### PR TITLE
fix(compute): too small timestamp causes integer overflow

### LINKED ISSUE #6507: fix(compute): fix timestamp with timezone
### Describe the bug

As the title. 
Found by Bowen in https://github.com/risingwavelabs/sqlalchemy-risingwave/issues/15.
Now we only support `timestampz` after 1970.1.1.

We convert `Timestampz` to `i64` by `timestamp_nano`. It will panic due to integer overflow.

### To Reproduce

RisingWave:
```sql
dev=> CREATE TABLE t (v FLOAT, ts TIMESTAMP WITH TIME ZONE);
CREATE_TABLE
dev=> INSERT INTO t VALUES (1.0, '022-11-15 15:35:40+08:00');
ERROR:  QueryError: internal error: internal error: error reading a body from connection: broken pipe
```

Log of compute node:
```sh
thread 'risingwave-batch-tasks' panicked at 'attempt to multiply with overflow', /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.22/src/naive/datetime/mod.rs:392:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:115:5
   3: chrono::naive::datetime::NaiveDateTime::timestamp_nanos
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.22/src/naive/datetime/mod.rs:392:21
   4: chrono::datetime::DateTime<Tz>::timestamp_nanos
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.22/src/datetime/mod.rs:270:9
   5: risingwave_expr::vector_op::cast::str_to_timestampz::{{closure}}
             at ./src/expr/src/vector_op/cast.rs:154:20
   6: core::result::Result<T,E>::map
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:775:25
   7: risingwave_expr::vector_op::cast::str_to_timestampz
             at ./src/expr/src/vector_op/cast.rs:153:5
   8: core::ops::function::Fn::call
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:78:5
   9: <risingwave_expr::expr::template::UnaryExpression<IA1,OA,F> as risingwave_expr::expr::Expression>::eval
             at ./src/expr/src/expr/template.rs:327:1
  10: risingwave_batch::executor::values::ValuesExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/values.rs:85:35
  11: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  12: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/stream.rs:120:9
  13: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/mod.rs:1626:9
  14: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/next.rs:32:9
  15: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/huahua/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  16: risingwave_batch::executor::trace::TraceExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/trace.rs:67:69
```

### Expected behavior

PostgreSQL:
```sql
postgres=# CREATE TABLE t (v FLOAT, ts TIMESTAMP WITH TIME ZONE);
CREATE TABLE
postgres=# INSERT INTO t VALUES (1.0, '022-11-15 15:35:40+08:00');
INSERT 0 1
postgres=# select * from t;
 v |              ts
---+------------------------------
 1 | 0022-11-15 15:41:23+08:05:43
(1 row)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HuaHuaY**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

as the title

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #6507

### CODE REVIEW

**Review by BowenXiao1999 — COMMENTED** [review]
LGTM

File: src/expr/src/vector_op/cast.rs [hunk 1]
```diff
@@ -183,7 +183,9 @@ pub fn i64_to_timestampz(t: i64) -> Result<i64> {
 pub fn timestampz_to_utc_string(elem: i64) -> String {
     // Just a meaningful representation as placeholder. The real implementation depends on TimeZone
     // from session. See #3552.
-    let instant = Utc.timestamp_nanos(elem * 1000);
+    let secs = elem / 1_000_000;
+    let nsecs = (elem % 1_000_000) * 1000;
+    let instant = Utc.timestamp_opt(secs, nsecs as u32).unwrap();
```
Comment (xiangjinwu) [inline src/expr/src/vector_op/cast.rs:188]: * What if `elem` is negative? What would happen during the `usecs as u32` cast?
* Is the `unwrap()` guaranteed to never panic?

Comment (HuaHuaY) [reply src/expr/src/vector_op/cast.rs:188]: 1. secs will be negative.
2. no, it will panic if timestamp value is too big. This PR just makes it not as easy as before to panic

Comment (xiangjinwu) [reply src/expr/src/vector_op/cast.rs:188]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e2f7bce89ffb0097e25f3039d8da1870

**Review by xiangjinwu — APPROVED** [review]
Could you add some test cases?

**Review by BowenXiao1999 — APPROVED** [review]
