### PR TITLE
fix: column index mapping bug of `LogicalExpand::rewrite_with_input`

### LINKED ISSUE #12620: type mismatch, array builder type: Utf8, scalar type: Int64
### Describe the bug

[error.sql.log](https://github.com/risingwavelabs/risingwave/files/12798445/error.sql.log)

[compute-node-5687.log](https://github.com/risingwavelabs/risingwave/files/12798457/compute-node-5687.log)

More details to follow.

### Error message/log

```text
thread 'risingwave-streaming-actor' panicked at /risingwave/src/common/src/array/mod.rs:479:29:
type mismatch, array builder type: Utf8, scalar type: Int64
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

https://buildkite.com/risingwavelabs/main-cron/builds/897

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #12620.

Bug explanation: Because of the usage of `ColIndexMapping::without_target_size`, sometimes the derived `target_size` is not the same as output schema length when doing `logical_rewrite_for_stream`. The previous buggy `LogicalExpand::rewrite_with_input` wrongly assumed the `target_size` of `input_col_change` as `new_input_col_num`.

Each commit does one thing, reviewers may browse through commit history to see changes more clearly.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM, thanks for the fix. I am curious about what would the target size be if the target size of input_col_change is different from the length of the input schema.

File: src/frontend/src/optimizer/plan_node/logical_expand.rs [hunk 1]
```diff
@@ -94,14 +94,30 @@ impl PlanTreeNodeUnary for LogicalExpand {
...
-            mapping
-                .iter()
-                .map(|p| p.map(|i| i + new_input_col_num))
-                .collect_vec()
-        });
-        mapping.push(Some(2 * new_input_col_num));
+
+        let old_out_len = self.schema().len();
+        let old_in_len = self.input().schema().len();
+        let new_in_len = input.schema().len();
```
Comment (kwannoel) [inline src/frontend/src/optimizer/plan_node/logical_expand.rs:100]: Why are these different? This part seems confusing to me.

Comment (kwannoel) [reply src/frontend/src/optimizer/plan_node/logical_expand.rs:100]: What does "old" and "new" mean here?

File: src/frontend/src/optimizer/plan_node/logical_expand.rs [hunk 2]
```diff
@@ -94,14 +94,30 @@ impl PlanTreeNodeUnary for LogicalExpand {
                     .collect_vec()
             })
             .collect_vec();
-        let (mut mapping, new_input_col_num) = input_col_change.into_parts();
```
Comment (kwannoel) [inline src/frontend/src/optimizer/plan_node/logical_expand.rs:97]: IIUC `new_input_col_num` is the offset we originally used.

After this PR we use `new_in_len`. What's the difference?

**Comment by kwannoel** [comment]
> Bug explanation: Because of the usage of ColIndexMapping::without_target_size, sometimes the derived target_size is not the same as output schema length when doing logical_rewrite_for_stream. The previous buggy LogicalExpand::rewrite_with_input wrongly assumed the target_size of input_col_change as new_input_col_num.

Hmm I'm a little skeptical of the current way `without_target_size` is used. Even though it has "no target size", the method still initializes a target size as:
```rs
            Some(target_max) => target_max + 1,
```

I think `target_size` should be `None` in the context of `without_target_size` to make it type-safe, and let the user handle it.

> Each commit does one thing, reviewers may browse through commit history to see changes more clearly.

That makes it a lot easier to review, thanks for highlighting it.

**Comment by stdrc** [comment]
> I am curious about what would the target size be if the target size of input_col_change is different from the length of the input schema.

@chenzl25 As Noel pointed out, it'll be max target index + 1.



> > Bug explanation: Because of the usage of ColIndexMapping::without_target_size, sometimes the derived target_size is not the same as output schema length when doing logical_rewrite_for_stream. The previous buggy LogicalExpand::rewrite_with_input wrongly assumed the target_size of input_col_change as new_input_col_num.
> 
> Hmm I'm a little skeptical of the current way `without_target_size` is used. Even though it has "no target size", the method still initializes a target size as:
> 
> ```rust
>             Some(target_max) => target_max + 1,
> ```
> 
> I think `target_size` should be `None` in the context of `without_target_size` to make it type-safe, and let the user handle it.

@kwannoel Agree. IIUC the `target_size` here, when given one, is just to ensure each target index in the mapping is valid. Setting `target_size` to max + 1 is meaningless. OTOH, since we set it, we should by no means assume `target_size` equal to _output schema length_.

File: src/frontend/src/optimizer/plan_node/logical_expand.rs (hunk 2 above)
Comment (stdrc) [reply src/frontend/src/optimizer/plan_node/logical_expand.rs:97]: On their naming, the meaning of `new_input_col_num` is exactly the same as that of `new_in_len`, the difference is in what we assign to them.

File: src/frontend/src/optimizer/plan_node/logical_expand.rs (hunk 1 above)
Comment (stdrc) [reply src/frontend/src/optimizer/plan_node/logical_expand.rs:100]: > This part seems confusing to me.

Indeed, really confusing. I couldn't find why it's fixed after I fixed it. Finally I realized the logic here is exactly the same as previous one (just clearer), the difference is the value of `new_in_len`.

**Comment by stdrc** [comment]
Submitted an issue to track the `target_size` problem: https://github.com/risingwavelabs/risingwave/issues/13100

File: src/frontend/src/optimizer/plan_node/logical_expand.rs (hunk 1 above)
Comment (kwannoel) [reply src/frontend/src/optimizer/plan_node/logical_expand.rs:100]: Still don't get it.
Why are these different?
```
self.input().schema().len();
input.schema().len()
```

Seems like something should be changed here. Maybe not in this PR, because it was the same logic as previously. But we should fix it.

Comment (stdrc) [reply src/frontend/src/optimizer/plan_node/logical_expand.rs:100]: Oh, this method is to replace the `self.input` with a new `input`, so `input != self.input()`

**Review by kwannoel — APPROVED** [review]

**Review by st1page — APPROVED** [review]
LGTM, but we should assume the `target_size` of `input_col_change` as `new_input_col_num` by removing all `Mapping::without_target_size`. It should be ensured by the implementation of `rewrite_with_input`
