### PR TITLE
fix(pgwire): infer query type using parser rather than  naive string comparison 

### LINKED ISSUE #8089: please trim the sql statement before processing it - e.g. `<space>select 1` fails
### Describe the bug

Example in java

standalone repro : (uses testcontainers)
```
git clone https://github.com/cameronbraid/risingwave-java-received-resultset-tuples-but-no-field-structure-for-them-reproduction
cd risingwave-java-received-resultset-tuples-but-no-field-structure-for-them-reproduction
mvn test
```

example code : 

```
var list = handle.createQuery(" select 1").mapToMap().list();
```

```
java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2301)
 at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
 at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
 at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
 at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
 at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
 at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
 at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1787)
 at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:94)
 at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:58)
 at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:269)
 at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:325)
 at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:314)
 at risingwave.TestCase.testCase(TestCase.java:60)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ZENOTME**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

as title.
fix #8089

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/utils/pgwire/src/pg_response.rs [hunk 1]
```diff
@@ -118,6 +119,34 @@ where
...
+                }
+            }
+            Statement::Update { returning, .. } => {
+                if returning.is_empty() {
+                    Ok(StatementType::UPDATE)
+                } else {
+                    Ok(StatementType::UPDATE_RETURNING)
+                }
+            }
+            _ => Err("unsupported statement type".to_string()),
```
Comment (BugenZhao) [inline src/utils/pgwire/src/pg_response.rs:146]: Are these statement types sufficient  for us?

File: src/utils/pgwire/src/pg_protocol.rs [hunk 2]
```diff
@@ -396,21 +396,24 @@ where
...
-        // TODO: regard DML with RETURNING as a query
         let is_query_sql = {
-            let lower_sql = sql.to_ascii_lowercase();
-            lower_sql.starts_with("select")
-                || lower_sql.starts_with("values")
-                || lower_sql.starts_with("show")
-                || lower_sql.starts_with("with")
-                || lower_sql.starts_with("describe")
-                || lower_sql.starts_with("explain")
+            let stmts = Parser::parse_sql(sql)
```
Comment (BugenZhao) [inline src/utils/pgwire/src/pg_protocol.rs:400]: Does it mean that we need to parse this statement multiple times? Is there a way to avoid that?

File: src/utils/pgwire/src/pg_response.rs [hunk 3]
```diff
@@ -118,6 +119,34 @@ where
 }
 
 impl StatementType {
+    pub fn infer_from_statement(stmt: &Statement) -> Result<Self, String> {
```
Comment (liurenjie1024) [inline src/utils/pgwire/src/pg_response.rs:122]: How about implement `TryFrom`?

File: src/utils/pgwire/src/pg_protocol.rs (hunk 2 above)
Comment (liurenjie1024) [reply src/utils/pgwire/src/pg_protocol.rs:400]: I think if we want to avoid multi-parsing SQL times, we need to store the parsed statement in session, and in later messages, the pg client is supposed to send data only rather SQL again.

**Review by liurenjie1024 — APPROVED** [review]
Generally LGTM, but as @BugenZhao  suggested, we should avoid parsing SQL multi times. But it can be seen as an optimization, and we can do it later.

File: src/utils/pgwire/src/pg_protocol.rs (hunk 2 above)
Comment (Eurekaaw) [reply src/utils/pgwire/src/pg_protocol.rs:400]: Can we have this info included in `FeParseMessage`?

Comment (ZENOTME) [reply src/utils/pgwire/src/pg_protocol.rs:400]: > Does it mean that we need to parse this statement multiple times? Is there a way to avoid that?

Yes. To avoid to parse multiple times, we need to refactor extended query mode in pgwire (as @liurenjie1024 says). This will be complete in #8112.

>I think if we want to avoid multi-parsing SQL times, we need to store the parsed statement in session, and in later messages, the pg client is supposed to send data only rather SQL again.

But this require a big refactor and a new design. This PR is to fix #8089 first.

**Review by Eurekaaw — APPROVED** [review]
fair to leave refractor to future tasks, LGTM!

File: src/utils/pgwire/src/pg_response.rs (hunk 3 above)
Comment (ZENOTME) [reply src/utils/pgwire/src/pg_response.rs:122]: Interface like `StatementType::from(Statement)` seems not clear enough because Statement and StatementType is not the type in the dimension (e.g i32 and i64 are at the same dimension. They are all integral)🤔? The relation between them is that StatementType is infer from Statement.

File: src/utils/pgwire/src/pg_response.rs (hunk 1 above)
Comment (ZENOTME) [reply src/utils/pgwire/src/pg_response.rs:193]: It's sufficient now.🤣
