### PR TITLE
fix(connector): support more data types in JDBC sink

### LINKED ISSUE #8647: feat(JDBCSink): supported TIMESTAMP type
### Describe the bug

```
2023-03-20 08:48:38,584 ERROR [grpc-default-executor-6] connector.SinkStreamObserver:168 - sink task error: 
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: unsupported type TIMESTAMP
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.49.0.jar:1.49.0]
        at com.risingwave.connector.JsonDeserializer.validateJsonDataTypes(JsonDeserializer.java:145) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.JsonDeserializer.lambda$deserialize$0(JsonDeserializer.java:62) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[?:?]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[?:?]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[?:?]
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
        at com.risingwave.connector.api.sink.TrivialCloseIterator.hasNext(TrivialCloseIterator.java:34) ~[connector-api-1.0-SNAPSHOT.jar:?]
        at com.risingwave.metrics.MonitoredRowIterator.hasNext(MonitoredRowIterator.java:29) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:229) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:125) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:33) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #8647

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

File: ci/scripts/e2e-sink-test.sh [hunk 1]
```diff
@@ -31,7 +31,8 @@ mv target/debug/risedev-dev-"$profile" target/debug/risedev-dev
 mv target/debug/librisingwave_java_binding.so-"$profile" target/debug/librisingwave_java_binding.so
 
 export RW_JAVA_BINDING_LIB_PATH=${PWD}/target/debug
-export RW_CONNECTOR_RPC_SINK_PAYLOAD_FORMAT=stream_chunk
+# TODO: Switch to stream_chunk encoding once it's completed, and then remove json encoding as well as this env var.
+export RW_CONNECTOR_RPC_SINK_PAYLOAD_FORMAT=json
```
Comment (fuyufjh) [inline ci/scripts/e2e-sink-test.sh:35]: Note that here I switched back to JSON encoding because it looks not so easy to implement decoding for decimal & timestamp right now.
