### PR TITLE
fix: return error if source executor failed to receive the first barrier

### LINKED ISSUE #6931: longevity panic: `unwrap()` in `source_executor.rs`
### Describe the bug

```
thread 'risingwave-streaming-actor' panicked at 'called `Option::unwrap()` on a `None` value', /risingwave/src/stream/src/executor/source/source_executor.rs:258:14
```

https://github.com/risingwavelabs/risingwave/blob/66df2f77a63458e78b0e7d6b2be1e3e69f0f5a0f/src/stream/src/executor/source/source_executor.rs#L258

Full logs:

https://rqa-logs.s3.ap-southeast-1.amazonaws.com/longevity/222_logs.txt

OR

https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Frwc-3-longevity-20221214-180848/log-events/ip-10-0-74-173.ap-southeast-1.compute.internal-risingwave.var.log.containers.risingwave-compute-1_rwc-3-longevity-20221214-180848_compute-5a7b1ee2a90c3f8ddf2cfea2c1993d7918d26f1aa3d199281c26bb3d4017855e.log$3FfilterPattern$3D

### To Reproduce

N/A

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tabVersion**
Signed-off-by: tabVersion <tabvision@bupt.icu>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

**This section will be used as the commit message. Please do not leave this empty!**

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

this is a temp fix for #6931, and I believe that this can happen in rare cases. 

From the log described in the issue, there is a failover that occurred before the panic. I think some part of meta failed to recover and the barrier channel closed for some reason.

It shows a possibility that meta node could fail to recover and compute node should be robots enough rather than panicking.  

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

resolve #6931

### CODE REVIEW

**Review by waruto210 — APPROVED** [review]
lgtm.

File: src/stream/src/executor/source/source_executor_v2.rs [hunk 1]
```diff
@@ -249,7 +250,13 @@ impl<S: StateStore> SourceExecutorV2<S> {
             .recv()
             .stack_trace("source_recv_first_barrier")
             .await
-            .unwrap();
+            .ok_or_else(|| {
+                StreamExecutorError::from(anyhow!(
+                    "failed to receive the first barrier, actor_id: {:?}, source_id: {:?}",
+                    self.ctx.id,
+                    self.identity
```
Comment (xx01cyx) [inline src/stream/src/executor/source/source_executor_v2.rs:257]: `self.identity` is not `source_id`. Maybe we should output `source_id` (`table_id` in `StreamSourceCore` for now and will be renamed to `source_id` soon) only when `stream_source_core` is `Some`.

**Review by xx01cyx — APPROVED** [review]
