### PR TITLE
fix: allow ENCODE BYTES use generated columns

### LINKED ISSUE #17959: feat(source): `ENCODE BYTES` should allow generated columns
https://github.com/risingwavelabs/risingwave/blob/e68a7bbe877e3de31c7abeeb28d081ad84b61f62/src/frontend/src/handler/create_source.rs#L759-L766

Some other format/encode branches above already handle generated columns explicitly.

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #17959

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/frontend/src/handler/create_source.rs [hunk 1]
```diff
@@ -697,6 +697,7 @@ pub(crate) fn bind_all_columns(
                 "Schema definition is required, either from SQL or schema registry.".to_string(),
             )));
         }
+        let non_generated_sql_defined_columns = non_generated_sql_columns(col_defs_from_sql);
```
Comment (tabVersion) [inline src/frontend/src/handler/create_source.rs:700]: Is there a term for normally defined columns? 🤣
non-generated sounds really weird

**Review by tabVersion — APPROVED** [review]
The impl LGTM, please consider a better var name.

File: src/frontend/src/handler/create_source.rs (hunk 1 above)
Comment (yuhao-su) [reply src/frontend/src/handler/create_source.rs:700]: I hope there is  🤔
