### PR TITLE
fix(sqlparser): distinguish table and table function

### LINKED ISSUE #5228: zero-arg table function is viewed as a table
### Describe the bug

_No response_

### To Reproduce

```sql
dev=> create table t(x int);
CREATE_TABLE
dev=> select * from t();
 x
---
(0 rows)
```

### Expected behavior

```sql
postgres=# create table t(x int);
CREATE TABLE
postgres=# select * from t();
ERROR:  function t() does not exist
LINE 1: select * from t();
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

close #5228

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

File: src/sqlparser/src/ast/query.rs [hunk 1]
```diff
@@ -311,8 +307,9 @@ pub enum TableFactor {
     },
     /// `<expr>[ AS <alias> ]`
     TableFunction {
-        expr: Expr,
+        name: ObjectName,
```
Comment (xxchan) [inline src/sqlparser/src/ast/query.rs:310]: The old syntax is ANSI `select * from TABLE(SOME_FUNCTION(some_arg))`, and it's parsing is already removed previously.

**Review by TennyZhuang — APPROVED** [review]
LGTM
