### PR TITLE
fix(source): resolve avro `Ref` during `access` without hack

### LINKED ISSUE #17020: Support Avro ref type in source
We added the support for Debezium avro, but not otherwise, which makes no sense.

A little background: In debezium, there are `after` and `before` sharing the same schema.

https://github.com/risingwavelabs/risingwave/blob/8dfae832334ae1dc0585dcae4b3071e9ee6c9b1d/src/connector/src/parser/debezium/avro_parser.rs#L83

BTW, this line is introduced in this huge refactor: https://github.com/risingwavelabs/risingwave/pull/10096, which is too confusing and scary. How does it work before?

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Sequel to #19601 and resolves #17020.

The recursive call is changed from `Self {schema: inner, relax_numeric: self.relax_numeric}.convert_to_datum(v, field_type)` into `self.convert_to_datum(inner, v, field_type)` so that
* The changing part `schema: inner` is passed as argument rather than keep reconstructing new `AvroParseOptions`.
* `self: AvroParseOptionsInner` captures the immutable "global" context: `relax_numeric: bool` and `refs: NamesRef<'a>`

On the use site, `self.schema` is changed to `self.lookup_ref(unresolved_schema)`. Note that introducing a new type to distinguish `resolved` from `unresolved` would not make it less error-prone for a careless developer - nothing prevents them from matching against unresolved `apache_avro::Schema` directly and ignoring `Schema::Ref`.

~~Full removal of `ResolvedAvroSchema` will be done in an immediate follow-up, to minimize the signature changes in this PR.~~ `ResolvedAvroSchema` will either be fully removed or repurposed to hold `HashMap<Name, Schema>` (an owned `NamesRef`) in a follow-up.

Same as #19601, this is intended to be part of v2.2 and NOT cherry-picked into earlier versions.

## Checklist

- [ ] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
:GTM

File: src/connector/codec/src/decoder/avro/mod.rs [hunk 1]
```diff
@@ -33,28 +33,46 @@ use super::{bail_uncategorized, uncategorized, Access, AccessError, AccessResult
 use crate::decoder::avro::schema::avro_schema_to_struct_field_name;
 
 #[derive(Clone)]
-/// Options for parsing an `AvroValue` into Datum, with an optional avro schema.
+/// Options for parsing an `AvroValue` into Datum, with a root avro schema.
 pub struct AvroParseOptions<'a> {
-    /// Currently, this schema is only used for decimal.
-    ///
-    /// FIXME: In theory we should use resolved schema.
-    /// e.g., it's possible that a field is a reference to a decimal or a record containing a decimal field.
```
Comment (xiangjinwu) [inline src/connector/codec/src/decoder/avro/mod.rs:41]: Now we can support _reference to a decimal or a record containing a decimal field_.
