### PR TITLE
fix(meta): allow multiple internal tables while dropping table

### LINKED ISSUE #8335: bug: Drop table with watermark panicked
### Describe the bug

```
thread 'risingwave-main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/meta/src/rpc/ddl_controller.rs:500:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:211:5
   4: risingwave_meta::rpc::ddl_controller::DdlController<S>::drop_table_inner::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:500:13
   5: risingwave_meta::rpc::ddl_controller::DdlController<S>::drop_streaming_job::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:279:21
   6: risingwave_meta::rpc::ddl_controller::DdlController<S>::run_command::{{closure}}::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:140:88
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/future/future.rs:125:9
   8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  11: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  12: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  14: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  15: ___rust_try
  16: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  17: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  18: tokio::runtime::task::harness::poll_future
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  19: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  20: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  21: tokio::runtime::task::raw::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  22: tokio::runtime::task::raw::RawTask::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  23: tokio::runtime::task::LocalNotified<S>::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  25: tokio::runtime::coop::with_budget
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  26: tokio::runtime::coop::budget
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  29: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  31: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  32: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
  34: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  35: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  37: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  38: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  40: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  41: ___rust_try
  42: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  43: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  44: tokio::runtime::task::harness::poll_future
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  46: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  47: tokio::runtime::task::raw::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  48: tokio::runtime::task::raw::RawTask::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  49: tokio::runtime::task::UnownedTask<S>::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
  50: tokio::runtime::blocking::pool::Task::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
  51: tokio::runtime::blocking::pool::Inner::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
  52: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sat Mar  4 13:37:19 UTC 2023 [risedev]: Program exited with 134
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

Similar to #8290

### PR DESCRIPTION
**Pull request by TennyZhuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

My PR **DOES NOT** contain user-facing changes

## What's changed and what's your intention?

closes #8335 

## Checklist For Contributors

- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

### CODE REVIEW

File: src/common/src/field_generator/timestamp.rs [hunk 1]
```diff
@@ -57,6 +59,7 @@ impl TimestampField {
             // default max_past = 1 day
             DEFAULT_MAX_PAST
         };
+        debug!(?local_now, ?max_past, "parse timestamp field option");
```
Comment (yuhao-su) [inline src/common/src/field_generator/timestamp.rs:62]: will this generate too many debug info?

Comment (TennyZhuang) [reply src/common/src/field_generator/timestamp.rs:62]: Only one record per field while creating table/source.

**Review by yuhao-su — APPROVED** [review]
LGTM

**Review by yezizp2012 — APPROVED** [review]
