### PR TITLE
fix(stream): fix TopN cache by only inserting into high if the row is top

### LINKED ISSUE #8570: Stream TopN panics
### Describe the bug

```
panicked at 'assertion failed: self.middle.len() <= self.limit', /risingwave/src/stream/src/executor/top_n/top_n_cache.rs:140:13",
```

### To Reproduce

```sql
create table hackernews_newstories( 
   "id" INTEGER,
   "title" VARCHAR,
   "author" VARCHAR,
   "score" INTEGER,
   "url" VARCHAR,
   "type" VARCHAR,
   "summary" VARCHAR,
   "keyphrases" VARCHAR[],
    "timestamp" TIMESTAMP)
WITH (
   connector = 'datagen' );



CREATE MATERIALIZED VIEW top_keyphrases_latest_5min AS WITH now_timestamp AS (
    SELECT MAX(timestamp) AS now_timestamp
    FROM hackernews_newstories
),
top_keyphrases_hop_5s_5min AS (
    SELECT count(*) as count,
        keyphrases,
        window_start,
        window_end
    FROM (
            SELECT unnest(keyphrases) as keyphrases,
                timestamp,
                window_start,
                window_end
            FROM HOP (
                    hackernews_newstories,
                    timestamp,
                    INTERVAL '5' SECOND,
                    INTERVAL '5' MINUTE
                )
        )
    GROUP BY keyphrases,
        window_start,
        window_end
    ORDER BY window_start DESC
)
SELECT count,
    keyphrases,
    window_end
FROM top_keyphrases_hop_5s_5min
WHERE window_end = (
        SELECT window_end
        FROM top_keyphrases_hop_5s_5min
        WHERE window_end >= (
                SELECT now_timestamp
                FROM now_timestamp
            )
        ORDER BY window_end ASC
        LIMIT 1
    )
ORDER BY window_end DESC;
```

Then wait a while. easily reproduable.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Quick fix #8570 -- without performance in mind! @@BugenZhao mentioned there's a `sync` flag in the Min/Max aggregation cache. I'm not sure whether we should do the same (or other methods) here. 

I manually tested the original case in #8570, and didn't find problem yet.

Also added some debug utilities.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
Wait, isn't this silly implementation means that we don't need the high cache at all..? 😅

**Comment by xxchan** [comment]
f575c6333cc29bd4907c6c04b4ad4b9b6ca19ad0 is the first bad commit

**Review by st1page — COMMENTED** [review]
LGTM as a quick fix. But I think we can do further optimization. The high cache does not need to be full and we only need to ensure it cache the topn elements and we only need to do check the inserted element with its cached min element when inserting to it

**Review by st1page — APPROVED** [review]

**Comment by xxchan** [comment]
I came up with a more fine-grained fix. 🥵

File: src/stream/src/executor/top_n/top_n_cache.rs [hunk 1]
```diff
@@ -214,6 +273,20 @@ impl TopNCacheTrait for TopNCache<false> {
...
+            if need_refill {
+                managed_state
+                    .fill_high_cache(
+                        group_key,
+                        self,
+                        self.middle.last_key_value().unwrap().0.clone(),
+                        self.high_capacity,
+                    )
+                    .await?;
+            }
```
Comment (st1page) [inline src/stream/src/executor/top_n/top_n_cache.rs:289]: it seems that we fill the high cache too many times, which makes the e2e test timeout :thinking:

File: src/common/src/row/mod.rs [hunk 2]
```diff
@@ -145,6 +146,18 @@ pub trait RowExt: Row {
     {
         assert_row(Project::new(self, indices))
     }
+
+    fn to_pretty_string(&self) -> String {
```
Comment (BugenZhao) [inline src/common/src/row/mod.rs:150]: May return an anonymous `impl Display` instead of constructing a `String` here?

File: src/stream/src/executor/top_n/top_n_cache.rs [hunk 3]
```diff
@@ -159,20 +219,60 @@ impl<const WITH_TIES: bool> TopNCache<WITH_TIES> {
...
+                self.is_high_cache_dirty = false;
+            }
+            self.high.insert(cache_key, row);
+        } else {
+            let high_last = self.high.last_entry().unwrap();
+            if cache_key <= *high_last.key() {
+                high_last.remove_entry();
+                self.high.insert(cache_key, row);
+            }
+        }
```
Comment (st1page) [inline src/stream/src/executor/top_n/top_n_cache.rs:256]: Maybe we do not need to refill the high cache here and just ignore the insert operation when `elem_to_compare_with_high.0 > *high_last.key()` so that we do not need to maintain the `is_high_cache_dirty` and the high cache will store the TopK elements forever.

Comment (xxchan) [reply src/stream/src/executor/top_n/top_n_cache.rs]: updated

File: src/stream/src/executor/top_n/top_n_cache.rs [hunk 4]
```diff
@@ -153,11 +211,33 @@ impl<const WITH_TIES: bool> TopNCache<WITH_TIES> {
...
-        if full {
-            assert!(self.is_middle_cache_full());
+        self.high.len() >= self.high_capacity
+    }
+
+    /// Use this method instead of `self.high.insert` directly when possible.
+    ///
+    /// It only inserts into high cache if the key is smaller than the largest key in the high
+    /// cache. Otherwise, we simply ignore the row. We will wait until the high cache becomes
+    /// empty and fill it at that time.
```
Comment (st1page) [inline src/stream/src/executor/top_n/top_n_cache.rs:221]: :heart:

**Review by st1page — APPROVED** [review]
LGTM
