### PR TITLE
fix(binder): multiple unions should retain the same cte_to_relation context

### LINKED ISSUE #9004: cte: cannot Catalog error: table or source not found
### Describe the bug

```
dev=> with table1 as ( select 1 as n) select * from table1;
 n 
---
 1
(1 row)

dev=> with table1 as ( select 1 as n), table2 as ( select 2 as n) select * from table1 union select * from table2;
 n 
---
 1
 2
(2 rows)

dev=> with table1 as ( select 1 as n), table2 as ( select 2 as n), table3 as ( select 3 as n) select * from table1 union select * from table2 union select * from table3;
ERROR:  QueryError: Catalog error: table or source not found: table3

dev=> with table1 as ( select 1 as n), table3 as ( select 3 as n), table2 as ( select 2 as n) select * from table1 union select * from table2 union select * from table3;
ERROR:  QueryError: Catalog error: table or source not found: table3

dev=> with table1 as ( select 1 as n), table3 as ( select 3 as n), table2 as ( select 2 as n) select * from table1 union select * from table2;
 n 
---
 1
 2
(2 rows)

dev=> with table1 as ( select 1 as n), table3 as ( select 3 as n), table2 as ( select 2 as n) select * from table1 union select * from table3;
 n 
---
 1
 3
(2 rows)

dev=> with table1 as ( select 1 as n), table3 as ( select 3 as n), table2 as ( select 2 as n) select * from table1 union select * from table3 union select * from table2;
ERROR:  QueryError: Catalog error: table or source not found: table2

dev=> with table1 as ( select 1 as n), table3 as ( select 3 as n), table2 as ( select 2 as n) select * from table2 union select * from table3 union select * from table1;
ERROR:  QueryError: Catalog error: table or source not found: table1
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

closes #9004 

## Checklist For Contributors

~- [ ] I have written necessary rustdoc comments~
- [x] I have added necessary unit tests and integration tests
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.~

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/frontend/src/binder/set_expr.rs [hunk 1]
```diff
@@ -160,6 +160,7 @@ impl Binder {
                         // select a from t2 union all select b from t2 order by a+1; should throw an
                         // error.
                         self.context = BindContext::default();
+                        self.context.cte_to_relation = new_context.cte_to_relation;
```
Comment (lmatz) [inline src/frontend/src/binder/set_expr.rs:163]: since CTE can only be defined at the top level, I suppose I can just retain the `cte_to_relation` without concern?

**Review by fuyufjh — APPROVED** [review]
