### PR TITLE
fix(cdc): use `lsn_commit` and `lsn_proc` for pg cdc offset

### LINKED ISSUE #22369: Use lsn_commit and lsn_proc as offset for Postgres CDC
Currently we are using `lsn` for Postgres CDC offset, instead we should use `lsn_commit` and `lsn_proc` to get a total order between messages in interleaving transactions.

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

fix #22369

This pull request will use `lsn_commit` and `lsn_proc` to give a total order to debezium change event.

Previously the `lsn` we used only reflect the order of the event inside a transaction. 

When there are interleaving TXs, consider the following case:
```
LSN 100  T1: INSERT …
LSN 108  T2: INSERT …
LSN 112  T1: INSERT …
LSN 118  T2: COMMIT        -- T2 commits first
LSN 124  T1: INSERT …
LSN 130  T1: COMMIT        -- T1 commits later
```
The change events from debezium will be grouped together by TXs. So they will arrive as

```
LSN 108  T2: INSERT …
LSN 118  T2: COMMIT        -- T2 commits first
LSN 100  T1: INSERT …
LSN 112  T1: INSERT …
LSN 124  T1: INSERT …
LSN 130  T1: COMMIT        -- T1 commits later
```

When T2 and T1 were separated into 2 chunks, the `LSN 110 112` in T1 could be filtered by `mark_cdc_chunk` when backfilling, resulting in missing data.

### Test coverage improvements:

* **Postgres Offset Tests (`src/connector/src/source/cdc/external/postgres.rs`)**: Added tests for `PartialOrd` behavior with new fields and for Debezium offset parsing to validate field presence and error handling.

### Code cleanup:

* **Snapshot Reading Logic (`src/stream/src/executor/backfill/cdc/upstream_table/snapshot.rs`)**: Removed unreachable code in the snapshot reading loop for improved clarity.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by yuhao-su** [comment]
> However, I think it is better to have a test coverage on the issue. 

It's very hard to do the test because it happens when backfilling. I did modify some code locally to reproduce it more easily.

File: src/connector/src/source/cdc/external/postgres.rs [hunk 1]
```diff
@@ -40,12 +40,35 @@ pub struct PostgresOffset {
...
+        match (
+            self.lsn_commit,
+            self.lsn_proc,
+            other.lsn_commit,
+            other.lsn_proc,
+        ) {
+            (_, Some(self_proc), _, Some(other_proc)) => {
+                // if both have `lsn_commit` and `lsn_proc`, compare `lsn_commit` first, then `lsn_proc`
+                // if `lsn_commit` is None, fall back to `lsn_proc`
+                match self.lsn_commit.partial_cmp(&other.lsn_commit) {
```
Comment (BugenZhao) [inline src/connector/src/source/cdc/external/postgres.rs]: This looks confusing to me as it's mixing `Option` from field and `Option` from `partial_ord`. There's seems no need to implement `PartialOrd`. We may consider implement `Ord` instead and forward `PartialOrd` impl to `Some(self.cmp(other))`.

Comment (yuhao-su) [reply src/connector/src/source/cdc/external/postgres.rs]: > mixing Option from field and Option from partial_ord

I not sure if I got your point. But the returning value of the implemented partialord are all from `partial_cmp` but not directly related to the vlaue of option of `lsn_proc`

**Review by wcy-fdu — APPROVED** [review]
LGTM! Good Catch!

File: src/connector/src/source/cdc/external/postgres.rs (hunk 1 above)
Comment (BugenZhao) [reply src/connector/src/source/cdc/external/postgres.rs]: All fields here are primitive and implement `Ord`. I mean shall we also directly implement `Ord` here for clarity?

Comment (yuhao-su) [reply src/connector/src/source/cdc/external/postgres.rs]: It is indeed a total order. I'll try do that

**Review by BugenZhao — APPROVED** [review]

File: src/connector/src/source/cdc/external/postgres.rs [hunk 2]
```diff
@@ -56,15 +102,27 @@ impl PostgresOffset {
...
+
+        // `lsn_commit` may not be present in the offset for the first tx.
+        let lsn_commit = dbz_offset.source_offset.lsn_commit;
+
+        let lsn_proc = dbz_offset
+            .source_offset
+            .lsn_proc
+            .context("invalid postgres lsn_proc")?;
+
         Ok(Self {
```
Comment (zwang28) [inline src/connector/src/source/cdc/external/postgres.rs:130]: `lsn_commit` and `lsn_proc` should be set in `PostgresExternalTableReader::current_cdc_offset` as well?
Although I guess it's difficult / impossible to obtain them?

Comment (zwang28) [reply src/connector/src/source/cdc/external/postgres.rs:130]: It leads to the branch? i.e. `lsn_commit and lsn_proc being both None` causes the fix in this PR being skipped, which means the `filtering by offset logic` is still not 100% safe.
```
// Fall back to lsn comparison when either lsn_commit or lsn_proc is missing
self.lsn.cmp(&other.lsn)
```

Comment (yuhao-su) [reply src/connector/src/source/cdc/external/postgres.rs:130]: lsn_commit is maintained by dbz not pg. And there is no way to have that before the last tx commit.

> which means the filtering by offset logic is still not 100% safe.

You are probably right. The first `current_cdc_offset` can still cause unsafe filter.

Comment (zwang28) [reply src/connector/src/source/cdc/external/postgres.rs:130]: Can we initialize the `last_binlog_offset` on the first `get_cdc_chunk_last_offset` rather than by `PostgresExternalTableReader::current_cdc_offset` in `CdcBackfillExecutor`?
Note that if applying this change, do remember to change [this](https://github.com/risingwavelabs/risingwave/blob/main/src/stream/src/executor/backfill/cdc/state.rs#L71) because it can be None now.

Comment (zwang28) [reply src/connector/src/source/cdc/external/postgres.rs:130]: > // Fall back to lsn comparison when either lsn_commit or lsn_proc is missing
> self.lsn.cmp(&other.lsn)

We can add a warning here, and merge this PR. Since this PR has resolved the major issue.

**Review by zwang28 — APPROVED** [review]

**Comment by hzxa21** [comment]
CI fails at `different_pk_and_dist_key`. Confirmed with @wenym1. It is a flaky test caused by #23071. Retry can help.
