### PR TITLE
fix(binder): improve array cmp type inference

### LINKED ISSUE #5408: Panics when comparing varchar and array
### Describe the bug

_No response_

### To Reproduce

```sql
select 'a' = array['a'];

thread 'risingwave-main' panicked at 'Functions returning struct or list can not be inferred. Please use `FunctionCall::new_unchecked`.', src/common/src/types/mod.rs:147:47
```

### Expected behavior

_No response_

### Additional context

This won't panic:
```sql
select 1 = array[1];
ERROR:  QueryError: Feature is not yet implemented: Equal[Int32, List]
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
```

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fixes #5408, and also disallows comparison between arrays of different types.

When comparing an `unknown` literal (e.g. `null` or `'{1}'`) with an array, it should be casted to the same `DataType::List`. As our general inference rule only handles `DataTypeName`, this requires one more arm in the special handling logic.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

File: src/frontend/src/expr/type_inference/func.rs [hunk 1]
```diff
@@ -157,6 +164,54 @@ fn infer_type_for_special(
...
+        | ExprType::NotEqual
+        | ExprType::LessThan
+        | ExprType::LessThanOrEqual
+        | ExprType::GreaterThan
+        | ExprType::GreaterThanOrEqual
+        | ExprType::IsDistinctFrom
+        | ExprType::IsNotDistinctFrom => {
+            ensure_arity!("cmp", | inputs | == 2);
+            match (inputs[0].is_unknown(), inputs[1].is_unknown()) {
+                // `'a' = null` handled by general rules later
```
Comment (CAJan93) [inline src/frontend/src/expr/type_inference/func.rs:177]: Can this also be `null = null`?

File: src/frontend/planner_test/tests/testdata/array.yaml [hunk 2]
```diff
@@ -160,3 +160,19 @@
   logical_plan: |
     LogicalProject { exprs: [Array('a':Varchar, 'b':Varchar)::Varchar] }
     └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
+- name: compare with null
+  sql: |
+    select null = array[1];
+  logical_plan: |
+    LogicalProject { exprs: [(null:List { datatype: Int32 } = Array(1:Int32))] }
+    └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
```
Comment (CAJan93) [inline src/frontend/planner_test/tests/testdata/array.yaml:168]:
```suggestion
- name: compare null with null 1
sql: |
  select null = null;
logical_plan: |
  BatchProject { exprs: [(null:Varchar = null:Varchar)] }
  └─BatchValues { rows: [[]] }
  - name: compare null with null 2
sql: |
  select null < null;
logical_plan: |
  BatchProject { exprs: [(null:Varchar < null:Varchar)] }
  └─BatchValues { rows: [[]] }
- name: compare with null
sql: |
  select null = array[1];
logical_plan: |
  LogicalProject { exprs: [(null:List { datatype: Int32 } = Array(1:Int32))] }
  └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
```

Comment (CAJan93) [inline src/frontend/planner_test/tests/testdata/array.yaml:168]:
```suggestion
- name: compare with null
sql: |
  select null = array[1];
logical_plan: |
  LogicalProject { exprs: [(null:List { datatype: Int32 } = Array(1:Int32))] }
  └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
- name: compare null with null 1
sql: |
  select null = null;
logical_plan: |
  BatchProject { exprs: [(null:Varchar = null:Varchar)] }
  └─BatchValues { rows: [[]] }
  - name: compare null with null 2
sql: |
  select null < null;
logical_plan: |
  BatchProject { exprs: [(null:Varchar < null:Varchar)] }
  └─BatchValues { rows: [[]] }
```

[the remark this answers is not in the document]
Comment (CAJan93) [reply src/frontend/planner_test/tests/testdata/array.yaml:168]: Maybe also add comparisons between two `null` values?

File: src/frontend/src/expr/type_inference/func.rs [hunk 3]
```diff
@@ -157,6 +164,54 @@ fn infer_type_for_special(
...
+                // Types of both sides are known. Continue.
+                (false, false) => {}
+            }
+            let ok = match (inputs[0].return_type(), inputs[1].return_type()) {
+                // TODO(#3692): handle `Struct`
+                // It should tolerate field name differences and allow castable types.
+                // `row(int, date) = row(bigint, timestamp)`
+
+                // However, PostgreSQL disallows `int[] = bigint[]`
+                (l @ DataType::List { .. }, r @ DataType::List { .. }) => l == r,
```
Comment (CAJan93) [inline src/frontend/src/expr/type_inference/func.rs:200]: Really like this line. Quite elegant 👍

File: src/frontend/src/expr/type_inference/func.rs [hunk 4]
```diff
@@ -157,6 +164,54 @@ fn infer_type_for_special(
                 _ => Ok(None),
             }
         }
+        ExprType::Equal
+        | ExprType::NotEqual
+        | ExprType::LessThan
+        | ExprType::LessThanOrEqual
+        | ExprType::GreaterThan
+        | ExprType::GreaterThanOrEqual
+        | ExprType::IsDistinctFrom
```
[the remark this answers is not in the document]
Comment (xiangjinwu) [reply src/frontend/src/expr/type_inference/func.rs:173]: Guess it belongs to [user doc](https://www.risingwave.dev/docs/latest/sql-function-comparison/) rather than inline comments. Thanks for the suggestion.

File: src/frontend/src/expr/type_inference/func.rs (hunk 1 above)
Comment (xiangjinwu) [reply src/frontend/src/expr/type_inference/func.rs:177]: Yes. Both literal `null` and literals with single quotes (e.g. `'a'` or `'1'`) are considered to be `unknown` type.

File: src/frontend/src/expr/type_inference/func.rs [hunk 5]
```diff
@@ -157,6 +164,54 @@ fn infer_type_for_special(
...
+                }
+                // Types of both sides are known. Continue.
+                (false, false) => {}
+            }
+            let ok = match (inputs[0].return_type(), inputs[1].return_type()) {
+                // TODO(#3692): handle `Struct`
+                // It should tolerate field name differences and allow castable types.
+                // `row(int, date) = row(bigint, timestamp)`
+
+                // However, PostgreSQL disallows `int[] = bigint[]`
```
[the remark this answers is not in the document]
Comment (xiangjinwu) [reply src/frontend/src/expr/type_inference/func.rs:199]: `However` is contrasting PostgreSQL's behavior between row/struct and array/list, rather than contrasting between PostgreSQL and us. I will update the wording to make it clear.

**Review by neverchanje — APPROVED** [review]
This PR as a bugfix is Ok. But I feel that maintaining special rules and general rules seperately will make this logic more complicate. Suppose I need to debug cmp expressions, I will first need to understand that they are scattered around two different places in the code. I think there could be some better way to implement this.
