### PR TITLE
fix: wait for bootstrap recovery to finish to fix flaky drop mview test

### LINKED ISSUE #11792: bug(meta): deterministic test failure: assertion failed: `(left == right)`
### Describe the bug

https://buildkite.com/risingwavelabs/main/builds/5363#018a02c1-2a99-4236-891a-866aa696a68a

Panicked at:

https://github.com/risingwavelabs/risingwave/blob/88a4daca851bf23bea68065426779aeea105bd8d/src/meta/src/stream/stream_manager.rs#L942

### Error message/log

```text
[2K_bk;t=1692263511558[31;1m        FAIL[0m [   0.706s] [35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m

_bk;t=1692263511558

_bk;t=1692263511558[31;1m--- [0m[31;1mSTDOUT:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692263511558

_bk;t=1692263511558running 1 test

_bk;t=1692263511558test is runner,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558test is drop,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558test stream::stream_manager::tests::test_drop_materialized_view ... FAILED

_bk;t=1692263511558

_bk;t=1692263511558failures:

_bk;t=1692263511558

_bk;t=1692263511558failures:

_bk;t=1692263511558    stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558

_bk;t=1692263511558test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 116 filtered out; finished in 0.66s

_bk;t=1692263511558

_bk;t=1692263511558[0m

_bk;t=1692263511559[31;1m--- [0m[31;1mSTDERR:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692263511559thread '<unnamed>' panicked at 'assertion failed: `(left == right)`

_bk;t=1692263511559  left: `0`,

_bk;t=1692263511559 right: `4`', src/meta/src/stream/stream_manager.rs:942:9

_bk;t=1692263511559stack backtrace:

_bk;t=1692263511559   0: rust_begin_unwind

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5

_bk;t=1692263511559   1: core::panicking::panic_fmt

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14

_bk;t=1692263511559   2: core::panicking::assert_failed_inner

_bk;t=1692263511559   3: core::panicking::assert_failed

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:228:5

_bk;t=1692263511559   4: risingwave_meta::stream::stream_manager::tests::test_drop_materialized_view::{{closure}}::{{closure}}

_bk;t=1692263511559             at ./src/stream/stream_manager.rs:942:9

_bk;t=1692263511559   5: madsim::sim::task::Executor::block_on::{{closure}}::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:230:32

_bk;t=1692263511559   6: <core::pin::Pin<P> as core::future::future::Future>::poll

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9

_bk;t=1692263511559   7: async_task::raw::RawTask<F,T,S,M>::run

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17

_bk;t=1692263511559   8: async_task::runnable::Runnable<M>::run

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18

_bk;t=1692263511559   9: madsim::sim::task::Executor::run_all_ready::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:50

_bk;t=1692263511559  10: std::panicking::try::do_call

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40

_bk;t=1692263511559  11: __rust_try

_bk;t=1692263511559  12: std::panicking::try

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19

_bk;t=1692263511559  13: std::panic::catch_unwind

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14

_bk;t=1692263511559  14: madsim::sim::task::Executor::run_all_ready

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:17

_bk;t=1692263511559  15: madsim::sim::task::Executor::block_on

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:238:13

_bk;t=1692263511559  16: madsim::sim::runtime::Runtime::block_on

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:9

_bk;t=1692263511559  17: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/builder.rs:128:35

_bk;t=1692263511559note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

_bk;t=1692263511559context: node=0 "main", task=320 (spawned at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:19)

_bk;t=1692263511559note: run with `MADSIM_TEST_SEED=1692263510861490596` environment variable to reproduce this error

_bk;t=1692263511559[0m

_bk;t=1692263511559[32;1m     Running[0m [ 00:00:04] [=>]  692/992 : [1m16[0m running, [1m692[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692263511559[31;1m     Running[0m [ 00:00:04] [=>]  692/992 : [1m16[0m running, [1m692[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692263511559[31;1m     Running[0m [ 00:00:04] []  693/992 : [1m15[0m running, [1m692[0m [32;1mpassed[0m, [1m1[0m [31;1mfailed[0m, [1m12[0m [33;1mskipped[0m     [1A
[2K_bk;t=1692263511560[1B
[2K_bk;t=1692263511560[1A[32;1m        PASS[0m [   0.356s] [35;1mrisingwave_storage[0m [36mhummock::conflict_detector::test[0m[36m::[0m[34;1mtest_write_to_archived_epoch[0m
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #11792 .

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/meta/src/barrier/mod.rs [hunk 1]
```diff
@@ -577,9 +577,14 @@ where
             // consistency.
             // Even if there's no actor to recover, we still go through the recovery process to
             // inject the first `Initial` barrier.
```
Comment (BugenZhao) [inline src/meta/src/barrier/mod.rs:579]: The change will break this and there's no Initial barrier to be sent. 🥵

Comment (yezizp2012) [reply src/meta/src/barrier/mod.rs:579]: I see, then I guess simply adding a sleep in the test and left the initial recovery unchanged should also works. 🥵

File: src/meta/src/stream/stream_manager.rs [hunk 2]
```diff
@@ -918,6 +918,9 @@ mod tests {
     async fn test_drop_materialized_view() -> MetaResult<()> {
         let services = MockServices::start("127.0.0.1", 12334, false).await?;
 
+        // Wait for bootstrap_recovery to finish.
+        tokio::time::sleep(Duration::from_secs(2)).await;
```
Comment (BugenZhao) [inline src/meta/src/stream/stream_manager.rs:922]: Can we call `BarrierScheduler::wait_for_next_barrier_to_collect` to make this deterministic?

**Review by BugenZhao — COMMENTED** [review]
Rest LGTM

File: src/meta/src/stream/stream_manager.rs (hunk 2 above)
Comment (yezizp2012) [reply src/meta/src/stream/stream_manager.rs:922]: During recovery, the barrier scheduler will be marked as blocked and all commands will be aborted. It could still be possible that the bootstrap recovery fails the `FLUSH` command somehow. 🥵

Comment (BugenZhao) [reply src/meta/src/stream/stream_manager.rs:922]: Then what about repeating this until success? Since this is test codes, any hacks look good to me. I just don't want this to be flaky anymore in the future. 😂

Comment (yezizp2012) [reply src/meta/src/stream/stream_manager.rs:922]: Okay, that's also acceptable to me. I will change it.

**Review by BugenZhao — APPROVED** [review]
LGTM

File: src/meta/src/stream/stream_manager.rs [hunk 3]
```diff
@@ -804,6 +804,14 @@ mod tests {
 
             let (join_handle_2, shutdown_tx_2) = GlobalBarrierManager::start(barrier_manager).await;
 
+            // Wait until the bootstrap recovery is done.
+            loop {
+                tokio::time::sleep(Duration::from_millis(100)).await;
```
Comment (fuyufjh) [inline src/meta/src/stream/stream_manager.rs:809]: Better to put the `sleep` after 

```
if barrier_scheduler.flush(false).await.is_ok() {
    break;
}
```
