### PR TITLE
fix: ChunkBuilder asserts empty size only for debug build

### LINKED ISSUE #6551: CN crash due to dropping non-empty stream chunk builder
### Describe the bug

The issue was found when I was running a test that continuously adds new MVs (nexmark_q7) to a cluster. 

When there are 50+ MVs, 

1. Firstly compute node 1 encounters timeout when trying to read object store, subsequently causes actor exits.
2. Then compute node 1 crashes due to `dropping non-empty stream chunk builder`.
3. Thus meta cannot finish recovery.

### To Reproduce

Deploy a 3 compute node cluster and `bash run_tasks.sh` [here](https://github.com/risingwavelabs/risingwave/tree/wangzheng/test_lots_mv). (make sure meta:5690 and frontend:4566 are reachable specified in `run.sh`).
MVs will be continuously created. It will take minutes to trigger the issue (console running `bash run_tasks.sh` will receive error message).

### Expected behavior

- Transient object store error better not fail actor.
- CN shouldn't crash. ~~Recovery should succeed.~~

### Additional context

[cn-1-panic.log](https://github.com/risingwavelabs/risingwave/files/10080694/cn-1-panic.log)
[meta.log](https://github.com/risingwavelabs/risingwave/files/10080698/meta.log)
[cn-2.log](https://github.com/risingwavelabs/risingwave/files/10080696/cn-2.log)
[cn-0.log](https://github.com/risingwavelabs/risingwave/files/10080697/cn-0.log)
[compactor.log](https://github.com/risingwavelabs/risingwave/files/10080699/compactor.log)
[source.log](https://github.com/risingwavelabs/risingwave/files/10080701/source.log)

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

See https://github.com/risingwavelabs/risingwave/issues/6551

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

None
## Refer to a related PR or issue link (optional)

closes #6551

### CODE REVIEW

**Review by yuhao-su — APPROVED** [review]

File: src/stream/src/common/builder.rs [hunk 1]
```diff
@@ -45,7 +45,8 @@ pub struct StreamChunkBuilder {
 
 impl Drop for StreamChunkBuilder {
     fn drop(&mut self) {
-        assert_eq!(self.size, 0, "dropping non-empty stream chunk builder");
+        // Possible to fail in some corner cases but should not in unit tests
```
Comment (TennyZhuang) [inline src/stream/src/common/builder.rs:48]: If it's a test behavior, `cfg(test)` is better than debug_assert_eq.
