### PR TITLE
fix: support more types in kafka sink

### LINKED ISSUE #6759: Using timestamp type of variable in sink function should not cause the crash
### Describe the bug

From the below discussion in Risingwave Community channel, found this issue.
https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1670305270356339?thread_ts=1670227935.460609&cid=C02T3F7UYM6

### To Reproduce

_No response_

### Expected behavior

Should not cause a crash for the unimplemented type of the variable.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

as title, add more data type for kafka sink and avoid unimplemented panic

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

pending #6718
resolve #6759

### CODE REVIEW

**Comment by fuyufjh** [comment]
#6759

File: src/connector/src/sink/kafka.rs [hunk 1]
```diff
@@ -344,8 +345,20 @@ fn datum_to_json_object(field: &Field, datum: DatumRef<'_>) -> ArrayResult<Value
...
+            json!(v.to_text())
+        }
+        (DataType::Time, ScalarRefImpl::NaiveTime(v)) => {
+            json!(v.to_text())
+        }
+        (DataType::TIMESTAMP, ScalarRefImpl::NaiveDateTime(v)) => {
+            json!(v.to_text())
+        }
+        (DataType::TIMESTAMPZ, ScalarRefImpl::Int64(v)) => {
+            json!(v)
```
Comment (xiangjinwu) [inline src/connector/src/sink/kafka.rs:358]: * If an output like `"v1": "2022-12-01 12:00:00+00:00",` is preferred, use the new `v.to_text_with_type`.
  * Given all 5 chrono types are using string, it can be shorten to a single match arm `(DataType::Date | DataType::Time | ..., _) => json!(v.to_text_with_type(data_type))`
* If an output like `"v1": 1669896000000000` is preferred, keep `v` as it is right now. Note this is in microseconds.

**Review by waruto210 — APPROVED** [review]
lgtm.
