### PR TITLE
fix: avoid panic when remove collect rx after reset

### LINKED ISSUE #6860: bug(recovery): panic due to barrier collect complete receiver not found
### Describe the bug

The collect barrier operation is done in an asynchronous handler:
```rust
                let _ = tokio::spawn(Self::collect_barrier(
                    node_need_collect,
                    self.env.stream_client_pool_ref(),
                    command_context,
                    barrier_complete_tx,
                ));
```
When CN receives collect_barrier request after reset actors in recovery, CN will panic.

### To Reproduce

_No response_

### Expected behavior

CN should return error rather than panic.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title, to fix panic of `barrier collect complete receiver` in my local deterministic recovery test. Since it's still possible that CN receives `collect_barrier` request after reset actors in recovery, we should return error rather than panic.

```rust
// todo: the collect handler should be abort when recovery.
let _ = tokio::spawn(Self::collect_barrier(
                    node_need_collect,
                    self.env.stream_client_pool_ref(),
                    command_context,
                    barrier_complete_tx,
                ));
```
After that, we still need to make `collect_barrier` abortable, because collect failure after reset can lead to unnecessary recovery.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Fix #6860

### CODE REVIEW

File: src/stream/src/task/barrier_manager.rs [hunk 1]
```diff
@@ -184,14 +185,15 @@ impl LocalBarrierManager {
     }
 
     /// Use `prev_epoch` to remove collect rx and return rx.
-    pub fn remove_collect_rx(&mut self, prev_epoch: u64) -> CompleteReceiver {
+    pub fn remove_collect_rx(&mut self, prev_epoch: u64) -> StreamResult<CompleteReceiver> {
         self.collect_complete_receiver
             .remove(&prev_epoch)
-            .unwrap_or_else(|| {
-                panic!(
+            .ok_or_else(|| {
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager.rs:191]: How about adding some comments (or simply link to this PR/issue) for why it's possible to fail here?
