### PR TITLE
fix(stream/materialize): incorrect implementation in ignore-conflict behavior

### LINKED ISSUE #14347: Materialize with "ignore" behavior introduce incorrect data
### Describe the bug

When executing an insert-after-delete case, the implementation is wrong. It forgot to delete the value in the cache.

The input stream:

```
+ 1 3
- 1 3
+ 1 6
```

The table data:

```
1 -> 3
```

A key can never been updated in this mode.

### Error message/log

_No response_

### To Reproduce

The testcase was added in #14345, and I'll fix the bug in that PR.

### Expected behavior

```
1 -> 6
```

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

v1.5.4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TennyZhuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #14347 

1. We still need to store the value in cache when the stream is retractable even if we use the ignore behavior.
2. We need to update cache value to None when deleting a row.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/stream/src/executor/mview/materialize.rs [hunk 1]
```diff
@@ -500,28 +485,30 @@ impl<SD: ValueRowSerde> MaterializeCache<SD> {
...
                             update_cache = true;
                         }
-                        ConflictBehavior::IgnoreConflict => (),
+                        ConflictBehavior::IgnoreConflict => {
+                            match self.force_get(&key) {
+                                Some(old_row) => {
+                                    if old_row.row == value {
+                                        fixed_changes.delete(key.clone(), old_row.row.clone());
+                                        update_cache = true;
+                                    }
```
Comment (st1page) [inline src/stream/src/executor/mview/materialize.rs:502]: Not sure the expected behavior when the old value is not consitent, need think when we use the Ignore behavior

**Review by st1page — APPROVED** [review]

**Review by wcy-fdu — APPROVED** [review]
