### PR TITLE
fix(udf): make field name case-insensitive in Rust UDF

### LINKED ISSUE #16095: bug(udf): function not found when field name contains uppercases
### Describe the bug

When creating a Rust UDF which returns a struct type with uppercases in its field name, the field name must be all lowercases in Rust code, otherwise it will fail with an error saying that function is not found. (see To Reproduce for details)

The reason is that SQL identifier is case-insensitive and is converted to lowercase. However, the function signature in `arrow-udf` is case sensitive (because field name is case sensitive in arrow). To fix this problem, we should lookup function signature case-insensitively.

### Error message/log

_No response_

### To Reproduce

```sql
dev=> create function key_value(varchar) returns struct<KEY varchar, VALUE varchar> language rust as $$
    #[derive(StructType)]
    struct KeyValue<'a> {
        KEY: &'a str,
        VALUE: &'a str,
    }
    #[function("key_value(varchar) -> struct KeyValue")]
    fn key_value(kv: &str) -> Option<KeyValue<'_>> {
        let (KEY, VALUE) = kv.split_once('=')?;
        Some(KeyValue { KEY, VALUE })
    }
$$;
ERROR:  Failed to run the query

Caused by:
  Invalid Parameter Value: function not found in wasm binary: "key_value(varchar)->struct<key:varchar,value:varchar>"
HINT: available functions:
  key_value(varchar)->struct KeyValue
```

Using lowercases in Rust code is okay:

```sql
dev=> create function key_value(varchar) returns struct<KEY varchar, VALUE varchar> language rust as $$
    #[derive(StructType)]
    struct KeyValue<'a> {
        key: &'a str,
        value: &'a str,
    }
    #[function("key_value(varchar) -> struct KeyValue")]
    fn key_value(kv: &str) -> Option<KeyValue<'_>> {
        let (key, value) = kv.split_once('=')?;
        Some(KeyValue { key, value })
    }
$$;
CREATE_FUNCTION
```

### Expected behavior

Creating function should succeed.

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

Current main branch. 137bab2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #16095 

I also fixed a bug where Rust table functions with multiple return columns could not be built. But the fix is entirely done in arrow-udf https://github.com/risingwavelabs/arrow-udf/commit/d134e73767956e015a7206e0902c8e5db742c69b and there is no need to modify risingwave. A new test for this is added in this PR.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/frontend/src/handler/create_function.rs [hunk 1]
```diff
@@ -325,8 +325,34 @@ fn find_wasm_identifier_v2(
...
+            }
+        }
+    };
+    // Function signature in arrow-udf is case sensitive.
+    // However, SQL identifiers are usually case insensitive and stored in lowercase.
+    // So we should convert the signature to lowercase before comparison.
     let identifier = runtime
-        .find_function_by_inlined_signature(inlined_signature)
+        .functions()
+        .find(|f| inline_types(f).to_lowercase() == inlined_signature)
```
Comment (xxchan) [inline src/frontend/src/handler/create_function.rs:355]: `inline_types` is the same as that used inside `find_function_by_inlined_signature`, right?

Therefore, slightly prefer doing this in `arrow-udf-wasm` instead of here (or at least expose `inline_types`). But anyway

**Review by xxchan — APPROVED** [review]

File: src/frontend/src/handler/create_function.rs (hunk 1 above)
Comment (wangrunji0408) [reply src/frontend/src/handler/create_function.rs:355]: Yes. At the beginning I also wanted to do it in `arrow-udf-wasm`. But after a second thought, I found this case-insensitive property is SQL-specific, and the backward compatibility is a demand specific to RisingWave. So I finally moved it to RisingWave.
