### PR TITLE
fix: advance epoch to meet now requirement

### LINKED ISSUE #7241: bug(batch): `select now()` is incorrect before any materialized view runs
### Describe the bug

We depend on `latest_snapshot_current_epoch` in the `HummockSnapshotManager`. Unfortunately, the epoch is only updated when an MV or table is running.

Possible fix: change meta to advance the snapshot epoch even without MV.

### To Reproduce

run 

```sql
select now()
```

Without any MV or tables.

It does not update.

### Expected behavior

show updated time.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Advance epoch to meet now requirement.

## Checklist

~- [ ] I have written necessary rustdoc comments~
~- [ ] I have added necessary unit tests and integration tests~
~- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
#7161 
Fix #7241

### CODE REVIEW

File: src/meta/src/barrier/mod.rs [hunk 1]
```diff
@@ -621,6 +615,20 @@ where
                 .await
                 .unwrap();
 
+            // When there's no actors exist in the cluster, we don't need to send the barrier. This
```
Comment (jon-chuang) [inline src/meta/src/barrier/mod.rs:618]: update comment?

**Review by soundOfDestiny — APPROVED** [review]
lgtm, but what if we have actors but they are all idle?

**Comment by yezizp2012** [comment]
> lgtm, but what if we have actors but they are all idle?

The actors state does not affect the flow of the barrier, barrier will still be injected and collected as normal even the actors are all idle.

File: src/meta/src/barrier/mod.rs [hunk 2]
```diff
@@ -600,13 +600,7 @@ where
             let info = self
                 .resolve_actor_info(&mut checkpoint_control, &command)
                 .await;
-            // When there's no actors exist in the cluster, we don't need to send the barrier. This
-            // is an advance optimization. Besides if another barrier comes immediately,
-            // it may send a same epoch and fail the epoch check.
-            if info.nothing_to_do() {
```
Comment (yezizp2012) [inline src/meta/src/barrier/mod.rs:606]: Since this is already filtered in `inject_barrier` and `collect_barrier`, this optimization is no longer needed. After that we can advance epochs in order based on the barrier complete channel, simply advance epochs here will break the epoch updating orders. This is the reason why the previous ci failed: https://buildkite.com/risingwavelabs/pull-request/builds/15220#0185864f-496d-461b-98aa-f23dc01191a2

Comment (BugenZhao) [reply src/meta/src/barrier/mod.rs:606]: +1
