### PR TITLE
 fix(stream): read exactly a single row if no snapshot read on barrier

### LINKED ISSUE #14077: snapshot read: Read 1 record exactly rather than 1 chunk at least per barrier
> However, yesterday we suddenly realized this will cause problems: it forces every barrier must have more than 256 rows, which could cause barrier pile-up in some bad cases (such as when there is huge amplification in downstream MV)

For each barrier, we currently enforce to read 1 chunk at least. That could have issues when there's huge amplification.
So we enforce to read 1 row exactly instead, if no rows read before we recieved the barrier.

credit: @fuyufjh and @st1page

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Closes #14077 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by kwannoel** [comment]
As per @fuyufjh's comments , moved the logic from iter chunks to within `no_shuffle_backfill`. Conceptually the same as https://github.com/risingwavelabs/risingwave/pull/14146, only difference is in implementation.

File: src/stream/src/executor/backfill/no_shuffle_backfill.rs [hunk 1]
```diff
@@ -299,20 +310,27 @@ where
...
+                                        if let Some(data_chunk) = builder.append_one_row(record) {
+                                            let ops = vec![Op::Insert; data_chunk.capacity()];
+                                            let chunk = StreamChunk::from_parts(ops, data_chunk);
+                                            // Raise the current position.
+                                            // As snapshot read streams are ordered by pk, so we can
+                                            // just use the last row to update `current_pos`.
+                                            current_pos =
+                                                Some(get_new_pos(&chunk, &pk_in_output_indices));
+
+                                            let chunk_cardinality = chunk.cardinality() as u64;
```
Comment (fuyufjh) [inline src/stream/src/executor/backfill/no_shuffle_backfill.rs:324]: Not a big deal but the indent is a bit too deep. Perhaps we can try to split the `execute_inner` function later.

**Review by fuyufjh — COMMENTED** [review]
LGTM for the rest

File: src/tests/simulation/tests/integration_tests/backfill_tests.rs [hunk 2]
```diff
@@ -190,6 +190,44 @@ async fn test_arrangement_backfill_replication() -> Result<()> {
...
+            .unwrap();
+    })
+    .await?;
+    let mut session = cluster.start_session();
+    session.run("FLUSH").await?;
+    // Run flush to check if barrier can go through. It should be able to.
+    // There will be some latency for the initial barrier.
+    session.run("FLUSH;").await?;
+    // But after that flush should be processed timely.
+    session.run("FLUSH;").await?;
```
[the remark this answers is not in the document]
Comment (kwannoel) [reply src/tests/simulation/tests/integration_tests/backfill_tests.rs]: I have added a timeout. Note that the join here is cpu bound, so it may take a long time in real-world, but in madsim, we don't tick the clock unless there's IO. So it may not timeout.

Regardless, if the test runtime of this test spikes, it should trigger CI timeout.

Alternatively we can run it on a non-sim environment, e.g. via `run-backfill-tests.sh` in the future.

File: src/stream/src/executor/backfill/no_shuffle_backfill.rs [hunk 3]
```diff
@@ -675,6 +675,33 @@ where
...
+        // As snapshot read streams are ordered by pk, so we can
+        // just use the last row to update `current_pos`.
+        *current_pos = Some(get_new_pos(&chunk, pk_indices));
+
+        let chunk_cardinality = chunk.cardinality() as u64;
+        *cur_barrier_snapshot_processed_rows += chunk_cardinality;
+        *total_snapshot_processed_rows += chunk_cardinality;
+
+        Message::Chunk(mapping_chunk(chunk, output_indices))
+    }
```
Comment (kwannoel) [inline src/stream/src/executor/backfill/no_shuffle_backfill.rs:704]: Refactored the logic out

File: src/stream/src/executor/backfill/no_shuffle_backfill.rs (hunk 1 above)
Comment (kwannoel) [reply src/stream/src/executor/backfill/no_shuffle_backfill.rs]: https://github.com/risingwavelabs/risingwave/pull/14544/files#r1454375129

**Review by fuyufjh — APPROVED** [review]

File: src/tests/simulation/tests/integration_tests/backfill_tests.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (fuyufjh) [reply src/tests/simulation/tests/integration_tests/backfill_tests.rs]: Indeed. I forgot it runs in madsim. Also not sure what's the clock's behavior in mad-sim.

[the remark this answers is not in the document]
Comment (kwannoel) [reply src/tests/simulation/tests/integration_tests/backfill_tests.rs]: > but in madsim, we don't tick the clock unless there's IO. So it may not timeout.

**Comment by kwannoel** [comment]
PTAL cc @chenzl25

File: src/tests/simulation/tests/integration_tests/backfill_tests.rs [hunk 4]
```diff
@@ -190,6 +191,44 @@ async fn test_arrangement_backfill_replication() -> Result<()> {
...
+    let mut cluster = Cluster::start(Configuration::default()).await?;
+    let mut session = cluster.start_session();
+
+    // Create dimension table
+    session.run("CREATE TABLE dim (v1 int);").await?;
+    // Ingest
+    // Amplification of 1000 records
+    session
+        .run("INSERT INTO dim SELECT 1 FROM generate_series(1, 200);")
+        .await?;
```
Comment (chenzl25) [inline src/tests/simulation/tests/integration_tests/backfill_tests.rs:205]: 1000 or 200?

**Review by chenzl25 — APPROVED** [review]
Sending exactly one row to the downstream LGTM.

File: src/tests/simulation/tests/integration_tests/backfill_tests.rs (hunk 4 above)
Comment (kwannoel) [reply src/tests/simulation/tests/integration_tests/backfill_tests.rs:205]: 200, updating the docstring.

File: src/tests/simulation/tests/integration_tests/backfill_tests.rs [hunk 5]
```diff
@@ -190,6 +191,44 @@ async fn test_arrangement_backfill_replication() -> Result<()> {
...
 
+#[tokio::test]
+async fn test_backfill_backpressure() -> Result<()> {
+    let mut cluster = Cluster::start(Configuration::default()).await?;
+    let mut session = cluster.start_session();
+
+    // Create dimension table
+    session.run("CREATE TABLE dim (v1 int);").await?;
+    // Ingest
+    // Amplification of 1000 records
```
Comment (kwannoel) [inline src/tests/simulation/tests/integration_tests/backfill_tests.rs:202]:
```suggestion
    // Amplification of 200 records
```
