### PR TITLE
fix(streaming): correctly skip problematic table-function input

### LINKED ISSUE #19352: bug: streaming table function result missing if other input rows lead to error
Since https://github.com/risingwavelabs/risingwave/pull/17156, we should be able to tolerate table function error in streaming mode. However, the implementation seems incorrect: a problematic input can cause the results of other input rows to be missing, if they are in the same chunk.

To reproduce:

```sql
-- ensure the same chunk
set streaming_parallelism to 1;

create table t (x int);
create materialized view mv as select x, generate_series(1, 2, x) from t;

insert into t values (0), (1);
flush;

select * from mv;
-- got empty result, expected (x = 1) to be successfully executed
```

Revealed by https://github.com/risingwavelabs/risingwave/pull/19250

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

See #19352. Close #19352.

----

The behavior for table function returning an error in streaming mode will become:

https://github.com/risingwavelabs/risingwave/blob/c6d2ba881c59cd04b3940f163f4ec5f2339d23b0/src/stream/src/executor/project_set.rs#L205-L213

As described in #17156, there's currently a limitation that

> If some rows have been output when the error occurs, these rows will not be reverted.

which behaves kind of strangely. Since it might be uncommon (?) for a table function to fail halfway, I prefer not to document this behavior.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
* **#19250** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#19353** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19353?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BugenZhao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/stream/src/executor/project_set.rs [hunk 1]
```diff
@@ -174,22 +184,33 @@ impl Inner {
                                 unsafe { std::mem::transmute(row.as_mut_slice()) };
 
                             row[0] = Some(projected_row_id.into());
-                            // if any of the set columns has a value
-                            let mut valid = false;
+
+                            // Whether all table functions has exhausted or has failed for current input row.
+                            let mut fully_consumed = true;
```
Comment (stdrc) [inline src/stream/src/executor/project_set.rs:189]: In which case it's considered as "exhausted"?

Comment (BugenZhao) [reply src/stream/src/executor/project_set.rs:189]: When this condition doesn't meet:

```rust
if let Some((i, result)) = state.peek()
  && is_current_input(i)
```

i.e., the cursor of the `state` has moved to the next input.

**Review by stdrc — APPROVED** [review]
