### PR TITLE
fix: casting Varchar to multidimensional List

### LINKED ISSUE #4887: bug: casting to multidimensional list results in panic
### Describe the bug

Casting from `Varchar` to for example `integer[][]` panics when length of inner array is larger than one. 

This breaks:
`'{{1, 2}, {3, 4}}'::integer[][]`

This does not break:
`'{{1}, {3}}'::integer[][]`

Apart from that there should not be any panic at all. Instead when trying to cast an invalid `Varchar` to a list, an error message should be returned gracefully. 

### To Reproduce

```
dev=> select * from (values ('{{1, 2}, {3, 4}}'::integer[][])) as t(arr);
ERROR:  QueryError: Expr error: Internal(Last character should be right brace '}'

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.62/src/error.rs:81:36
...
```

### Expected behavior

For valid input:
```
dev=> select * from  (values ('{{1, 2}, {3, 4}}'::integer[][])) as t(arr);
    arr     
------------
 {{1, 2}, {3, 4}}
```

For invalid input:
```
dev=> select * from  (values ('{{1}, {invalid input}}')) as t(arr);
ERROR:  QueryError: Expr error: InvalidCast(Invalid input syntax for type integer)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nanderstabel**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR implements casting from Varchar input to any (multi-dimensional) List.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- New `fn unnest()` function splits input string into 1 or more items e.g.:
`assert_eq!(unnest("{{1, 2, 3}, {4, 5, 6}}"), vec!["{1, 2, 3}".to_string(), "{4, 5, 6}".to_string()]));`
`assert_eq!(unnest("{1, 2, 3}"), vec!["1".to_string(), "2".to_string(), "3".to_string()]));`
- These splits can then be parsed accordingly.
- This is an MVP implementation. This solution might not catch some edge-cases. Also escape `'\'` character is not implemented.
- Checkout `# Test multiple castings of the same input` in `array.slt.part` for showcase of implementation.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
fixes #4887

### CODE REVIEW

File: src/expr/src/vector_op/cast.rs [hunk 1]
```diff
@@ -314,38 +314,72 @@ macro_rules! for_each_cast {
     };
 }
 
-#[inline(always)]
-pub fn str_to_list(input: &str, target_elem_type: &DataType) -> Result<ListValue> {
+// TODO(nanderstabel): optimize for multidimensional List. Depth can be given as a parameter to this
```
Comment (neverchanje) [inline src/expr/src/vector_op/cast.rs:317]: indeed.

**Review by neverchanje — APPROVED** [review]
