### PR TITLE
fix(expr): `array_to_string` should handle multidimensional array recursively

### LINKED ISSUE #8680: array_to_string gives extra parenthesis when double arrays are passed
### Describe the bug

On passing double arrays in `array_to_string` we get extra parenthesis in result. It was implemented in #8027
```
dev=> select array_to_string(array[array['one', 'two'], array['three', 'four']]::text[][], ',');
    array_to_string     
------------------------
 {one,two},{three,four}
(1 row)

```

### To Reproduce

Simply Run
`select array_to_string(array[array['one', 'two'], array['three', 'four']]::text[][], ',');
`

### Expected behavior

We should get

```
  array_to_string   
--------------------
 one,two,three,four
(1 row)

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #8680. See https://github.com/risingwavelabs/risingwave/issues/3811#issuecomment-1556656529 for rationale.

This is consistent with `unnest` and `cardinality` (and `array_replace` in the future).

Note the following (with `::text[]` rather than `::text[][]`) is still different from PostgreSQL:
```
select array_to_string(array[array['one', 'two'], array['three', 'four']]::text[], ',');
```
This is not related to the `array_to_string` function. In PostgreSQL, `::text[]` still returns a 2d array with 4 elements, while we return a 1d array with 2 elements, first of which is a result of `array['one', 'two']::text`. This is intentional.

We do not guarantee backward compatibility of experimental multidimensional array.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/expr/src/expr/expr_array_to_string.rs [hunk 1]
```diff
@@ -100,7 +111,8 @@ fn array_to_string(
     mut writer: &mut dyn Write,
 ) {
     let mut first = true;
-    for element in array.iter().flatten() {
+    for element in array.flatten() {
+        let Some(element) = element else { continue };
```
Comment (xiangjinwu) [inline src/expr/src/expr/expr_array_to_string.rs:115]: The old `.iter().flatten()` means to iter 1 layer, then remove nulls.

The new `.flatten()` means to flatten (unnest) recursively. Nulls are removed via let-else.

The 2 `flatten` are completely different, one on `Iterator<Item=Option<T>>` while the other on `ListRef`

**Review by st1page — APPROVED** [review]
LGTM

**Comment by st1page** [comment]
So have we decided to be compatible with PG's behavior for those function with the same name?

**Comment by xiangjinwu** [comment]
> So have we decided to be compatible with PG's behavior for those function with the same name?

Yes. To elaborate:
* It is okay for a query to work in PG but report an error in RW. This is an unsupported feature that may be supported later.
* It is also okay for a query to report an error in PG but work in RW. This is an extension.
* It is better avoided that the same query output different results **silently** in PG and RW. This is the issue being fixed here.
