### PR TITLE
fix: fix catalog inconsistency when dropping stream jobs.

### LINKED ISSUE #20953: panic on `row not found` in backfill during `drop sink`
### Buildkite URL

https://buildkite.com/risingwavelabs/pull-request/builds/70391#0195a81b-2f51-4204-8e83-e8d45d256a29

### Description and Insights

e2e, ci-3streaming-2serving-3fe, streaming
```

e2e_test/backfill/sink/different_pk_and_dist_key.slt         .. [FAILED]

failed to run `e2e_test/backfill/sink/different_pk_and_dist_key.slt`

Caused by:
    statement failed: db error: ERROR: Failed to run the query

    Caused by these errors (recent errors listed first):
      1: gRPC request to meta service failed: Unknown error
      2: transport error
      3: connection error
      4: connection reset

    [SQL] drop sink s1;
    at e2e_test/backfill/sink/different_pk_and_dist_key.slt:39
```

And the compute node 5687 & 5688 logs contain:
```
2025-03-18T07:26:38.750739678Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 501 }, it may be removed by meta-service
2025-03-18T07:26:38.750779107Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 504 }, it may be removed by meta-service
2025-03-18T07:26:38.750791644Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 504 }, it may be removed by meta-service
2025-03-18T07:26:38.750800904Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 501 }, it may be removed by meta-service
2025-03-18T07:26:38.750809556Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 504 }, it may be removed by meta-service
2025-03-18T07:26:38.750817509Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 501 }, it may be removed by meta-service
2025-03-18T07:26:38.750826129Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 501 }, it may be removed by meta-service
2025-03-18T07:26:38.750835386Z ERROR risingwave_storage::hummock::compactor::shared_buffer_compact: can not find table TableId { table_id: 504 }, it may be removed by meta-service
2025-03-18T07:26:38.768159766Z ERROR risingwave_stream::task::stream_manager: actor exit with error actor_id=3928 error=Executor error: row [
    Some(
        Int16(
            66,
        ),
    ),
] not found

Backtrace:
   0: msg<alloc::string::String>
             at ./.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.86/src/backtrace.rs:27:14
   1: {async_fn#0}<risingwave_storage::monitor::monitored_store::MonitoredStateStore<risingwave_storage::store_impl::dyn_state_store::StateStorePointer<alloc::sync::Arc<dyn risingwave_storage::store_impl::dyn_state_store::DynStateStore, alloc::alloc::Global>>>, false, core::iter::adapters::map::Map<risingwave_common::bitmap::BitmapOnesIter, fn(usize) -> risingwave_common::hash::consistent_hash::vnode::VirtualNode>>
             at ./src/stream/src/executor/backfill/utils.rs:791:25
   2: {coroutine#0}<risingwave_storage::monitor::monitored_store::MonitoredStateStore<risingwave_storage::store_impl::dyn_state_store::StateStorePointer<alloc::sync::Arc<dyn risingwave_storage::store_impl::dyn_state_store::DynStateStore, alloc::alloc::Global>>>, risingwave_common::util::value_encoding::column_aware_row_encoding::ColumnAwareSerde>
             at ./src/stream/src/executor/backfill/arrangement_backfill.rs:485:18
```

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

This PR addresses one corner case that may have lead to #20953.
The issue occurs when catalog client retrieves catalog from meta node, while the result doesn't include the table that is being dropped, as explained [here](https://github.com/risingwavelabs/risingwave/issues/20953#issuecomment-2736262262).

resolve #20953

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  My PR contains critical fixes that are necessary to be merged into the latest release. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/meta/service/src/ddl_service.rs [hunk 1]
```diff
@@ -882,6 +882,7 @@ impl DdlService for DdlServiceImpl {
                     .into_iter()
                     .map(|id| id as _)
                     .collect(),
+                true,
```
Comment (wenym1) [inline src/meta/service/src/ddl_service.rs:885]: Shall we also include the parameter `include_dropped_table` in `GetTableRequest` to make this rpc call more general?

**Review by wenym1 — APPROVED** [review]
Rest LGTM

**Review by Li0k — APPROVED** [review]
LGTM
