### PR TITLE
fix(cdc): commit offset to upstream after checkpoint has commit

### LINKED ISSUE #15464: feat: checkpoint commit callback (for cdc-connector)
### Some background go first

Our cdc connector consumes PG cdc events while acking to the PG server at regular intervals the offset (lsn) that has been consumed. Then upstream PG will assume that wal log of those offsets can be discarded.
https://github.com/risingwavelabs/risingwave/blob/e6d8d88bcef5a388a0a7a0669d9418d25194f138/java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEventConsumer.java#L189-L199

DebeziumEngine will commit those marked offsets to upstream:
https://github.com/debezium/debezium/blob/4ca2a67b0d302c611b89b1931728377cf232ab6c/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java#L435-L436

### Findings 
After some investigation, I think the reason for the "_Cannot seek to the last known offset_" error is that **we ack the offset to PG before the checkpoint commit**. So that when the cluster recovered from a committed checkpoint, the restored offset may already been discarded by upstream PG.

Currently our framework doesn't have a [checkpoint commit callback](https://github.com/apache/flink/blob/cf5bb80b5fd965928ff75d415dd93e0b12fa1b49/flink-core/src/main/java/org/apache/flink/api/common/state/CheckpointListener.java#L98) mechanism to notify the source executor. An intuitive idea is to let Meta make a broadcast RPCs to each CNs in the cluster. cc @hzxa21 

To confirm the findings, I increase the offset flush interval to 30mins which is much large than the time required for the test and rerun the chaos test (stresschaos only and w/o memtable spill: [599](https://buildkite.com/risingwave-test/chaos-mesh/builds/599), [603](https://buildkite.com/risingwave-test/chaos-mesh/builds/603) ), the results show that the "Cannot seek" error is gone and btw mv check is passed.

But! when I run chaos test with 3CNs ([601](https://buildkite.com/risingwave-test/chaos-mesh/builds/601)) , even the error is gone, the source table is still unsynced with PG, I have no idea of this one right now.

_Originally posted by @StrikeW in https://github.com/risingwavelabs/risingwave/issues/15141#issuecomment-1959605692_

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
resolve #15464  
- Add `WaitEpochWorker` in source executor to wait the commit of an epoch for some cdc connectors 
- Add `JniDbzSourceRegistry` to allow source executor can get the source handler
- Add `get_encoded_offset()` to `SplitMetaData` to get offset from a split

related: #15312

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/stream/src/executor/source/source_executor.rs [hunk 1]
```diff
@@ -610,6 +653,58 @@ impl<S: StateStore> Debug for SourceExecutor<S> {
...
+impl<S: StateStore> WaitEpochWoker<S> {
+    pub async fn run(mut self) {
+        tracing::debug!("wait epoch worker start success");
+        loop {
+            // poll the rx and wait for the epoch commit
+            match self.wait_epoch_rx.recv().await {
+                Some((epoch, updated_offsets)) => {
+                    let state_store_guard = self.state_table_handler.lock().await;
+                    tracing::debug!("start to wait epoch {}", epoch.0);
+                    let ret = state_store_guard.state_store.wait_epoch(epoch.0).await;
```
Comment (StrikeW) [inline src/stream/src/executor/source/source_executor.rs:670]: What strange is the wait epoch cannot success.
```
2024-04-07T23:14:40.312592+08:00 DEBUG actor{otel.name="Actor 1" actor_id=1 prev_epoch=6243462565134336 curr_epoch=6243462630735872}:executor{otel.name="Source 100002712"}: risingwave_stream::executor::source::source_executor: epoch to wait EpochPair { curr: 6243462696337408, prev: 6243462630735872 }
2024-04-07T23:14:40.314398+08:00 DEBUG risingwave_stream::executor::source::source_executor: start to wait epoch 6243462696337408
2024-04-07T23:15:10.335995+08:00  WARN risingwave_storage::hummock::utils: wait_epoch timeout when waiting for version update epoch=6243462696337408
2024-04-07T23:15:40.339846+08:00  WARN risingwave_storage::hummock::utils: wait_epoch timeout when waiting for version update epoch=6243462696337408
```
Do you have any idea? @hzxa21

File: src/stream/src/common/table/state_table.rs [hunk 2]
```diff
@@ -212,6 +212,11 @@ where
             .expect("non-replicated state store should start immediately.")
             .expect("non-replicated state store should not wait_for_epoch, and fail because of it.")
     }
+
+    /// Wait until the epoch is committed and its data is ready to read.
+    pub async fn wait_epoch(&self, epoch: u64) -> StorageResult<()> {
```
Comment (wenym1) [inline src/stream/src/common/table/state_table.rs:217]: Actually no need to add `wait_epoch` on `LocalStateStore`. We can just store the original `StateStore` in the `StateTable` and then call the `try_wait_epoch` of `StateStore`.

File: src/stream/src/executor/source/source_executor.rs (hunk 1 above)
Comment (BugenZhao) [inline src/stream/src/executor/source/source_executor.rs:670]: The calling of `wait_epoch` resides in the critical section of the lock over `state_store_handler`. This looks unnecessary to me and could lead to deadlocks.

File: src/stream/src/executor/source/source_executor.rs [hunk 3]
```diff
@@ -610,6 +653,58 @@ impl<S: StateStore> Debug for SourceExecutor<S> {
...
+                    drop(state_store_guard);
+
+                    match ret {
+                        Ok(()) => {
+                            tracing::debug!(epoch = epoch.0, "wait epoch success");
+                            // cdc source only has one split
+                            assert_eq!(1, updated_offsets.len());
+                            let (split_id, offset) = updated_offsets.into_iter().next().unwrap();
+                            let source_id: u64 = u64::from_str(split_id.as_ref()).unwrap();
```
Comment (BugenZhao) [inline src/stream/src/executor/source/source_executor.rs:679]: Why `source_id` is from `split_id`?

File: src/stream/src/executor/source/source_executor.rs [hunk 4]
```diff
@@ -610,6 +653,58 @@ impl<S: StateStore> Debug for SourceExecutor<S> {
...
+                            // notify cdc connector to commit offset
+                            match jni_source::commit_cdc_offset(source_id, offset.clone()) {
+                                Ok(_) => {}
+                                Err(e) => {
+                                    tracing::error!(
+                                        error = ?e.as_report(),
```
Comment (BugenZhao) [inline src/stream/src/executor/source/source_executor.rs:685]:
```suggestion
                                        error = %e.as_report(),
```

`?` will include the backtrace. I'm afraid this is not expected here. Same for other occurrences.

File: src/stream/src/executor/source/executor_core.rs [hunk 5]
```diff
@@ -38,7 +41,7 @@ pub struct StreamSourceCore<S: StateStore> {
     pub(crate) latest_split_info: HashMap<SplitId, SplitImpl>,
 
     /// Stores information of the splits.
-    pub(crate) split_state_store: SourceStateTableHandler<S>,
+    pub(crate) split_state_store: Arc<Mutex<SourceStateTableHandler<S>>>,
```
Comment (BugenZhao) [inline src/stream/src/executor/source/executor_core.rs:44]: Can we avoid introducing the lock? IMO we only need the `wait_epoch` call on the state store, without touching the internal fields of local states.

File: src/stream/src/executor/source/source_executor.rs [hunk 6]
```diff
@@ -610,6 +653,58 @@ impl<S: StateStore> Debug for SourceExecutor<S> {
     }
 }
 
+struct WaitEpochWoker<S: StateStore> {
```
Comment (BugenZhao) [inline src/stream/src/executor/source/source_executor.rs:656]:
```suggestion
struct WaitEpochWorker<S: StateStore> {
```

File: src/stream/src/executor/source/executor_core.rs (hunk 5 above)
Comment (StrikeW) [reply src/stream/src/executor/source/executor_core.rs:44]: The problem is we need to share the `SourceStateTableHandler<S>` between source executor and the worker. Although the worker only require share access, the source executor need mutable access. One improvement is to move the lock into the struct:
```
pub struct SourceStateTableHandler<S: StateStore> {
    pub state_store: Arc<Mutex<StateTable<S>>>,
}
```
WDUT?

Comment (BugenZhao) [reply src/stream/src/executor/source/executor_core.rs:44]: Can we directly call `wait_epoch` on the `StateStore`? It seems to be clonable.

Comment (StrikeW) [reply src/stream/src/executor/source/executor_core.rs:44]: It seems not. It requires the  `<S as risingwave_storage::StateStore>::Local` to be cloneable.
```
error[E0599]: the method `clone` exists for struct `StateTableInner<S, BasicSerde, false, WatermarkBufferByEpoch<300>>`, but its trait bounds were not satisfied
   --> src/stream/src/executor/source/source_executor.rs:91:61
    |
91  |               state_table: core.split_state_store.state_store.clone(),
    |                                                               ^^^^^ method cannot be called due to unsatisfied trait bounds
    |
   ::: src/stream/src/common/table/state_table.rs:96:1
    |
96  | / pub struct StateTableInner<
97  | |     S,
98  | |     SD = BasicSerde,
99  | |     const IS_REPLICATED: bool = false,
100 | |     W = DefaultWatermarkBufferStrategy,
101 | |     const USE_WATERMARK_CACHE: bool = false,
102 | | > where
    | | -
    | | |
    | |_method `clone` not found for this struct
    |   doesn't satisfy `_: Clone`
    |
note: trait bound `<S as risingwave_storage::StateStore>::Local: Clone` was not satisfied
   --> src/stream/src/common/table/state_table.rs:95:10
    |
95  | #[derive(Clone)]
    |          ^^^^^ unsatisfied trait bound introduced in this `derive` macro
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `clone`, perhaps you need to implement it:
            candidate #1: `Clone`
```

File: src/stream/src/executor/source/source_executor.rs (hunk 3 above)
Comment (StrikeW) [reply src/stream/src/executor/source/source_executor.rs:677]: `WaitEpochWorker` only started for cdc sources, which is singleton and we use `source_id` to represent the split id.

File: src/stream/src/executor/source/source_executor.rs (hunk 4 above)
Comment (StrikeW) [reply src/stream/src/executor/source/source_executor.rs]: fixed

File: src/connector/src/source/base.rs [hunk 7]
```diff
@@ -560,6 +564,8 @@ pub trait SplitMetaData: Sized {
     fn encode_to_json(&self) -> JsonbVal;
     fn restore_from_json(value: JsonbVal) -> Result<Self>;
     fn update_with_offset(&mut self, start_offset: String) -> crate::error::ConnectorResult<()>;
+
+    fn get_encoded_offset(&self) -> String;
```
Comment (BugenZhao) [inline src/connector/src/source/base.rs:568]: Would you mind adding some docs to the interfaces in this trait? For example, what's the difference (behavior and usage) between `encode_to_json` and `encoded_offset`?

File: src/connector/src/source/kinesis/split.rs [hunk 8]
```diff
@@ -57,6 +57,10 @@ impl SplitMetaData for KinesisSplit {
         self.start_position = start_offset;
         Ok(())
     }
+
+    fn get_encoded_offset(&self) -> String {
+        todo!()
```
Comment (BugenZhao) [inline src/connector/src/source/kinesis/split.rs:62]: Is this okay?

File: src/connector/src/source/iceberg/mod.rs [hunk 9]
```diff
@@ -129,6 +129,10 @@ impl SplitMetaData for IcebergSplit {
     fn update_with_offset(&mut self, _start_offset: String) -> ConnectorResult<()> {
         unimplemented!()
     }
+
+    fn get_encoded_offset(&self) -> String {
+        unimplemented!()
```
Comment (BugenZhao) [inline src/connector/src/source/iceberg/mod.rs:134]: Is this okay?

File: src/stream/src/common/table/watermark.rs [hunk 10]
```diff
@@ -36,6 +36,12 @@ impl WatermarkBufferStrategy for WatermarkNoBuffer {
     }
 }
 
+impl Clone for WatermarkNoBuffer {
```
Comment (BugenZhao) [inline src/stream/src/common/table/watermark.rs:39]: Why don't we `derive(Clone)` for it?

File: src/stream/src/common/table/watermark.rs [hunk 11]
```diff
@@ -58,3 +64,11 @@ impl<const PERIOD: usize> WatermarkBufferStrategy for WatermarkBufferByEpoch<PER
         }
     }
 }
+
+impl<const PERIOD: usize> Clone for WatermarkBufferByEpoch<PERIOD> {
```
Comment (BugenZhao) [inline src/stream/src/common/table/watermark.rs:68]: ditto

File: src/stream/src/common/table/state_table.rs [hunk 12]
```diff
@@ -212,6 +213,17 @@ where
             .expect("non-replicated state store should start immediately.")
             .expect("non-replicated state store should not wait_for_epoch, and fail because of it.")
     }
+
+    pub fn state_store(&self) -> &S {
+        &self.store
+    }
+
+    /// Wait until the epoch is committed and its data is ready to read.
+    pub async fn wait_epoch(&self, epoch: u64) -> StorageResult<()> {
```
Comment (BugenZhao) [inline src/stream/src/common/table/state_table.rs:222]: Is this method still used?

File: src/connector/src/source/kinesis/split.rs (hunk 8 above)
Comment (StrikeW) [reply src/connector/src/source/kinesis/split.rs]: fixed

File: src/connector/src/source/iceberg/mod.rs (hunk 9 above)
Comment (StrikeW) [reply src/connector/src/source/iceberg/mod.rs:134]: modify to `unreachable()`, since iceberg source cannot be used as stream source.

File: src/stream/src/common/table/state_table.rs (hunk 12 above)
Comment (StrikeW) [reply src/stream/src/common/table/state_table.rs]: removed

File: src/stream/src/common/table/watermark.rs (hunk 10 above)
Comment (StrikeW) [reply src/stream/src/common/table/watermark.rs]: removed, don't need it to be cloneable.

File: src/connector/src/source/base.rs (hunk 7 above)
Comment (StrikeW) [reply src/connector/src/source/base.rs:571]: done

File: src/stream/src/executor/source/source_executor.rs [hunk 13]
```diff
@@ -610,6 +650,59 @@ impl<S: StateStore> Debug for SourceExecutor<S> {
...
+                                Err(e) => {
+                                    tracing::error!(
+                                        error = %e.as_report(),
+                                        "source#{source_id}: failed to commit cdc offset: {offset}.",
+                                    )
+                                }
+                            }
+                        }
+                        Err(e) => {
+                            tracing::error!(
```
Comment (hzxa21) [inline src/stream/src/executor/source/source_executor.rs:690]: At the first glance I thought we may miss `commit_cdc_offset` if we reach here. But I realize that `try_wait_epoch` on committed epoch won't fail unless the node is exiting. We may want to add a commment here for this assumption.

File: src/connector/src/source/reader/reader.rs [hunk 14]
```diff
@@ -105,6 +105,11 @@ impl SourceReader {
         }
     }
 
+    /// Postgres and Oracle connectors need to commit the offset to upstream.
+    pub fn need_commit_offset_to_upstream(&self) -> bool {
+        matches!(&self.config, ConnectorProperties::PostgresCdc(_))
```
Comment (hzxa21) [inline src/connector/src/source/reader/reader.rs:110]: How about mysql? I thought all dbz-based cdc needs to commit offset.

File: src/connector/src/source/base.rs [hunk 15]
```diff
@@ -477,6 +477,10 @@ impl SplitMetaData for SplitImpl {
             inner.update_with_offset(start_offset)
         )
     }
+
+    fn get_encoded_offset(&self) -> String {
```
Comment (hzxa21) [inline src/connector/src/source/base.rs:481]: Given that this method is specific to dbz-based cdc source, I feel that it is confusing to add this method to the `SplitMetaData` trait and let all sources to impl this method. How about checking the type of SplitImpl in `need_commit_offset_to_upstream` and direct gets the cdc offset instead of introducing `get_encoded_offset` in the trait?

File: java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java [hunk 16]
```diff
@@ -211,16 +216,61 @@ var record = event.value();
...
+                new SourceRecord(
+                        offset.sourcePartition,
+                        adjustSourceOffset((Map<String, Object>) offset.sourceOffset),
+                        "DUMMY",
+                        Schema.BOOLEAN_SCHEMA,
+                        true);
+        ChangeEvent<SourceRecord, SourceRecord> changeEvent =
+                EmbeddedEngineChangeEventProxy.create(null, recordWrapper, recordWrapper);
+        currentRecordCommitter.markProcessed(changeEvent);
+        currentRecordCommitter.markBatchFinished();
```
Comment (hzxa21) [inline java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java:252]:
```
/**
     * Contract passed to {@link ChangeConsumer}s, allowing them to commit single records as they have been processed
     * and to signal that offsets may be flushed eventually.
     */
    interface RecordCommitter<R> {

        /**
         * Marks a single record as processed, must be called for each
         * record.
         *
         * @param record the record to commit
         */
        void markProcessed(R record) throws InterruptedException;

        /**
         * Marks a batch as finished, this may result in committing offsets/flushing
         * data.
         * <p>
         * Should be called when a batch of records is finished being processed.
         */
        void markBatchFinished() throws InterruptedException;
```

The contract of `RecordCommitter` states that `markProcessed` must be called for **each** record and `markBatchFinished` should be called when the batch is processed. However, IIUC, in the current implementation, we will only call `markProcessed` per checkpoint. Also, the checkpoint doesn't necessarily align with the dbz batch boundary. Example:
```
dbz batch:
  record 1
  record 2
  record 3

// Prior to this PR
markProcessed(1);
markProcessed(2);
markProcessed(3);
markBatchFinished();

// After this PR, assume checkpoint happens after processing record 2 but before record 3
markProcessed(2);
markBatchFinished();

markProcessed(3);
...
markBatchFinished();

```

Will this be an issue?

**Comment by StrikeW** [comment]
I evaluated the effectiveness of this PR with chaos test, the `Cannot seek to the last known offset` error is gone, which means https://github.com/risingwavelabs/risingwave/issues/15464 can be resolved.
But `ch_benchmark_q4` still encounter inconsistency of the cdc source tables (tracked in https://github.com/risingwavelabs/risingwave/issues/15312). I think we can merge this PR first and continue investigating the cdc table inconsistent issues.

**Comment by hzxa21** [comment]
> I evaluated the effectiveness of this PR with chaos test, the `Cannot seek to the last known offset` error is gone, which means #15464 can be resolved. But `ch_benchmark_q4` still encounter inconsistency of the cdc source tables (tracked in #15312). I think we can merge this PR first and continue investigating the cdc table inconsistent issues.

https://github.com/risingwavelabs/risingwave/issues/15312#issuecomment-2051184315 Can we be sure that the extra rows in RW is not caused by this PR?

**Comment by StrikeW** [comment]
> > I evaluated the effectiveness of this PR with chaos test, the `Cannot seek to the last known offset` error is gone, which means #15464 can be resolved. But `ch_benchmark_q4` still encounter inconsistency of the cdc source tables (tracked in #15312). I think we can merge this PR first and continue investigating the cdc table inconsistent issues.
> 
> [#15312 (comment)](https://github.com/risingwavelabs/risingwave/issues/15312#issuecomment-2051184315) Can we be sure that the extra rows in RW is not caused by this PR?

I also run against the nightly image ([750](https://buildkite.com/risingwave-test/chaos-mesh/builds/750)), the symptom is same: RW rows is more than upstream pg.

File: java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java (hunk 16 above)
Comment (hzxa21) [reply java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzChangeEventConsumer.java:252]: Thanks for the explanation. Indeed the same logic [here](https://github.com/apache/flink-cdc/blob/48ca8623bb8fa405adb56dbe505dbad10902db89/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/internal/DebeziumChangeConsumer.java#L83)

File: src/connector/src/source/reader/reader.rs (hunk 14 above)
Comment (hzxa21) [reply src/connector/src/source/reader/reader.rs:110]: Do you mean that `recordCommitter.markProcessed()` and `recordCommitter.markBatchFinished` are no-ops for other dbz-based cdc source?

File: src/stream/src/executor/source/source_executor.rs (hunk 13 above)
Comment (hzxa21) [reply src/stream/src/executor/source/source_executor.rs:690]: I agree that as long as we don't miss offset commit for a long time, it is not a big deal. However, my point is not about whether we will miss it. My point is that `try_wait_epoch` is not expected to fail in this case. I originally thought we should panic here but logging an error log is more robust. How about just tweaking the message to be "Unexpected failure in try_wait_epoch {}" and adding a comment for this assumption?

File: src/connector/src/source/base.rs [hunk 17]
```diff
@@ -443,6 +444,17 @@ impl SplitImpl {
...
     }
+
+    /// Get the current split offset.
+    pub fn get_cdc_split_offset(&self) -> String {
+        match self {
+            MysqlCdc(split) => split.start_offset().clone().unwrap_or_default(),
+            PostgresCdc(split) => split.start_offset().clone().unwrap_or_default(),
+            MongodbCdc(split) => split.start_offset().clone().unwrap_or_default(),
+            CitusCdc(split) => split.start_offset().clone().unwrap_or_default(),
+            _ => "".to_string(),
```
Comment (hzxa21) [inline src/connector/src/source/base.rs:455]: `unreachable!` instead of empty string?

**Review by hzxa21 — APPROVED** [review]
Rest LGTM!

File: src/connector/src/source/reader/reader.rs (hunk 14 above)
Comment (StrikeW) [reply src/connector/src/source/reader/reader.rs:110]: No. only a step in `recordCommitter.markBatchFinished` is no-op for cdc sources that are not pg and oracle.
```java
/**
     * Commits the given offset with the source database. Used by some connectors
     * like Postgres and Oracle to indicate how far the source TX log can be
     * discarded.
     */
    default void commitOffset(Map<String, ?> partition, Map<String, ?> offset) {
    }
```
I got your point. To be cautious, we should call those methods for all cdc connectors.

**Review by BugenZhao — APPROVED** [review]
LGTM for the executor part
