### PR TITLE
fix: reject concurrent altering table column

### LINKED ISSUE #17093: bug: sql-backend meta node panics when there are concurrent `ALTER TABLE ADD COLUMN` requests
### Describe the bug

SQL-backend meta node panics when there are concurrent `ALTER TABLE ADD COLUMN` requests.

### Error message/log

```text
thread 'rw-main' panicked at src/meta/src/barrier/info.rs:162:22:
actor not found
stack backtrace:

0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:197:5
   3: core::panicking::panic_str
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:172:5
   4: core::option::expect_failed
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/option.rs:1995:5
   5: core::option::Option<T>::expect
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/option.rs:896:21
   6: risingwave_meta::barrier::info::InflightActorInfo::post_apply
             at ./src/meta/src/barrier/info.rs:159:31
   7: risingwave_meta::barrier::state::BarrierManagerState::apply_command
             at ./src/meta/src/barrier/state.rs:81:9
   8: risingwave_meta::barrier::GlobalBarrierManager::handle_new_barrier
             at ./src/meta/src/barrier/mod.rs:725:20
   9: risingwave_meta::barrier::GlobalBarrierManager::run::{{closure}}
             at ./src/meta/src/barrier/mod.rs:706:37
  10: risingwave_meta::barrier::GlobalBarrierManager::start::{{closure}}
             at ./src/meta/src/barrier/mod.rs:497:46
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/future/future.rs:123:9
  12: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  13: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  15: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  16: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panic/unwind_safe.rs:272:9
  18: std::panicking::try::do_call
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  19: ___rust_try
  20: std::panicking::try
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  21: std::panic::catch_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  22: tokio::runtime::task::harness::poll_future
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  23: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  24: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  25: tokio::runtime::task::raw::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  26: tokio::runtime::task::raw::RawTask::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  27: tokio::runtime::task::LocalNotified<S>::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:427:9
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:639:17
  29: tokio::runtime::coop::with_budget
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  30: tokio::runtime::coop::budget
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  33: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  34: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  35: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  36: std::thread::local::LocalKey<T>::try_with
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/local.rs:284:16
  37: std::thread::local::LocalKey<T>::with
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/local.rs:260:9
  38: tokio::runtime::context::set_scheduler
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  39: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  40: tokio::runtime::context::runtime::enter_runtime
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  41: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  42: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  43: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42:21
  44: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  45: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  46: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  47: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  48: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  49: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panic/unwind_safe.rs:272:9
  50: std::panicking::try::do_call
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  51: ___rust_try
  52: std::panicking::try
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  53: std::panic::catch_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  54: tokio::runtime::task::harness::poll_future
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  55: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  56: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  57: tokio::runtime::task::raw::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  58: tokio::runtime::task::raw::RawTask::poll
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  59: tokio::runtime::task::UnownedTask<S>::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:464:9
  60: tokio::runtime::blocking::pool::Task::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:159:9
  61: tokio::runtime::blocking::pool::Inner::run
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:513:17
  62: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:471:13
```

### To Reproduce

1. Cleanup `~/.risingwave`.
2. Start single-node with `risingwave`.
3. Create a table with `create table t;`
4. Send concurrent `ALTER` requests with:
```bash
seq 1 10000 | parallel -j 8 "psql -h 0.0.0.0 -p 4566 -d dev -U root -c \"alter table t add column v{} int\""
```

### Expected behavior

May postpone or reject some requests, but no component should crash and the table must be remain in a consistent state.

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

`main`

### Additional context

With etcd backend, the cluster survives while rejecting some of the requests. This is achieved by the check here:

https://github.com/risingwavelabs/risingwave/blob/e2354fa9c3ba6f088e6ac3edb8165d07372d567a/src/meta/src/manager/catalog/mod.rs#L3351-L3354

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #17093 , this PR used the temp object dependency record of altering column to distinguish whether the target table is being altering. 
1. For altering table column, query will be used to check if the target table is being altered or referring by some creating jobs.
```sql
SELECT Count(*) AS num_items
FROM
  (SELECT "object_dependency"."id",
          "object_dependency"."oid",
          "object_dependency"."used_by"
   FROM "object_dependency"
   INNER JOIN "object" ON "object_dependency"."used_by" = "object"."oid"
   INNER JOIN "streaming_job" ON "object"."oid" = "streaming_job"."job_id"
   WHERE "object_dependency"."oid" = 6
     AND "object"."obj_type" = 'TABLE'
     AND "streaming_job"."job_status" <> 'CREATED') AS "sub_query"
```
2. For creating mview, query will be used to check if any dependent relations are being altering.
```sql
SELECT COUNT(*) AS num_items
FROM
  (SELECT "object_dependency"."id",
          "object_dependency"."oid",
          "object_dependency"."used_by"
   FROM "object_dependency"
   INNER JOIN "object" ON "object_dependency"."used_by" = "object"."oid"
   INNER JOIN "streaming_job" ON "object"."oid" = "streaming_job"."job_id"
   WHERE "object_dependency"."oid" IN (6)
     AND "object"."obj_type" = 'TABLE'
     AND "streaming_job"."job_status" <> 'CREATED'
     AND "object"."oid" NOT IN
       (SELECT "table_id"
        FROM "table") ) AS "sub_query"
```

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/meta/src/controller/streaming_job.rs [hunk 1]
```diff
@@ -541,12 +541,32 @@ impl CatalogController {
...
+            .join(JoinType::InnerJoin, object::Relation::StreamingJob.def())
+            .filter(
+                object_dependency::Column::Oid
+                    .eq(id as ObjectId)
+                    .and(object::Column::ObjType.eq(ObjectType::Table))
+                    .and(streaming_job::Column::JobStatus.ne(JobStatus::Created)),
+            )
+            .count(&txn)
+            .await?;
+        if replacing_cnt != 0 {
```
Comment (BugenZhao) [inline src/meta/src/controller/streaming_job.rs:559]: Is it possible that there'a race case where multiple threads pass this check, as we don't do this in the same transaction as insertion of job obj?

Comment (yezizp2012) [reply src/meta/src/controller/streaming_job.rs:559]: No, the function is protected by a read-write lock inside the catalog controller.

**Review by BugenZhao — APPROVED** [review]
LGTM. Wondering if it's possible to write some tests to cover it.

File: src/meta/src/controller/streaming_job.rs [hunk 2]
```diff
@@ -541,12 +541,32 @@ impl CatalogController {
...
+            assert_eq!(replacing_cnt, 1);
+            return Err(MetaError::permission_denied("table is being altered"));
+        }
```
Comment (yuhao-su) [inline src/meta/src/controller/streaming_job.rs:562]: Is it possible we have a `create mv on table` blocking the `alter` since you are checking the existing table object in streaming job

Comment (yezizp2012) [reply src/meta/src/controller/streaming_job.rs:562]: Oh yes, 👍  after some tests I found that `alter` will make `create mv on table` fail and trigger recovery if it's under barrier collection step. So I think `create mv on table` should be mutually exclusive with `block` alter as well. Let me remove the assertion and add the check in create side as well.

Comment (yezizp2012) [reply src/meta/src/controller/streaming_job.rs]: Updated. The following query will be used for `create mv on table`:
```sql
SELECT COUNT(*) AS num_items
FROM
  (SELECT "object_dependency"."id",
          "object_dependency"."oid",
          "object_dependency"."used_by"
   FROM "object_dependency"
   INNER JOIN "object" ON "object_dependency"."used_by" = "object"."oid"
   INNER JOIN "streaming_job" ON "object"."oid" = "streaming_job"."job_id"
   WHERE "object_dependency"."oid" IN (6)
     AND "object"."obj_type" = 'TABLE'
     AND "streaming_job"."job_status" <> 'CREATED'
     AND "object"."oid" NOT IN
       (SELECT "table_id"
        FROM "table") ) AS "sub_query"
```
