### PR TITLE
fix: invalid schema type for LogicalVectorSearchLookupJoin

### LINKED ISSUE #23891: `CorrelatedTopNToVectorSearchRule` have inconsistent output schema
For example:
```sql
create table items (id int primary key, extra string, text string, embedding vector(3)) append only;
create index i on items using flat (embedding) include(text) with (distance_type = 'l2');
explain(trace) with input as (select '[3,2,1]'::vector(3) as embedding) select array(select row(id, text) from items order by input.embedding <-> items.embedding limit 2) as related_info from input;
```

```txt
Previous:
 LogicalProject { exprs: [$expr3] }
 └─LogicalApply { type: LeftOuter, on: true, correlated_id: 1, max_one_row: true }
   ├─LogicalProject { exprs: ['[3,2,1]':Vector(3)] }
   │ └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
   └─LogicalProject { exprs: [Coalesce(array_agg($expr1 order_by($expr2 ASC)), ARRAY[]:List(Struct(StructType { fields: [("f1", Int32), ("f2", Varchar)] }))) as $expr3] }
     └─LogicalAgg { aggs: [array_agg($expr1 order_by($expr2 ASC))] }
       └─LogicalTopN { order: [$expr2 ASC], limit: 2, offset: 0 }
         └─LogicalProject { exprs: [Row(items.id, items.text) as $expr1, L2Distance(CorrelatedInputRef { index: 0, correlated_id: 1 }, items.embedding) as $expr2] }
           └─LogicalScan { table: items, columns: [id, extra, text, embedding, _rw_timestamp] }

LogicalApply's schema: { fields: ['[3,2,1]':Vector(3):Vector(3), $expr10003:List(Struct(StructType { fields: [("f1", Int32), ("f2", Varchar)] }))] }

After CorrelatedTopNToVectorSearchRule:
 LogicalProject { exprs: [array] }
 └─LogicalVectorSearchLookupJoin { distance_type: L2Sqr, top_n: 2, input_vector: '[3,2,1]':Vector(3):Vector(3), lookup_vector: items.embedding }
   ├─LogicalProject { exprs: ['[3,2,1]':Vector(3)] }
   │ └─LogicalValues { rows: [[]], schema: Schema { fields: [] } }
   └─LogicalScan { table: items, columns: [id, extra, text, embedding, _rw_timestamp] }

LogicalVectorSearchLookupJoin's schema: { fields: ['[3,2,1]':Vector(3):Vector(3), array:List(Struct(StructType { fields: [("items.id", Int32), ("items.text", Varchar)] }))] }


```

_Originally posted by @silver-ymz in https://github.com/risingwavelabs/risingwave/issues/23154#issuecomment-3584505972_

### PR DESCRIPTION
**Pull request by silver-ymz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

close #23891

`CorrelatedTopNToVectorSearchRule` only specifies following logical plan pattern.

```
LogicalApply { type: LeftOuter, on: true, correlated_id, max_one_row: true }
 └─ LogicalProject { exprs: [[Coalesce(array_agg($expr1 order_by($expr2 ASC)), ARRAY[]) as $expr3] }
    └─ LogicalAgg { aggs: [array_agg($expr1 order_by($expr2 ASC))] }
       └─ LogicalTopN { order: [$expr2 ASC] }
          └─ LogicalProject { exprs: [Row(...) as $expr1, L2Distance(CorrelatedInputRef { index: 0, correlated_id: 1 }, items.embedding) as $expr2] }
```

This logical plan should have schema same as `array(row(...))`, so the inner struct type should be an unnamed struct.

## Checklist

- [x] I have written necessary rustdoc comments.
- [x]  I have added necessary unit tests and integration tests.
- [x]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/logical_vector_search_lookup_join.rs [hunk 1]
```diff
@@ -66,17 +66,14 @@ impl VectorSearchLookupJoinCore {
     }
 
     fn struct_type(&self) -> StructType {
-        StructType::new(
+        StructType::unnamed(
```
Comment (wenym1) [inline src/frontend/src/optimizer/plan_node/logical_vector_search_lookup_join.rs]: Shall we have a unified method in `StructType` like `fn row_expr_type(types: impl Iterator<Item = DataType>)` and call in both here and in `bind_row` so that we can explicitly declare that here we construct the struct type in the same way as `row`?

**Review by wenym1 — APPROVED** [review]
Rest LGTM. Thanks for the quick fix!

File: src/frontend/src/optimizer/plan_node/logical_vector_search_lookup_join.rs (hunk 1 above)
Comment (silver-ymz) [reply src/frontend/src/optimizer/plan_node/logical_vector_search_lookup_join.rs]: updated in new commit
