### PR TITLE
fix(risedev): fill-in CONNECTOR_LIBS_PATH if set

### LINKED ISSUE #12922: Cannot connect to connector when starting up risingwave with risedev
### Describe the bug

Hit `environment variable CONNECTOR_LIBS_PATH is not specified` when trying to CREATE TABLE for mysql-cdc with risingwave started up via risedev

### Error message/log

```text
dev=> set cdc_backfill='true';

CREATE TABLE lineitem_rw (
   k int primary key,
   v int
) WITH (
    connector = 'mysql-cdc',
    hostname = '127.0.0.1',
    port = '8306',
    username = 'root',
    password = '123456',
    database.name = 'test',
    table.name = 'test',
    server.id = '2'
);
SET_VARIABLE
ERROR:  QueryError: internal error: internal error: environment variable CONNECTOR_LIBS_PATH is not specified
```

### To Reproduce

1. `risedev configure` to enable connector build
2. `risedev d` to start dev playground
3. Start up a local mysql instance and create a test table.
4. Run the following query in psql
```
dev=> set cdc_backfill='true';
SET_VARIABLE

dev=>CREATE TABLE lineitem_rw (
   k int primary key,
   v int
) WITH (
    connector = 'mysql-cdc',
    hostname = '127.0.0.1',
    port = '8306',
    username = 'root',
    password = '123456',
    database.name = 'test',
    table.name = 'test',
    server.id = '2'
);

ERROR:  QueryError: internal error: internal error: environment variable CONNECTOR_LIBS_PATH is not specified

```

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hzxa21**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #12922

Tested in my local box and I can create mysql-cdc source table successfully.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/risedevtool/src/task/compactor_service.rs [hunk 1]
```diff
@@ -96,6 +96,13 @@ impl Task for CompactorService {
             cmd.env("MALLOC_CONF", conf); // unprefixed for linux
         }
 
+        if crate::util::is_env_set("CONNECTOR_LIBS_PATH") {
+            cmd.env(
+                "CONNECTOR_LIBS_PATH",
+                env::var("CONNECTOR_LIBS_PATH").unwrap(),
+            );
+        }
```
Comment (BugenZhao) [inline src/risedevtool/src/task/compactor_service.rs:104]: Don't quite get that. Is this a no-op?

Comment (hzxa21) [reply src/risedevtool/src/task/compactor_service.rs:104]: Nope. `cmd.env` will set the env for the tmux session while `env::var("CONNECTOR_LIBS_PATH")` will get the host process env.

Comment (BugenZhao) [reply src/risedevtool/src/task/compactor_service.rs:104]: Oh, I missed that. However, I guess it may not a good practice to export the "path" env var in `user.env`. As you can see, there're only boolean variables and they control whether the `risedev` will prepare or build some components, but usually have nothing to do with `risedev-dev` (`./risedev d`).

**Comment by chenzl25** [comment]
https://github.com/risingwavelabs/risingwave/blob/0ca0ee46a0b4efa57314dba3c355f772e9c0df2c/src/risedevtool/config/src/main.rs#L397-L402

**Comment by hzxa21** [comment]
> I handled `CONNECTOR_LIBS_PATH` in this way while risedev configure. It works on my laptop.
> 
> https://github.com/risingwavelabs/risingwave/blob/0ca0ee46a0b4efa57314dba3c355f772e9c0df2c/src/risedevtool/config/src/main.rs#L397-L402

It doesn't work in my local ubuntu box. What is your tmux version?

File: src/risedevtool/src/task/compactor_service.rs (hunk 1 above)
Comment (chenzl25) [reply src/risedevtool/src/task/compactor_service.rs:104]: Agree. We can remove configuration `CONNECTOR_LIBS_PATH` from `risingwave/src/risedevtool/config/src/main.rs` and add it to `src/risedevtool/src/task/compute_node_service.rs` and `src/risedevtool/src/task/meta_node_service.rs`. BTW, this configuration is not needed for frontend and compactor.

Comment (hzxa21) [reply src/risedevtool/src/task/compactor_service.rs:104]: > Agree. We can remove configuration `CONNECTOR_LIBS_PATH` from `risingwave/src/risedevtool/config/src/main.rs` and add it to `src/risedevtool/src/task/compute_node_service.rs` and `src/risedevtool/src/task/meta_node_service.rs`. BTW, this configuration is not needed for frontend and compactor.

+1.

**Comment by StrikeW** [comment]
I can start the cluster with embedded jvm if only `export CONNECTOR_LIBS_PATH=".risingwave/bin/connector-node/libs"
` in my `~/.zshenv`, seems we don't need this patch?

**Comment by hzxa21** [comment]
> I can start the cluster with embedded jvm if only `export CONNECTOR_LIBS_PATH=".risingwave/bin/connector-node/libs" ` in my `~/.zshenv`, seems we don't need this patch?

Yes, if you have CONNECTOR_LIBS_PATH in your zshenv, things should work. New findings here: https://github.com/risingwavelabs/risingwave/issues/12922#issuecomment-1767694633

But I still think it is better to do all the necessary env settings in risedev since newcomers or users won't know they need to set `CONNECTOR_LIBS_PATH` in zshenv. It is also weird to ask them to do so.

File: src/risedevtool/src/task/compactor_service.rs (hunk 1 above)
Comment (hzxa21) [reply src/risedevtool/src/task/compactor_service.rs]: Addressed in the new commit.

File: src/risedevtool/src/task/compute_node_service.rs [hunk 2]
```diff
@@ -102,6 +102,13 @@ impl Task for ComputeNodeService {
             cmd.env("MALLOC_CONF", conf); // unprefixed for linux
         }
 
+        if crate::util::is_env_set("ENABLE_BUILD_RW_CONNECTOR") {
+            cmd.env(
+                "CONNECTOR_LIBS_PATH",
+                ".risingwave/bin/connector-node/libs/",
```
Comment (BugenZhao) [inline src/risedevtool/src/task/compute_node_service.rs:108]: What about using env var `PREFIX_BIN`? Not a big deal, but make it more consistent.

**Review by BugenZhao — APPROVED** [review]

**Review by chenzl25 — APPROVED** [review]
LGTM
