### PR TITLE
fix(array): unify hash function for datum and array

### LINKED ISSUE #3457: `Hash` implementation on `Datum` is not consistent with `Array::hash_at`
As long as we use `Datum` in a row, this affects the correctness of the consistent hash.

We use `Datum::hash` (`Option<ScalarImpl>::hash`) when hashing a row,
https://github.com/singularity-data/risingwave/blob/d577da0ce396438acd9455b7f07b6ad041038bc6/src/common/src/array/data_chunk_iter.rs#L292-L302

while using `Array::hash_at` when hashing an array or a data chunk.
https://github.com/singularity-data/risingwave/blob/d864f300132b41e6734c21f8ccfe5a7fd3cdb6b4/src/common/src/array/stream_chunk.rs#L229-L241

The behavior of these two implementations differs on...
- `Array::hash_at` manually hash `NULL` as `NULL_VAL_FOR_HASH`, while null datum is handled by `Option`.
https://github.com/singularity-data/risingwave/blob/36d4930ad060728562c96deb28acb5a186b0e982/src/common/src/array/mod.rs#L77-L78
- `Array::hash_at` may also behave differently from `ScalarImpl::hash`.

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Unify the hash implementation into `Scalar::hash_scalar`. Also fix the implementation of the `hash_at` function for list and struct array.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #3457

### CODE REVIEW

File: src/common/src/types/mod.rs [hunk 1]
```diff
@@ -689,42 +695,53 @@ macro_rules! impl_scalar_impl_ref_conversion {
...
-        Some(scalar) => scalar.hash(state),
+    hash_datum_ref(to_datum_ref(datum), state)
+}
+
+/// Feeds the raw scalar reference of `datum_ref` to the given `state`, which should behave the same
+/// as [`crate::array::Array::hash_at`], where NULL value will be carefully handled.
+///
+/// **FIXME**: the result of this function might be different from [`std::hash::Hash`] due to the
+/// type alias of `DatumRef = Option<_>`, we should manually implement [`std::hash::Hash`] for
+/// [`DatumRef`] in the future when it becomes a newtype.
```
Comment (xxchan) [inline src/common/src/types/mod.rs:740]: We can add a link to https://github.com/risingwavelabs/risingwave/issues/477

**Review by xxchan — APPROVED** [review]
