### PR TITLE
fix(binder): report error when defaulting null values to a non-nullable column

### LINKED ISSUE #23378: Insert without `NOT NULL` column should report error
### Describe the bug

When inserting into a table and excluding a `NOT NULL` column, the query succeeds but no data is actually inserted.

### Error message/log

```text

```

### To Reproduce

```
dev=> create table t(id int not null, v varchar not null);
CREATE_TABLE
dev=> insert into t(id,v) values(1,'a');
INSERT 0 1
dev=> insert into t(id) values(1);
INSERT 0 1
dev=> flush;
FLUSH
dev=> select * from t;
 id | v 
----+---
  1 | a
(1 row)
dev=> 
```

### Expected behavior

Expected behavior is to raise an error indicating the missing non-nullable column.

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

v2.5.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by howenyap**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Closes #23378. When insert values default to `null` but the column is not nullable, wrap the expression in a check not null function call, referenced from [here](https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/binder/insert.rs#L380-L415).

Attempting to insert an unspecified `null` value into a non-nullable column now reports the error, instead of silently failing.
image

## Checklist

- [x] I have written necessary rustdoc comments.
- [x]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/frontend/src/binder/insert.rs [hunk 1]
```diff
@@ -311,18 +311,31 @@ impl Binder {
...
+                            expr,
+                            ExprImpl::literal_varchar(column.name().to_owned()),
+                            ExprImpl::literal_varchar(table_name.to_owned()),
+                        ],
+                        column.data_type().clone(),
+                    )
+                    .into()
+                };
+
+                Ok((i, expr))
```
Comment (kwannoel) [inline src/frontend/src/binder/insert.rs]: Why need to return `Ok(...)` here?

Comment (kwannoel) [reply src/frontend/src/binder/insert.rs]: Here we only construct the function call which is pure, it doesn't actually evaluate the function yet. Only later during evaluation of the function call an error will be returned.

Comment (howenyap) [reply src/frontend/src/binder/insert.rs]: yeap think I forgot to remove it from an earlier version of the code, will make the change to return a regular tuple instead

**Comment by howenyap** [comment]
not sure why build took so long this time and timed out

**Comment by BugenZhao** [comment]
> not sure why build took so long this time and timed out

I guess it's because we recently updated the toolchain version, causing cache miss during the compilation of many crates. Rebasing the branch and retrying should help.
