### PR TITLE
fix: fix recovery hang and in-consistency for create/drop streaming jobs

### LINKED ISSUE #5145: fix(meta): Fix notification version synchronization problem after `re-subscribe`
Discussed in #5132.
Here are the steps that a frontend calls a ddl RPC.
1. frontend send a RPC request to meta.
2. meta send a notification to frontend in notification stream.
3. meta send a RPC response to frontend.
4. frontend wait a version which is sent by observer_manager after handling the notification.

If step 2's stream is broken, frontend will call `re-subscribe` to request catalog snapshot and catalog version, and send the version to step 4 to avoid request hang. But if meta reboots before `re-subscribe`, frontend will get a small init catalog version, and step 4 will wait until the new version is bigger than the value before meta reboots.

We plan to fix this after we de-couple ckpt and barrier.

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fixed several bugs in recovery deterministic test with `--kill-meta`:
1. recovery deterministic will hang occasionally.

_Originally posted by @yezizp2012 in https://github.com/risingwavelabs/risingwave/issues/5444#issuecomment-1254868444_

the reason is #5145. In this PR, I persist the notification version and try not to block waiting ddl operation using correct dll version.

2. added catalog error for meta and reported it to frontend to fulfill should retry check in simulation. Because currently it uses whether the error message contains `exists` as should retry condition, but some e2e test SQLs will contains `exists` as well. So I changed the condition to whether the error message contains `exists` and `Catalog error`.
3. since we introduced asynchronously delete streaming job in `StreamingJobBackgroundDeleter`, those to-delete streaming jobs should be cleaned before recovery and should not be rebuilt. If not so, the recovery process will fail due to `source not found` error. So in this PR, I added a tracker `in_progress_creation_streaming_job` in catalog manager, to avoid some in-consistency when cleaning streaming jobs at the beginning of recovery. This's just a workaround and should be refactored when we start to refactor `CatalogManager` and `TableFragmentManager`.

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Resolve #5145 Part of #4527

### CODE REVIEW

**Comment by yezizp2012** [comment]
After this PR merged, there will be only one bug found here:
# command
```
RUST_BACKTRACE=1 MADSIM_TEST_SEED=1 ./risedev sslt --release -- --kill-meta "e2e_test/streaming/tpch_upstream.slt"
```
# bug
actor exist unexpected when executing `include ../tpch/insert_orders.slt.part`:
```
2022-01-02T02:50:32.590521Z ERROR node{id=8 name="compute-3"}:task{id=966416}: risingwave_stream::task::stream_manager: actor exit actor=76007 error=Executor error: Deleting non-existent element
2022-01-02T02:50:32.590523Z ERROR node{id=8 name="compute-3"}:task{id=966412}: risingwave_stream::executor::actor: actor exit without stop barrier actor_id=76001
2022-01-02T02:50:32.590524Z ERROR node{id=6 name="compute-1"}:task{id=970788}: risingwave_stream::executor::actor: actor exit without stop barrier actor_id=76006
2022-01-02T02:50:32.590527Z ERROR node{id=8 name="compute-3"}:task{id=966418}: risingwave_stream::executor::subtask: actor downstream subtask failed
2022-01-02T02:50:32.590527Z ERROR node{id=8 name="compute-3"}:task{id=966418}: risingwave_stream::task::stream_manager: actor exit actor=76008 error=Executor error: Deleting non-existent element
...
2022-01-02T02:50:32.664685Z ERROR node{id=8 name="compute-3"}:task{id=966220}: risingwave_stream::task::stream_manager: actor exit actor=25019 error=Executor error: failed to pull left message, stream closed unexpectedly
2022-01-02T02:50:32.664695Z ERROR node{id=7 name="compute-2"}:task{id=974637}: risingwave_stream::task::stream_manager: actor exit actor=25028 error=Executor error: right barrier received while left stream end
2022-01-02T02:50:32.664747Z ERROR node{id=7 name="compute-2"}:task{id=974635}: risingwave_stream::task::stream_manager: actor exit actor=25027 error=Executor error: right barrier received while left stream end
2022-01-02T02:50:32.664839Z ERROR node{id=6 name="compute-1"}:task{id=970246}: risingwave_stream::task::stream_manager: actor exit actor=40012 error=Executor error: right barrier received while left stream end
2022-01-02T02:50:32.664850Z ERROR node{id=6 name="compute-1"}:task{id=970674}: risingwave_stream::task::stream_manager: actor exit actor=49011 error=Executor error: left barrier received while right stream end
2022-01-02T02:50:32.664888Z ERROR node{id=8 name="compute-3"}:task{id=966502}: risingwave_stream::task::stream_manager: actor exit actor=46008 error=Executor error: right barrier received while left stream end
2022-01-02T02:50:32.664935Z ERROR node{id=8 name="compute-3"}:task{id=966276}: risingwave_stream::task::stream_manager: actor exit actor=19015 error=Executor error: left barrier received while right stream end
```

Seems like this bug caused in range cache of `dynamic_filter` state. Need more investigation.

File: src/common/src/error.rs [hunk 1]
```diff
@@ -268,6 +268,9 @@ impl From<tonic::Status> for RwError {
             Code::InvalidArgument => {
                 ErrorCode::InvalidParameterValue(err.message().to_string()).into()
             }
+            Code::NotFound | Code::AlreadyExists => {
```
Comment (BugenZhao) [inline src/common/src/error.rs:271]: Not sure whether it's okay to always treat these codes as `CatalogError`, though there seems to be no similar error to report to the user. 🤔

File: src/meta/src/error.rs [hunk 2]
```diff
@@ -94,6 +101,14 @@ impl MetaError {
         use std::borrow::Borrow;
         std::matches!(self.inner.borrow(), &MetaErrorInner::InvalidWorker(_))
     }
+
+    pub fn catalog_not_found<T: ToString>(relation: &'static str, name: T) -> Self {
```
Comment (BugenZhao) [inline src/meta/src/error.rs:105]: `ToString` calls `Display::fmt`. I think what we need is `Into<String>` in most cases.

```suggestion
    pub fn catalog_not_found<T: Into<String>>(relation: &'static str, name: T) -> Self {
```

File: src/meta/src/manager/catalog/fragment.rs [hunk 3]
```diff
@@ -207,14 +207,12 @@ where
...
         let map = &mut self.core.write().await.table_fragments;
 
-        match map.entry(*table_id) {
-            Entry::Occupied(o) => {
-                TableFragments::delete(self.env.meta_store(), &table_id.table_id).await?;
-                o.remove();
-                Ok(())
-            }
-            Entry::Vacant(_) => bail!("table_fragment not exist: id={}", table_id),
+        if let Entry::Occupied(o) = map.entry(*table_id) {
```
Comment (BugenZhao) [inline src/meta/src/manager/catalog/fragment.rs:210]: Is the `vacant` arm reachable? We may add some warning if so.

File: src/meta/src/manager/catalog/mod.rs [hunk 4]
```diff
@@ -413,14 +413,18 @@ where
     pub async fn start_create_table_procedure(&self, table: &Table) -> MetaResult<()> {
         let core = &mut self.core.lock().await.database;
         let key = (table.database_id, table.schema_id, table.name.clone());
-        if !core.has_table(table) && !core.has_in_progress_creation(&key) {
+
+        if core.has_table(table) {
+            bail!("table already exists");
```
Comment (BugenZhao) [inline src/meta/src/manager/catalog/mod.rs:418]: Should we use `catalog_duplicated` here?

File: src/meta/src/manager/catalog/mod.rs [hunk 5]
```diff
@@ -413,14 +413,18 @@ where
...
+        } else if core.has_in_progress_creation(&key) {
+            bail!("table is in creating procedure");
```
Comment (BugenZhao) [inline src/meta/src/manager/catalog/mod.rs:420]: Is this reachable, or should we panic here?

File: src/meta/src/model/notification.rs [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+/// persistently to meta store.
+pub struct NotificationVersion(u64);
+
+impl NotificationVersion {
+    pub async fn new<S>(store: &S) -> Self
+    where
+        S: MetaStore,
+    {
+        let version = match store
+            .get_cf(DEFAULT_COLUMN_FAMILY, b"notification_version")
```
Comment (BugenZhao) [inline src/meta/src/model/notification.rs:27]: How about extracting the key to a constant?

File: src/stream/src/executor/barrier_align.rs [hunk 7]
```diff
@@ -83,7 +85,11 @@ pub async fn barrier_align(
                 Message::Barrier(_) => loop {
                     let start_time = Instant::now();
                     // received left barrier, waiting for right barrier
-                    match right.next().await.unwrap()? {
+                    match right
+                        .next()
+                        .await
+                        .context("failed to pull right message, stream closed unexpectedly")??
```
Comment (BugenZhao) [inline src/stream/src/executor/barrier_align.rs:91]:
```suggestion
                        .context("failed to poll right message, stream closed unexpectedly")??
```

**Review by BugenZhao — APPROVED** [review]
LGTM 🥰

File: src/meta/src/manager/catalog/fragment.rs (hunk 3 above)
Comment (yezizp2012) [reply src/meta/src/manager/catalog/fragment.rs:210]: Yes, it might be cleaned when recovery. I will add some warning here.

File: src/meta/src/manager/catalog/mod.rs (hunk 5 above)
Comment (yezizp2012) [reply src/meta/src/manager/catalog/mod.rs:420]: No, user might create relation with duplicate name in different session.

Comment (BugenZhao) [reply src/meta/src/manager/catalog/mod.rs:420]: You're right. So this is actaully "a table with duplicated name is in creating procedure"?

File: src/common/src/error.rs (hunk 1 above)
Comment (yezizp2012) [reply src/common/src/error.rs:268]: Yes, I think we can introduce an error message format here when come up with some other errors that need to use `Code::NotFound` or `Code::AlreadyExists`.
