### PR TITLE
fix: report unexpected actor exit to local barrier manager

### LINKED ISSUE #6319: streaming: report error to local barrier manager explicitly when error occurs
If an error (not panic) occurs during the execution of an actor, the actor will exit with `Err`, and without reporting to the local barrier manager. The exiting of the actor will cause upstream/downstream to exit, and finally cause a failure when injecting the **next** barrier, which will be realized by the meta service and trigger the fail-over procedure.

However, if the in-flight concurrent checkpoint has reached the maximum (or is simply set to `1`), the compute nodes will hang forever, while the heartbeat acts normally. We'll fail to recover the cluster.

We may need to explicitly report the error to the local barrier manager, so that the meta service will realize the failure ASAP.

cc @StrikeW @yezizp2012

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Fix #6319

### CODE REVIEW

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 1]
```diff
@@ -150,6 +152,34 @@ impl ManagedBarrierState {
...
     }
 
+    /// Notify unexpected actor exit with given `actor_id`.
+    pub(crate) fn notify_exit(&mut self, actor_id: ActorId) {
+        for (_, barrier_state) in &mut self.epoch_barrier_state_map {
+            match barrier_state.inner {
+                ManagedBarrierStateInner::Issued {
+                    ref remaining_actors,
+                    ref mut collect_notifier,
+                } => {
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:163]: I think we should also handle the `Stashed` case. Unfortunately, we don't have the `collect_notifier` here.

Considering this, how about adding a `Failed` state? If `transfrom_to_issued` meets `Failed`, it should directly send the `Err` to the channel. If multiple actors fail, the latter ones will also find this state has failed and do nothing.

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 2]
```diff
@@ -150,6 +152,34 @@ impl ManagedBarrierState {
...
+                    if remaining_actors.contains(&actor_id) {
+                        let collect_notifier = std::mem::take(collect_notifier);
+                        if collect_notifier
+                            .unwrap()
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:167]: Will this `unwrap` panic if multiple actors throw error?

Comment (yezizp2012) [reply src/stream/src/task/barrier_manager/managed_state.rs:167]: Good catch, it should do nothing if the collect notifier is None.

File: src/stream/src/task/barrier_manager/managed_state.rs (hunk 1 above)
Comment (yezizp2012) [reply src/stream/src/task/barrier_manager/managed_state.rs:163]: > 
> If multiple actors fail, the latter ones will also find this state has failed and do nothing.

So the `Failed` state should be a status of `ManagedBarrierState` rather than `BarrierState` and don't bind to any epoch. I will give it a try.

Comment (yezizp2012) [reply src/stream/src/task/barrier_manager/managed_state.rs:170]: I added a field `exited_actors` rather than a simple `Failed` state for compatibility, if we want to support partial checkpoint in the future.

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 3]
```diff
@@ -148,6 +155,37 @@ impl ManagedBarrierState {
...
+            match barrier_state.inner {
+                ManagedBarrierStateInner::Issued {
+                    ref remaining_actors,
+                    ref mut collect_notifier,
+                } => {
+                    if remaining_actors.contains(&actor_id) && collect_notifier.is_some() {
+                        let collect_notifier = std::mem::take(collect_notifier);
+                        if collect_notifier
+                            .unwrap()
+                            .send(Err(anyhow!(format!(
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:175]:
```suggestion
                    if remaining_actors.contains(&actor_id) && let Some(collect_notifier) = collect_notifier.take() {
                        if collect_notifier
                            .send(Err(anyhow!(
```

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 4]
```diff
@@ -222,14 +260,19 @@ impl ManagedBarrierState {
...
                 ..
             }) => {
-                let remaining_actors = actor_ids_to_collect
+                let remaining_actors: HashSet<ActorId> = actor_ids_to_collect
                     .into_iter()
                     .filter(|a| !collected_actors.remove(a))
                     .collect();
+                for exited_actor in &self.exited_actors {
+                    if remaining_actors.contains(exited_actor) {
+                        bail!("Actor {} exit unexpectedly", exited_actor);
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:269]: We report the failure through the channel if an error occurs on `Issued`, while through the return value of this function if on `Stashed`. 🤔 Can we make the behavior more consistent?

Comment (yezizp2012) [reply src/stream/src/task/barrier_manager/managed_state.rs:269]: Unlikely, I'm afraid. 😢  If we do the check at the start of `send barrier` and `collect barrier`, we still need to report the failure through the channel at the time of collection, as actor exit may also occur while waiting for the collection to complete.

File: src/stream/src/task/barrier_manager.rs [hunk 5]
```diff
@@ -214,8 +214,19 @@ impl LocalBarrierManager {
                 managed_state.collect(actor_id, barrier);
             }
         }
+    }
 
-        Ok(())
+    /// When a actor exit unexpectedly, it should report this event using this function, so meta
+    /// will notice actor's exit while collecting.
+    pub fn notify_exit(&mut self, actor_id: ActorId) {
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager.rs:221]: We will only call this if the actor exits on **failure**. How about naming it `notify_failure`?

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 6]
```diff
@@ -148,6 +155,32 @@ impl ManagedBarrierState {
...
+            match barrier_state.inner {
+                ManagedBarrierStateInner::Issued {
+                    ref remaining_actors,
+                    ref mut collect_notifier,
+                } => {
+                    if remaining_actors.contains(&actor_id) && let Some(collect_notifier) = collect_notifier.take() && collect_notifier
+                            .send(Err(anyhow!(format!(
+                                "Actor {} exit unexpectedly",
+                                actor_id
+                            ))
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:175]: How about also encoding the original error reported by the actor in this message? So that the meta service will give a more reasonable error message.

File: src/stream/src/task/barrier_manager/managed_state.rs [hunk 7]
```diff
@@ -222,14 +255,19 @@ impl ManagedBarrierState {
...
                 ..
             }) => {
-                let remaining_actors = actor_ids_to_collect
+                let remaining_actors: HashSet<ActorId> = actor_ids_to_collect
                     .into_iter()
                     .filter(|a| !collected_actors.remove(a))
                     .collect();
+                for actor_id in &self.failure_actors {
+                    if remaining_actors.contains(actor_id) {
+                        bail!("Actor {} exit unexpectedly", actor_id);
```
Comment (BugenZhao) [inline src/stream/src/task/barrier_manager/managed_state.rs:264]: Can we also throw the original error here?

Comment (yezizp2012) [reply src/stream/src/task/barrier_manager/managed_state.rs:264]: Well, the `StreamError` does not implement `Clone` trait, and it seems quite hard to do that. 😢  Do you think storing an internal error with original error encoded in `failure_actors` is acceptable?

Comment (BugenZhao) [reply src/stream/src/task/barrier_manager/managed_state.rs:264]: Seems there's no need to `Clone` the error. We can take ownership of the error instead of `inspect` it. 🤩

**Review by BugenZhao — APPROVED** [review]
