### PR TITLE
fix(storage): sync a bounded epoch range in each sync call

### LINKED ISSUE #5209: bug(storage): panicked: when sync an epoch, there should not be any uploading task
### Describe the bug

```
thread 'risingwave-main' panicked at 'when sync an epoch, there should not be any uploading task', src/storage/src/hummock/shared_buffer/mod.rs:290:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::shared_buffer::SharedBuffer::into_uncommitted_data
             at ./src/storage/src/hummock/shared_buffer/mod.rs:290:9
   3: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer_le_epoch::{{closure}}::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:545:61
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/ops/function.rs:301:13
   5: core::option::Option<T>::map
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/option.rs:929:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/map.rs:103:9
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter.rs:33:9
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/mod.rs:2648:9
  10: core::iter::traits::iterator::Iterator::collect
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/traits/iterator.rs:1836:9
  11: itertools::Itertools::collect_vec
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/lib.rs:1985:9
  12: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer_le_epoch::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:541:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  14: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:521:48
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  16: risingwave_storage::hummock::state_store::<impl risingwave_storage::store::StateStore for risingwave_storage::hummock::HummockStorage>::sync::{{closure}}
             at ./src/storage/src/hummock/state_store.rs:648:43
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  18: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  19: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  20: <risingwave_storage::monitor::monitored_store::MonitoredStateStore<S> as risingwave_storage::store::StateStore>::sync::{{closure}}
             at ./src/storage/src/monitor/monitored_store.rs:251:43
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  22: risingwave_stream::task::stream_manager::LocalStreamManager::sync_epoch::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:239:36
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  24: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  25: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  26: <risingwave_compute::rpc::service::stream_service::StreamServiceImpl as risingwave_pb::stream_service::stream_service_server::StreamService>::barrier_complete::{{closure}}
             at ./src/compute/src/rpc/service/stream_service.rs:166:75
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  29: <<risingwave_pb::stream_service::stream_service_server::StreamServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::BarrierCompleteSvc<T> as tonic::server::service::UnaryService<risingwave_pb::stream_service::BarrierCompleteRequest>>::call::{{closure}}
             at ./src/prost/src/stream_service.rs:941:67
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  32: tonic::server::grpc::Grpc<T>::unary::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.0/src/server/grpc.rs:166:27
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  34: <risingwave_pb::stream_service::stream_service_server::StreamServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
             at ./src/prost/src/stream_service.rs:958:58
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
 ... omitted ...
```

Full logs here: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9524115/risingwave-log.tgz)

### To Reproduce

1. Start the cluster with `./risedev d full`
2. Create sources:

```sql
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

3. Create MView:

```sql
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

4. Wait for 1 hour

### Expected behavior

_No response_

### Additional context

Full logs here: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9524115/risingwave-log.tgz)

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR intends to fix #5209. The cause of the bug is described in the discussion of the issue.

We fix the bug by ensuring that each sync call only syncs a bounded range of epochs. In detail, in each sync call, we will try to advance the current `max_sync_epoch`, and get the `prev_max_sync_epoch`, after which the sync call will only sync the epochs with `prev_max_sync_epoch < epoch < new_sync_epoch`, so that the epochs synced in each sync call is separated.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
fix #5209

### CODE REVIEW

**Comment by wenym1** [comment]
I have run an e2e test with the SQLs in the issue description and set the `shared_buffer_capacity_mb` to 1MB. 

With this setting, the main branch will panic within seconds, while for this PR it can keep running for at least 5 minute before I shut it down.

File: src/storage/src/hummock/local_version.rs [hunk 1]
```diff
@@ -126,8 +126,12 @@ impl LocalVersion {
         &self.pinned_version
     }
 
-    pub fn swap_max_sync_epoch(&mut self, epoch: HummockEpoch) -> Option<HummockEpoch> {
-        if self.max_sync_epoch > epoch {
+    /// Advance the `max_sync_epoch` to at least `new_epoch`.
+    ///
+    /// Return `Some(prev max_sync_epoch)` if `new_epoch > max_sync_epoch`
+    /// Return `None` if `new_epoch <= max_sync_epoch`
+    pub fn advance_max_sync_epoch(&mut self, epoch: HummockEpoch) -> Option<HummockEpoch> {
```
Comment (hzxa21) [inline src/storage/src/hummock/local_version.rs:133]: nits: name the parameter as `new_epoch` to make it consistent with the documentation.

**Review by hzxa21 — APPROVED** [review]
LGTM

**Review by xxhZs — APPROVED** [review]
