### PR TITLE
fix(binder): support schema-qualified names on `BindContext`

### LINKED ISSUE #6744: Bug(Binder): should not allow to refer the oringinal schema name + table alias
### Describe the bug

Users can refer table with the table's original schema name and table alias, which is illegal in PG and other DB system.

### To Reproduce

```
dev=> create schema s;
CREATE_SCHEMA
dev=> create schema ^C
dev=> create table s.t(v int);
CREATE_TABLE
dev=> select s.tt.v from s.t tt;
 v 
---
(0 rows)dev=> create schema s;
CREATE_SCHEMA
dev=> create schema ^C
dev=> create table s.t(v int);
CREATE_TABLE
dev=> select s.tt.v from s.t tt;
 v 
---
(0 rows)
```

### Expected behavior

in PG: 
```
dev=# create schema s;
CREATE SCHEMA
dev=# create table s.t(v int);
CREATE TABLE
dev=# select s.tt.v from s.t tt;
ERROR:  invalid reference to FROM-clause entry for table "tt"
LINE 1: select s.tt.v from s.t tt;
               ^
HINT:  There is an entry for table "tt", but it cannot be referenced from this part of the query.

```

### Additional context

_No response_

### LINKED ISSUE #6774: Bug(binder): check the schema name when bind column
### Describe the bug

_No response_

### To Reproduce

```
dev=> CREATE SCHEMA s
dev-> ;
CREATE_SCHEMA
dev=> CREATE TABLE s.t(v int); 
CREATE_TABLE
dev=> select aaa.t.v from s.t;
 v 
---
(0 rows)
```

### Expected behavior

in PG 15
```
dev=# select aaa.t.v from s.t;
ERROR:  invalid reference to FROM-clause entry for table "t"
LINE 1: select aaa.t.v from s.t;
               ^
HINT:  There is an entry for table "t", but it cannot be referenced from this part of the query.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Standing-Man**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

- Closes Part of #5176.
- Closes #6744.
- Closes #6774.

This PR adds support for schema-qualified names in both `bindContext` and `bind_column`, improving name resolution with explicit schemas. Currently, `schema_name` and `table_alias` fields have been added to `ColumnBinding` to distinguish table name with the same column name under different schemas and to record table aliases.
- `schema_name: Optional<String>`: records the schema name about the column name.
- `table_alias: Option<String>`: records the original table name when the table has an alias.

For non-system schemas, when handling schema-qualified names in the `bind_column` function, we first check whether the specified schema exists in the current database, and then verify whether the table exists under that schema.

While adding support for schema-qualified names, the current implementation also improves error messages to better guide users in correcting SQL syntax.

```
dev > CREATE SCHEMA s;
dev > CREATE TABLE s.t(v int);
dev > SELECT s.t.v FROM s.t AS tt;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: s.t.v
  2: Invalid reference: missing FROM-clause entry for table "t"
HINT:  Perhaps you meant to reference the table alias "tt".
```

## Checklist

- [ ] I have written necessary rustdoc comments.
- [x]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by Standing-Man** [comment]
Hi @chenzl25, please take a look when you have time.

**Comment by Standing-Man** [comment]
Hi @chenzl25, I’m thinking that for relations without an explicit schema, we could leverage search_path to resolve them. That said, adopting this approach would likely involve significant modifications to the binder module. I’d appreciate your thoughts on whether this direction makes sense.

**Comment by chenzl25** [comment]
There are other 2 PR: https://github.com/risingwavelabs/risingwave/pull/24954 and https://github.com/risingwavelabs/risingwave/pull/24668#pullrequestreview-3895182053 working on the same issue. Could you take a look at these 2 PR and find any thing miss in your PR?

**Comment by chenzl25** [comment]
@Standing-Man the planner test failed, please use `./risedev do-apply-planner-test` to fix the test.

**Comment by Standing-Man** [comment]
> ./risedev do-apply-planner-test

Thanks a lot for your suggestion. I’ve only briefly looked at PR #24954 so far and haven’t fully reviewed the other PR yet. I’ll ping you once I finish the review.

**Comment by Standing-Man** [comment]
Wait a minute, I found an issue related to `binding schema`. 😸 
```
dev=> CREATE SCHEMA s1;
CREATE_SCHEMA
dev=> CREATE SCHEMA s2;
CREATE_SCHEMA
dev=> CREATE TABLE s1.a(id int, x int);
CREATE_TABLE
dev=> CREATE TABLE s2.a(id int, y int);
CREATE_TABLE
```
The output should be
```
dev=> SELECT a.x FROM s1.a, s2.a;
ERROR:  table reference "a" is ambiguous
LINE 1: SELECT a.x FROM s1.a, s2.a;
                           ^
```
but the current output is
```
dev=> SELECT a.x FROM s1.a, s2.a;
 x 
---
(0 rows)
```

**Comment by chenzl25** [comment]
> Wait a minute, I found an issue related to `binding schema`. 😸

Ah. Good catch.

File: src/frontend/src/binder/bind_context.rs [hunk 1]
```diff
@@ -300,24 +338,92 @@ impl BindContext {
         }
     }
 
+    /// Resolve a qualified column reference (`table.column` or `schema.table.column`)
+    /// to one concrete column index in the current bind scope.
+    ///
+    /// This function intentionally uses a two-step strategy:
+    /// 1. Resolve relation first (`resolve_relation_range`), including ambiguity checks.
+    /// 2. Resolve column inside that unique relation range (`resolve_column_in_range`).
```
Comment (Standing-Man) [inline src/frontend/src/binder/bind_context.rs:346]: Hi @chenzl25, In the new commit, I enhanced the checks in `get_index_with_table_name`. It first filters and validates based on the relation, and then performs additional checks using both the relation and the column.

Currently, `bind_catalog_relation_by_name` uses the user-provided schema name during binding instead of resolving it via `search_path`. I will fixed in a future PR.

**Comment by Standing-Man** [comment]
Hi @chenzl25, could you help trigger the remaining workflows?

**Comment by chenzl25** [comment]
> Hi @chenzl25, could you help trigger the remaining workflows?

Thanks for your contribution!

**Comment by Standing-Man** [comment]
> Thanks for your contribution!

could you help trigger the remaining workflows? Please let me know if there’s anything else I should fix for CI. Thanks! 🤣

**Comment by chenzl25** [comment]
> could you help trigger the remaining workflows? Please let me know if there’s anything else I should fix for CI. Thanks! 🤣

Done. I think it would be merged soon.

**Comment by Standing-Man** [comment]
Hi @chenzl25, Thank you very much for your review! I'm wondering why some workflows in the repository need to be triggered by maintainers.

**Comment by chenzl25** [comment]
> Thank you very much for your review! I'm wondering why some workflows in the repository need to be triggered by maintainers.

I think @cyliu0 might have more context. Probably it is related to the recent AI Agent generated PRs which would cause additional CI cost?

**Comment by Standing-Man** [comment]
> I think @cyliu0 might have more context. Probably it is related to the recent AI Agent generated PRs which would cause additional CI cost?

Thanks for the clarification.
