### PR TITLE
fix(frontend): ensure implicit cast to boolean in required expressions

### LINKED ISSUE #7311: feat(sqlsmith): Generate null for scalar values
Bugs:
- [ ] https://github.com/risingwavelabs/risingwave/issues/7312

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- Implicit CAST to `BOOLEAN` for `WHERE`, `CASE WHEN`, `HAVING`, `FILTER`, `current_schemas`.
- Misc: Add gen null for sqlsmith.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)

Closes https://github.com/risingwavelabs/risingwave/issues/7312
Closes #7311

### CODE REVIEW

File: src/frontend/src/binder/expr/function.rs [hunk 1]
```diff
@@ -201,16 +201,20 @@ impl Binder {
...
-                let ExprImpl::Literal(literal) = &inputs[0] else {
+                let input = inputs
+                    .pop()
+                    .unwrap()
+                    .enforce_bool_clause("current_schemas")
+                    .map_err(|_| no_match_err)?;
+
+                println!("input: {:?}", input);
+                let ExprImpl::Literal(literal) = &input else {
                     return Err(ErrorCode::NotImplemented(
```
Comment (kwannoel) [inline src/frontend/src/binder/expr/function.rs:218]: We may support this in some other PR. For now just fix implicit cast for `current_schemas`.

If this should be easy fix, feel free to suggest.

File: src/frontend/planner_test/tests/testdata/cast.yaml [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+    | └─BatchFilter { predicate: 'y':Varchar::Boolean }
+    |   └─BatchScan { table: t1, columns: [t1.v1], distribution: SomeShard }
+    └─BatchExchange { order: [], dist: Single }
+      └─BatchFilter { predicate: 'y':Varchar::Boolean }
+        └─BatchScan { table: t2, columns: [], distribution: SomeShard }
+- name: current_schemas (current_schemas(VARCHAR))
+  sql: |
+    select current_schemas('y');
+  binder_error: |-
+    Feature is not yet implemented: Only boolean literals are supported in `current_schemas`.
```
Comment (kwannoel) [inline src/frontend/planner_test/tests/testdata/cast.yaml:80]: See: https://github.com/risingwavelabs/risingwave/pull/7325/files#r1067114884

File: src/frontend/planner_test/tests/testdata/cast.yaml [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+    └─BatchFilter { predicate: null:Boolean }
+      └─BatchValues { rows: [[]] }
+- name: implicit cast boolean (CASE NULL)
+  sql: |
+    select case when NULL then 1 end;
+  batch_plan: |
+    BatchProject { exprs: [Case(null:Boolean, 1:Int32)] }
+    └─BatchValues { rows: [[]] }
+- name: implicit cast boolean (JOIN ON NULL)
+  sql: "create table t1(v1 int); \ncreate table t2(v1 int); \nselect t1.v1 from t1 join t2 on NULL;\n"
```
Comment (kwannoel) [inline src/frontend/planner_test/tests/testdata/cast.yaml:24]: Is there some way to avoid this being rewritten to this form?

Comment (kwannoel) [reply src/frontend/planner_test/tests/testdata/cast.yaml]: Just edited directly. No reformat after run `do-apply-planner-test` again. I guess it doesn't edit if output is as expected.

File: src/frontend/src/binder/expr/function.rs (hunk 1 above)
Comment (xiangjinwu) [reply src/frontend/src/binder/expr/function.rs:217]: This will be solved once we generalize another place from handling `null` to `unknown` types: #7320

File: src/frontend/planner_test/tests/testdata/cast.yaml (hunk 2 above)
Comment (xiangjinwu) [reply src/frontend/planner_test/tests/testdata/cast.yaml:86]: This will be solved once we generalize another place from handling `null` to `unknown` types: #7320

File: src/frontend/planner_test/tests/testdata/cast.yaml (hunk 3 above)
Comment (xiangjinwu) [reply src/frontend/planner_test/tests/testdata/cast.yaml]: IIRC it is due to the trailing space before `\n`.

File: src/tests/sqlsmith/src/sql_gen/scalar.rs [hunk 4]
```diff
@@ -22,12 +22,29 @@ use risingwave_common::types::DataType;
...
         use DataType as T;
-        // TODO: chance to gen null for scalar.
+        // ENABLE: https://github.com/risingwavelabs/risingwave/issues/5826
+        let typ = match typ {
+            T::Timestamptz => &T::Timestamp,
+            _ => typ,
+        };
+        // NOTE(kwannoel): Since this generates many invalid queries,
+        // its probability should be set to low, e.g. 0.02.
+        // ENABLE(kwannoel): Tracking issue: <https://github.com/risingwavelabs/risingwave/issues/7327>
```
Comment (kwannoel) [inline src/tests/sqlsmith/src/sql_gen/scalar.rs:38]:
```suggestion
        // ENABLE: https://github.com/risingwavelabs/risingwave/issues/7327
```

**Review by xiangjinwu — APPROVED** [review]
