### PR TITLE
fix(optimizer):  do not push temporal filter predicate passing the temporal join

### LINKED ISSUE #13412: bug: do not push temporal filter predicate passing the temporal join
```SQL
create table stream(id1 int, a1 int, b1 int, v1 timestamp with time zone) APPEND ONLY;
create table version(id2 int, a2 int, b2 int, primary key (id2));
explain create materialized view temporal_join_mv as select id1, a1, id2, v1 from stream left join version FOR SYSTEM_TIME AS OF PROCTIME() on id1 = id2 where v1 > now();
ERROR:  QueryError

Caused by:
  Not supported: Temporal join requires an append-only left input
HINT: Please ensure your left input is append-only
```

explain trace 
```
 Begin:
 
 LogicalProject { exprs: [stream.id1, stream.a1, version.id2, stream.v1] }
 └─LogicalFilter { predicate: (stream.v1 > Now) }
   └─LogicalJoin { type: LeftOuter, on: (stream.id1 = version.id2) }
     ├─LogicalScan { table: stream, columns: [id1, a1, b1, v1, _row_id] }
     └─LogicalScan { table: version, columns: [id2, a2, b2] }
 
 Common Sub-plan Sharing:
 
 LogicalProject { exprs: [stream.id1, stream.a1, version.id2, stream.v1] }
 └─LogicalFilter { predicate: (stream.v1 > Now) }
   └─LogicalJoin { type: LeftOuter, on: (stream.id1 = version.id2) }
     ├─LogicalScan { table: stream, columns: [id1, a1, b1, v1, _row_id] }
     └─LogicalScan { table: version, columns: [id2, a2, b2] }
 
 Predicate Push Down:
 
 LogicalProject { exprs: [stream.id1, stream.a1, version.id2, stream.v1] }
 └─LogicalJoin { type: LeftOuter, on: (stream.id1 = version.id2) }
   ├─LogicalFilter { predicate: (stream.v1 > Now) }
   │ └─LogicalScan { table: stream, columns: [id1, a1, b1, v1, _row_id] }
   └─LogicalScan { table: version, columns: [id2, a2, b2] }
 
```

### PR DESCRIPTION
**Pull request by st1page**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #13412 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/logical_join.rs [hunk 1]
```diff
@@ -188,56 +188,6 @@ impl LogicalJoin {
         self.output_indices() == &(0..self.internal_column_num()).collect_vec()
     }
 
-    /// Try to split and pushdown `predicate` into a join's left/right child or the on clause.
```
Comment (st1page) [inline src/frontend/src/optimizer/plan_node/logical_join.rs:191]: no caller call it and it is a dead code before this PR.

File: src/frontend/planner_test/tests/testdata/input/temporal_filter.yaml [hunk 2]
```diff
@@ -3,71 +3,78 @@
...
-  - stream_plan
+    - stream_plan
 - name: Temporal filter in on clause for right join's right side
   sql: |
     create table t1 (a int, ta timestamp with time zone);
     create table t2 (b int, tb timestamp with time zone);
     select * from t1 right join t2 on a = b AND tb < now() - interval '1 hour' and tb >= now() - interval '2 hour';
   expected_outputs:
-  - stream_error
+    - stream_error
```
Comment (chenzl25) [inline src/frontend/planner_test/tests/testdata/input/temporal_filter.yaml:73]: All planner tests are without indents, so I think we can keep the same style?

**Review by chenzl25 — APPROVED** [review]
LGTM
