### PR TITLE
fix: misuse of props and options in `CREATE SOURCE`

### LINKED ISSUE #13365: bug: `schema.registry.username` and `schema.registry.password` are not correctly consumed
### Describe the bug

described in https://github.com/risingwavelabs/risingwave/pull/13362

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rossil2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Resolve #13365 #13367.

Properties in `WITH` clause and options in `FORMAT ... ENCODE ...` are misused. Options are merged into props, and parameters defined in options will be further looked up within props. This may result in the following consequences:

1. Duplicate keys in both options and props
2. Users fill parameters in wrong clause and get no error/warning
3. Checks of consuming props/options can be corrupted (see #13362 #13654)

Here are some keys that supposed to be in the options instead of props:
* schema.* (except for schema.name in db_cdc)
* message
* key.message
* without_header
* delimiter

Also found a misuse in the kafka doc: https://docs.risingwave.com/docs/current/ingest-from-kafka/#connector-parameters.
`schema.registry.username` and `schema.registry.password` should be defined in `ENCODE ... FORMAT`. cc @neverchanje.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/frontend/src/catalog/source_catalog.rs [hunk 1]
```diff
@@ -93,7 +95,8 @@ impl From<&PbSource> for SourceCatalog {
             .into_iter()
             .map(Into::into)
             .collect();
-        let with_options = WithOptions::new(prost.properties.clone());
+        let properties = WithOptions::new(prost.properties.clone()).into_inner();
+        let options = WithOptions::new(prost.options.clone()).into_inner();
```
Comment (xxchan) [inline src/frontend/src/catalog/source_catalog.rs:99]: We might need to rename the type alias now... 🥵

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: Besides, `properties` and `options` are not meaningful names. Can we change them to sth like `with_options` and `encode_format_options`/`row_options`?

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: How about `with_properties` and `row_options`?

File: src/frontend/src/handler/create_source.rs [hunk 2]
```diff
@@ -119,8 +128,11 @@ fn json_schema_infer_use_schema_registry(schema_config: &Option<(AstString, bool
 async fn extract_avro_table_schema(
     info: &StreamSourceInfo,
     with_properties: &HashMap<String, String>,
+    row_options: &mut BTreeMap<String, String>,
```
[the remark this answers is not in the document]
Comment (Rossil2012) [reply src/frontend/src/handler/create_source.rs:131]: We use &mut for `row_options` because in the `bind_columns_from_source` function fields of options are consumed (i.e. row_options.remove(&key)). And we will check `options.is_empty()` in the end.
https://github.com/risingwavelabs/risingwave/blob/main/src/frontend/src/handler/create_source.rs#L572-L584

**Comment by Rossil2012** [comment]
> Can you explain a little about what's changed in the code?

1. In `create_source` and `create_table` handler, keys are identified to be used in props and options according to docs.
2. Add `options` field in PbSource
3. Add column for `options` field in sql meta store.

> Whether is the separated `options` used

The options are separated and persisted in meta, but are not further used for now. But as @tabVersion inform that there is a plan to support `alter source`, the separated options might be useful in the future. 

> * Whether and how is backwards compatibility achived

There is no convenient or absolutely correct way to do this. I just carefully go through the code from frontend to meta and check the docs to check if the key is supposed to be in options other than props. And to ensure options are consumed correctly.

File: src/frontend/src/catalog/source_catalog.rs (hunk 1 above)
Comment (tabVersion) [reply src/frontend/src/catalog/source_catalog.rs:99]: the most of fields in `option` are related to parser behavior, I prefer `encode_option` or `parser_option`

Comment (xiangjinwu) [reply src/frontend/src/catalog/source_catalog.rs:99]: I have been calling them `format options` for sink 😂

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: Let's start a vote for `options`. Please use 👍 to pick the names you think is acceptable.

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: row_options

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: format_options

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: encode_format_options

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: parser_options

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: Wait a minute, the syntax seems to be `FORMAT ... ENCODE ... (...)`, so at least it should be `format_encode_options` 🤣

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: From the syntax, the options indeed look like it's for `ENCODE` 🤔.

From the parser's definition it seems to be called `row_options`, so I guess this is what it should be like when it was designed (and not only for `ENCODE`).  So might worth asking @st1page what's the best name for it.

https://github.com/risingwavelabs/risingwave/blob/b5c3f5dfd091d14184f06c5d93108604fcb1f333/src/sqlparser/src/ast/statement.rs#L338-L342



> the most of fields in option are related to parser behavior, I prefer `encode_option` or `parser_option`

I'm wondering whether `parser_options` will be confusing to users. We need to consider this in the error messages (maybe also syntax reference, but currently it also doesn't have a name)

Comment (BugenZhao) [inline src/frontend/src/catalog/source_catalog.rs:99]: BTW, should we consider backward compatibility here?

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: For now, legacy codes that try to find keys of `format_encode_options` in `with_properties` are identified and corrected. So unmerging `format_encode_options` from `with_properties` will not result in key-not-found-like errors. Is this the `backward compatibility` you suggested?

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: IMO the most important thing is: already created source can still work. It seems compute node doesn't use `format_encode_options` at all and thus not broken? (I'm not very sure. Correct me if I'm wrong.)

Besides is the semantics change on the frontend. I'm still not sure whether sth is changed (i.e., can work previously, but can't work now, and vice versa). But actually that's acceptable to me...

Glad to hear others' thoughts about detailed backward compatibility concerns. @BugenZhao zkss

Comment (st1page) [reply src/frontend/src/catalog/source_catalog.rs:99]: I think it is the historical reason...  `encode_option` LGTM. Btw, we might need some option in the `KEY ENCODE` in the future. c.c. @tabVersion 
```SQL
format upsert 
encode avro (
  schema.registry = 'http://message_queue:8081/',
  schema.registry.name.strategy = 'typo')
key encode avro (
  schema.registry = 'http://message_queue:8081/',
  schema.registry.name.strategy = 'typo')
)
```

Comment (BugenZhao) [reply src/frontend/src/catalog/source_catalog.rs:99]: > already created source can still work.

Yes!

> It seems compute node doesn't use `format_encode_options` at all and thus not broken?

Also the meta service part: does it handle the cases that the new fields do not exist?

TBH, I'm not that familiar with the connector part. 🤣 Practice is the sole criterion for testing truth.

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: I just added a backwards-compat test for invalid WITH options #13824. Can we or do we need to add similar stuff for this PR?

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: > IMO the most important thing is: already created source can still work. 

Do you mean that, for example, a user creates a source using RW 1.4, and then upgrades to RW 1.5. So codes in RW 1.5 should recognize it as legacy source and try to find option keys in properties. Is this hot-update issue you concerned?

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: Yes

Comment (Rossil2012) [reply src/frontend/src/catalog/source_catalog.rs:99]: Got it. We do need to add more codes to handle this issue.

Comment (xxchan) [reply src/frontend/src/catalog/source_catalog.rs:99]: FYI 😇 this is my solution for rejecting unknown WITH
 https://github.com/risingwavelabs/risingwave/commit/2e39b51e151b256d9007b2466d57647efabccbbd#diff-a80dd5cfb3d2b493a15182ad5c447741b10820fa16b8eea2719b9c0ae6f003a4R415-R418

**Comment by xxchan** [comment]
I don't think that's super *necessary* for now, because we don't have the need to "identify legacy source" (and use different code paths for them). We are just tolerating them. Basically, we are accepting a subset of inputs, instead of introducing fundamental new stuff.

Similar idea for stream plans was discussed before https://github.com/risingwavelabs/rfcs/pull/43 

I'm not sure whether it's worth adding a version regardless of the need. Glad to hear others' opinions.

**Comment by BugenZhao** [comment]
> I'm not sure whether it's worth adding a version regardless of the need, as a general design pattern. Glad to hear others' opinions.

Agree. I believe it's only necessary if there's a strict correctness issue.

File: src/frontend/src/utils/with_options.rs [hunk 3]
```diff
@@ -226,18 +226,10 @@ impl TryFrom<&Statement> for WithOptions {
...
-                        with_properties,
-                        source_schema,
-                        ..
+                        with_properties, ..
                     },
                 ..
-            } => {
-                let mut options = with_properties.0.clone();
-                if let CompatibleSourceSchema::V2(source_schema) = source_schema {
-                    options.extend_from_slice(source_schema.row_options());
```
Comment (xiangjinwu) [inline src/frontend/src/utils/with_options.rs:237]: Similar things are done for `create table` below. Did we forget to test that case?

File: src/frontend/src/handler/create_table.rs [hunk 4]
```diff
@@ -656,6 +664,7 @@ fn gen_table_plan_inner(
             .collect_vec(),
         pk_column_ids: pk_column_ids.iter().map(Into::into).collect_vec(),
         properties: with_options.into_inner().into_iter().collect(),
+        options: options.unwrap(),
```
Comment (xiangjinwu) [inline src/frontend/src/handler/create_table.rs:667]: The `unwrap` here always succeeds because it is inside `source_info.map`. In other words, existence of `source_info` guarantees existence of `options`. Shall we include `options` as part of `source_info`? Note that enum `format` and `row_encode` are also part of `source_info`.

File: src/frontend/src/catalog/source_catalog.rs (hunk 1 above)
Comment (tabVersion) [reply src/frontend/src/catalog/source_catalog.rs]: > I think it is the historical reason... format_encode_options LGTM.
> Btw, we might need some options in the KEY ENCODE in the future. 
+1 for `format_encode_options`
for KEY ENCODE, I think it is ok to add some fields in the options because the clause is optional in SQL and we don't expect it as strong as the value part.

File: src/frontend/src/handler/create_source.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (tabVersion) [reply src/frontend/src/handler/create_source.rs]: > The difference between the two's type might be confusing (especially mut). 

We hope to consume both configs here but it seems impossible for connector props. Let's keep `format_encode_options` safe from unknown fields.

File: src/connector/src/parser/mod.rs [hunk 5]
```diff
@@ -916,12 +920,14 @@ impl SpecificParserConfig {
                     config.topic = get_kafka_topic(props)?.clone();
                     config.client_config = SchemaRegistryAuth::from(props);
```
Comment (tabVersion) [inline src/connector/src/parser/mod.rs]: should here be `SchemaRegistryAuth::from(props, &mut options)`? We need both connector name and `format_encode_option` to build a schema registry client

File: src/connector/src/parser/mod.rs [hunk 6]
```diff
@@ -948,12 +954,14 @@ impl SpecificParserConfig {
...
```
Comment (tabVersion) [inline src/connector/src/parser/mod.rs]: ditto

File: src/connector/src/parser/mod.rs [hunk 7]
```diff
@@ -872,7 +872,11 @@ pub enum ProtocolProperties {
 
 impl SpecificParserConfig {
     // The validity of (format, encode) is ensured by `extract_format_encode`
-    pub fn new(info: &StreamSourceInfo, props: &HashMap<String, String>) -> Result<Self> {
+    pub fn new(
+        info: &StreamSourceInfo,
+        props: &HashMap<String, String>,
+        row_options: Option<&mut BTreeMap<String, String>>,
```
Comment (tabVersion) [inline src/connector/src/parser/mod.rs]: why wrap with an Option? I think we can always get the btreemap from the frontend

File: src/frontend/src/handler/create_source.rs [hunk 8]
```diff
@@ -1299,6 +1338,72 @@ pub mod tests {
...
+        connector = 'kinesis',
+        aws.region='user_test_topic',
+        endpoint='172.10.1.1:9090,172.10.1.2:9090',
+        aws.credentials.access_key_id = 'your_access_key',
+        aws.credentials.secret_access_key = 'your_secret_key'
+    )
+    FORMAT PLAIN ENCODE PROTOBUF (
+        message = '.test.TestRecord',
+        aws.credentials.access_key_id = 'your_access_key',
+        aws.credentials.secret_access_key = 'your_secret_key',
```
Comment (tabVersion) [inline src/frontend/src/handler/create_source.rs]: please give the assess keys and secret keys different value

File: src/frontend/src/handler/create_table.rs (hunk 4 above)
Comment (xiangjinwu) [reply src/frontend/src/handler/create_table.rs]: > > In other words, existence of source_info guarantees existence of options
> 
> I don't quite get how you get the conclusion.

If this claim is not true in some cases, the `unwrap` would panic and should be replaced by proper error handling.

**Comment by Rossil2012** [comment]
It seems that changing the name to with_properties breaks the dashboard🤣 
```typescript
export interface Relation {
  id: number
  name: string
  owner: number
  columns: (ColumnCatalog | Field)[]
  properties: { [key: string]: string }
}
export async function getRelations() {
  let relations = _.concat<Relation>(
    await getMaterializedViews(),
    await getTables(),
    await getIndexes(),
    await getSinks(),
    await getSources()
  )
  relations = sortBy(relations, (x) => x.id)
  return relations
}
```
The type check requires relations' proto to have the same field "properties".

There is a possible workaround:
```typescript
type SourceWrap = Source & {
  properties: { [key: string]: string }
}

export async function getSources() {
  let sourceList: SourceWrap[] = (await api.get("/api/sources")).map(
    Source.fromJSON
  ).map((src) => Object.defineProperty(src, 'properties', {
    get: function() {
      return this.with_properties
    },
    set: function(value) {
      this.with_properties = value
    }
  }))
  sourceList = sortBy(sourceList, (x) => x.id)
  return sourceList
}
```
or we rename all `properties` to `with_properties` in photo.

File: src/frontend/src/handler/create_table.rs (hunk 4 above)
Comment (Rossil2012) [reply src/frontend/src/handler/create_table.rs]: >  Shall we include options as part of source_info?

Done.

**Comment by Rossil2012** [comment]
Renaming implicit names like `properties` and `options` to `with_properties` and `format_encode_options` is done. 

However, the name of this wrapper should be changed too as it's now useful for `WITH` and `FORMAT ENCODE` both. Any suggestion of a new name?
```rust
/// Options or properties extracted from the `WITH` clause of DDLs.
#[derive(Default, Clone, Debug, PartialEq, Eq, Hash)]
pub struct WithOptions {
    inner: BTreeMap<String, String>,
}
```

**Comment by xxchan** [comment]
For me, I think the wrapper type isn't actually very useful. It's also not used widely, but just in some places.

e.g., this is a funny usage 

image

another one
image

So maybe we can totally get rid of it.

Just my rough personal feeling. lol

**Comment by tabVersion** [comment]
fix the doc mismatch: https://github.com/risingwavelabs/risingwave-docs/pull/1627

File: src/meta/src/manager/catalog/database.rs [hunk 9]
```diff
@@ -101,11 +102,32 @@ impl DatabaseManager {
...
         );
         let schemas = BTreeMap::from_iter(schemas.into_iter().map(|schema| (schema.id, schema)));
-        let sources = BTreeMap::from_iter(sources.into_iter().map(|source| {
+        let sources = BTreeMap::from_iter(sources.into_iter().map(|mut source| {
             // TODO(weili): wait for yezizp to refactor ref cnt
             if let Some(connection_id) = source.connection_id {
                 *relation_ref_count.entry(connection_id).or_default() += 1;
             }
+
+            // This block here is for maintaining backward compatibility with older source formats when `format_encode_options` is
```
Comment (yezizp2012) [inline src/meta/src/manager/catalog/database.rs:111]: How about introducing a separate function in catalog manager to rewrite in-compatible sources? Then you can use `commit_meta` instead of writing kv directly with a low level api.

File: proto/catalog.proto [hunk 10]
```diff
@@ -81,7 +83,7 @@ message Source {
   // specify a primary key, the vector will be empty.
   repeated int32 pk_column_ids = 7;
   // Properties specified by the user in WITH clause.
-  map<string, string> properties = 8;
+  map<string, string> with_properties = 8;
```
Comment (tabVersion) [inline proto/catalog.proto:86]: is there compatibility issue?

File: src/connector/src/source/mod.rs [hunk 11]
```diff
@@ -42,3 +42,15 @@ pub use mock_external_table::MockExternalTableReader;
 pub use crate::source::filesystem::{S3_CONNECTOR, S3_V2_CONNECTOR};
 pub use crate::source::nexmark::NEXMARK_CONNECTOR;
 pub use crate::source::pulsar::PULSAR_CONNECTOR;
+
+pub fn is_key_belong_to_format_encode_options(key: &str) -> bool {
+    const PREFIXES: &[&str] = &[
```
Comment (tabVersion) [inline src/connector/src/source/mod.rs:47]: `aws.credentials.*` are not part of the options?

**Review by tabVersion — APPROVED** [review]
generally LGTM, good work!

File: proto/catalog.proto (hunk 10 above)
Comment (fuyufjh) [reply proto/catalog.proto:86]: No. Renaming is always okay.

File: dashboard/pages/api/streaming.ts [hunk 12]
```diff
@@ -103,10 +103,23 @@ export async function getSinks() {
...
+    .map((src: Source) =>
+      Object.defineProperty(src, "properties", {
+        get: function () {
+          return this.with_properties
+        },
+        set: function (value) {
+          this.with_properties = value
+        },
+      })
+    )
```
Comment (fuyufjh) [inline dashboard/pages/api/streaming.ts:122]: Why not just renaming the occurrence of `properties` to `with_properties` in the dashboard code?

**Review by fuyufjh — COMMENTED** [review]
The rest LGTM

File: src/connector/src/source/mod.rs (hunk 11 above)
Comment (Rossil2012) [reply src/connector/src/source/mod.rs:47]: `aws.credentials.*` can also exist in `with_properties`.

File: dashboard/pages/api/streaming.ts (hunk 12 above)
Comment (Rossil2012) [reply dashboard/pages/api/streaming.ts:122]: There is type checking that `getSources` returns `Relation`, which requires field `properties`.
https://github.com/risingwavelabs/risingwave/blob/349d36fc2c76482ff2d653f1c0377193b57a1e7f/dashboard/pages/api/streaming.ts#L64-L74
https://github.com/risingwavelabs/risingwave/blob/349d36fc2c76482ff2d653f1c0377193b57a1e7f/dashboard/pages/api/streaming.ts#L37-L43

By delegating `with_properties` to `properties` and use `SourceWrap` as type wrapper, it keeps the `Relation` abstract of table/source/.. with minimal modification.

Comment (Rossil2012) [reply dashboard/pages/api/streaming.ts:122]: Since `src.with_properties` stores an `Object` and assignment of `Object` is actually "reference assignment", if all accesses are `src.with_properties.xxx`, we can simply use `src.properties = src.with_properties` rather than setter and getter. I will check it later.

File: src/connector/src/source/mod.rs (hunk 11 above)
Comment (xiangjinwu) [reply src/connector/src/source/mod.rs:47]: But for compatibility, they may also need to be copied (back) from `with_properties` to `format_encode_options` for a legacy source. Can we test this case in some way?

Comment (Rossil2012) [reply src/connector/src/source/mod.rs:47]: After validation by printing `SpecificParserConfig`. `format_encode_options` actually accept flatten keys like region/endpoint/.. as aws config. So we need to move these flatten keys instead of `aws.credentials.*`.
```rust
#[derive(Deserialize, Debug, Clone, WithOptions)]
pub struct AwsAuthProps {
    pub region: Option<String>,
    #[serde(alias = "endpoint_url")]
    pub endpoint: Option<String>,
    pub access_key: Option<String>,
    pub secret_key: Option<String>,
    pub session_token: Option<String>,
    pub arn: Option<String>,
    /// This field was added for kinesis. Not sure if it's useful for other connectors.
    /// Please ignore it in the documentation for now.
    pub external_id: Option<String>,
    pub profile: Option<String>,
}
```

File: src/connector/src/source/mod.rs [hunk 13]
```diff
@@ -42,3 +42,25 @@ pub use mock_external_table::MockExternalTableReader;
...
+        "endpoint_url",
+        "access_key",
+        "secret_key",
+        "session_token",
+        "arn",
+        "external_id",
+        "profile",
+    ];
+    PREFIXES.iter().any(|prefix| key.starts_with(prefix))
+        || (key == "endpoint" && !connector.eq_ignore_ascii_case(KINESIS_CONNECTOR))
```
Comment (Rossil2012) [inline src/connector/src/source/mod.rs:65]: `endpoint` is also found used (and only used) in Kinesis properties, so we move `endpoint` to `format_encode_options` if the connector is not Kinesis.
```rust
pub struct KinesisCommon {
    #[serde(rename = "stream", alias = "kinesis.stream.name")]
    pub stream_name: String,
    #[serde(rename = "aws.region", alias = "kinesis.stream.region")]
    pub stream_region: String,
    #[serde(rename = "endpoint", alias = "kinesis.endpoint")]
    pub endpoint: Option<String>,
```

File: dashboard/pages/api/streaming.ts (hunk 12 above)
Comment (Rossil2012) [reply dashboard/pages/api/streaming.ts]: > Why not just renaming the occurrence of properties to with_properties in the dashboard code?

Done.

File: src/connector/src/source/mod.rs (hunk 13 above)
Comment (xiangjinwu) [reply src/connector/src/source/mod.rs:65]: * I have no experience on aws config names used for connecting to kinesis (`endpoint` / `kinesis.endpoint`) vs names used for reading schema definition from s3 (`endpoint_url`). Would rely on @tabVersion with more experience to make sure the names are listed correctly, **and with proper tests**.
* My previous comment used the word **copy** instead of **move**. I am not sure if some names in legacy `with_properties` are actually used by both `with` and `format encode`. Moving them away from `with_properties` may break things. Again, whether this is an real issue depends on the meaning / usage of specific names, which has been obscure for a long time every time we talk about `with properties`. Just bringing the idea up and would rely on your judgement.

**Review by xiangjinwu — COMMENTED** [review]
Rest LGTM.

File: src/connector/src/source/mod.rs (hunk 13 above)
Comment (xiangjinwu) [reply src/connector/src/source/mod.rs:65]: Studied [serde](https://serde.rs/field-attrs.html) `rename` and `alias`, and it turns out the only name shared by both is `endpoint`, which would not be moved in the case of kinesis. **And existing kinesis connector are not using `format encode` from s3. (or we need to _copy_ `endpoint` even when it is kinesis)**

All other names for reading `format encode` from s3 has already been listed above properly.

Just for clarity, this is a concrete example of the current situation:
```
create [source | table] t with (
  connector = 'kinesis',
  stream = 't',
  aws.region = 'r0',
  endpoint = 'e0',
  aws.credentials.access_key_id = 'ak0',
  aws.credentials.secret_access_key = 'sk0'
) format plain encode avro (
  schema.location = 's3://foo/bar',
  region = 'r1',
  access_key = 'ak1',
  secret_key = 'sk1'
);
```

**Review by xiangjinwu — APPROVED** [review]

**Comment by xiangjinwu** [comment]
Built an image with `IMAGE_TAG=pr-13762-fix-prop-option-misuse`
https://buildkite.com/risingwavelabs/docker/builds/14892
Then ran integration tests with `RW_IMAGE_TAG=pr-13762-fix-prop-option-misuse`
https://buildkite.com/risingwavelabs/integration-tests/builds/514#018c6776-3b56-4406-b449-55cab832dae0
