### PR TITLE
fix(memory-manager): should not use prev_memory_stats.streaming_memory_usage

### LINKED ISSUE #9383: bug(memory-manager): should not use prev_memory_stats.streaming_memory_usage
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/8a494e54557737128879664f61b9fbb1aab8294a/src/compute/src/memory_management/policy.rs#L207-L209

Here `prev_memory_stats.streaming_memory_usage` is always zero, because it was set from `stream_manager.total_mem_usage()`

https://github.com/risingwavelabs/risingwave/blob/8a494e54557737128879664f61b9fbb1aab8294a/src/compute/src/memory_management/policy.rs#L169

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #9383.

This PR also reverts #8253 and #8475 but keeps the `trait MemoryControlPolicy` (renamed to "MemoryControl") for possible future usage.

The reason of that is, we are not actually ready for such "MemoryControlPolicy" right now. Back to that point when we wrote #8253 and #8475, we didn't realize that these policy cannot work at all without a better memory estimation.

After that, when #8827 merged, things become worse. Code of #8827 mixed up 2 things: 
- the **machanism of measuring** current memory usage 
- and the **policy** about how the memory should be used

... which made that part of code become quite error-prone. I think #9383 is one of its result.

(As you may see, I renamed `StreamingOnlyPolicy` to `JemallocMemoryControl` to emphasize it is a **machanism of measuring** rather than **policy**)

In my mind, This is a typical case of over-design or premature design. Thus, I strongly tend to remove these unused code and keep it simple and clear. We can add them back when memory estimation is ready, at which time we should get rid of `JemallocMemoryControl` and add back "StreamingOnlyPolicy" and "StreamingBatchPolicy".

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation
 My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/risedevtool/src/task/compute_node_service.rs [hunk 1]
```diff
@@ -61,11 +61,7 @@ impl ComputeNodeService {
             .arg("--parallelism")
             .arg(&config.parallelism.to_string())
             .arg("--total-memory-bytes")
-            .arg(&config.total_memory_bytes.to_string())
-            .arg("--memory-control-policy")
-            .arg(&config.memory_control_policy)
-            .arg("--streaming-memory-proportion")
```
Comment (fuyufjh) [inline src/risedevtool/src/task/compute_node_service.rs:67]: Can you help to confirm these arguments are not used in cloud yet? @arkbriar

**Comment by fuyufjh** [comment]
Longevity test: https://buildkite.com/risingwave-test/longevity-kubebench/builds/272#0187ae32-d2b6-4b63-adbf-d42b1b610286

(Run on 3e39550. No actual changes except renaming and removing parameter since then)

File: src/compute/src/memory_management/policy.rs [hunk 2]
```diff
@@ -15,140 +15,46 @@
...
-    /// -`streaming_memory_proportion`.
-    streaming_memory_proportion: f64,
+/// `JemallocMemoryControl` is a memory control policy that uses jemalloc statistics to control. It
+/// assumes that most memory is used by streaming engine and does memory control over LRU watermark
+/// based on jemalloc statistics.
+#[derive(Debug)]
+pub struct JemallocMemoryControl {
+    threshold_graceful: usize,
+    threshold_aggressive: usize,
 }
```
Comment (xx01cyx) [inline src/compute/src/memory_management/policy.rs:31]: Not sure whether it's a good idea to put configuration values into a policy (sth. like concrete vs abstract).

**Review by xx01cyx — APPROVED** [review]
Rest LGTM

File: src/compute/src/memory_management/policy.rs (hunk 2 above)
Comment (fuyufjh) [reply src/compute/src/memory_management/policy.rs:31]: Emmmm I prefer this style a little bit, because these values belong to the policy's config in my mind, and besides, these values don't change in loops

**Comment by fuyufjh** [comment]
The longevity can run correctly. But sadly, the fluctuation is not solved.

After running NexMark (q4,q5,q7,q8) for 2 hours:

image

After running NexMark (q4,q5,q7,q8) for 15 hours:

image

**Comment by st1page** [comment]
> The longevity can run correctly. But sadly, the fluctuation is not completely solved.

This is not a big fluctuation as previously :thinking: And maybe the curve is not as smooth as we would like it to be under the preemptive memory allocation.

File: src/risedevtool/src/task/compute_node_service.rs (hunk 1 above)
Comment (arkbriar) [reply src/risedevtool/src/task/compute_node_service.rs:67]: AFAIK, neither the operator nor the cloud control plane use them.
