### PR TITLE
fix(source): report error when user do not specify all columns in order for nexmark

### LINKED ISSUE #8812: Bug: crash when the columns are not fully written in nexmark source
### Describe the bug

When columns of the nexmark source are not written completely, it will panic in [schema_check](https://github.com/risingwavelabs/risingwave/blob/a1d084d50ef845b1a566b9e6c5ab733c2ad40509/src/stream/src/executor/wrapper/schema_check.rs#L25)

If this is the expected behavior, please close this issue.

### To Reproduce

```
dev=> create table bid (auction INTEGER, bidder INTEGER, price INTEGER, "date_time" TIMESTAMP)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '12',
  nexmark.min.event.gap.in.ns = '100000'
) ;

```

then 

```
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 4800002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
stack backtrace:
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 3000002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 2D00002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'schema check failed on SourceExecutor 3F00002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")schema check failed on SourceExecutor 2900002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', thread '', src/stream/src/executor/wrapper/schema_check.rsrisingwave-streaming-actorsrc/stream/src/executor/wrapper/schema_check.rs:' panicked at ':48schema check failed on SourceExecutor 4500002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")48:', :29src/stream/src/executor/wrapper/schema_check.rs29

```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by waruto210**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- report error when user do not specify all columns in order for nexmark 
- close #8812

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~- [] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by idx0-dev — APPROVED** [review]

File: src/connector/src/source/nexmark/source/combined_event.rs [hunk 1]
```diff
@@ -66,6 +69,62 @@ pub fn new_combined_event(event: Event) -> CombinedEvent {
...
+                .field_names
+                .into_iter()
+                .zip_eq_fast(struct_type.fields)
+                .collect_vec()
+        }
+    };
+
+    if let Some(row_id_index) = row_id_index {
+        // _row_id
+        fields.insert(row_id_index, ("_row_id".to_owned(), DataType::Serial));
```
Comment (BugenZhao) [inline src/connector/src/source/nexmark/source/combined_event.rs:122]: May use `row_id_column_desc` instead of hard-coding here.

File: e2e_test/nexmark/create_sources.slt.part [hunk 2]
```diff
@@ -32,6 +32,40 @@ CREATE SOURCE nexmark (
     nexmark.min.event.gap.in.ns = '100'
 );
 
+statement error The shema of the nexmark source must specify all columns in order
```
Comment (BugenZhao) [inline e2e_test/nexmark/create_sources.slt.part:35]: Seems not a good idea to put it into this file. 🥵 What about introducing a new `bug_fixes`?

File: src/connector/src/source/nexmark/source/combined_event.rs (hunk 1 above)
Comment (waruto210) [reply src/connector/src/source/nexmark/source/combined_event.rs:122]: fix by using `row_id_column_name`

File: e2e_test/nexmark/create_sources.slt.part (hunk 2 above)
Comment (waruto210) [reply e2e_test/nexmark/create_sources.slt.part]: introduced a new file.
