### PR TITLE
fix(expr): parse `timestamptz` without seconds but with offset

### LINKED ISSUE #12075: bug(expr): explicit timezone offset may be ignored when parsing `timestamptz`
### Describe the bug

We can parse `2023-11-05 01:40:00-07:00` correctly. But when the seconds part is missing `2023-11-05 01:40-07:00`, the offset would be ignored as well resulting in only `2023-11-05 01:40` interpreted in implicit session time zone.

### Error message/log

Silently produce a wrong value without errors. See repro below:

### To Reproduce

RisingWave:
```
dev=> select '2023-11-05 01:40-07:00'::timestamptz;
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.

        timestamptz        
---------------------------
 2023-11-05 01:40:00+00:00
(1 row)

dev=> select '2023-11-05 01:40-08:00'::timestamptz;
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.

        timestamptz        
---------------------------
 2023-11-05 01:40:00+00:00
(1 row)

dev=> select '2023-11-05 01:40:00-07:00'::timestamptz;
        timestamptz        
---------------------------
 2023-11-05 08:40:00+00:00
(1 row)

dev=> select '2023-11-05 01:40:00-08:00'::timestamptz;
        timestamptz        
---------------------------
 2023-11-05 09:40:00+00:00
(1 row)
```

### Expected behavior

PostgreSQL:
```
test=# select '2023-11-05 01:40-07:00'::timestamptz;
      timestamptz       
------------------------
 2023-11-05 08:40:00+00
(1 row)

test=# select '2023-11-05 01:40-08:00'::timestamptz;
      timestamptz       
------------------------
 2023-11-05 09:40:00+00
(1 row)

test=# select '2023-11-05 01:40:00-07:00'::timestamptz;
      timestamptz       
------------------------
 2023-11-05 08:40:00+00
(1 row)

test=# select '2023-11-05 01:40:00-08:00'::timestamptz;
      timestamptz       
------------------------
 2023-11-05 09:40:00+00
(1 row)
```

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #12075

It was actually caused by an unexpected combination:
* Parse as `chrono::DateTime<Utc>`, which requires both seconds and offset.
* When that fails, we fallback to parse as naive `timestamp`, which internally uses `speedate::DateTime` that allows either seconds or offset to be present or absent. But the offset is always ignored.

So the fix contains two parts:
* When parsing naive `timestamp`, report error rather than ignore it silently when an offset is present.
* When parsing `timestamptz`, also use `speedate::DateTime` rather than `chrono::DateTime<Utc>`.

Note that PostgreSQL actually ignores offset silently when parsing naive `timestamp`, leading to `'2006-01-01 15:04:05-07:00'::timestamp = '2006-01-01 15:04:05Z'::timestamp`. We'd rather reject this query until explicitly requested to be compatible with this.

Also replaced `parse_str` with `parse_str_rfc3339`. The former unintentionally allows `select '0'::date;` when we switch from `chrono` to `speedate` for parsing.

Limitation:
* `speedate::DateTime` cannot handle year < 1600 when converting to seconds since unix epoch. We could implement our own conversion manually but it adds little value.
* `FromStr` (rather than cast from varchar) of naive date / time / timestamp is still using `chrono` rather than `speedate`. This will be refactored later.

|                            | description         | chrono | speedate |
|----------------------------|---------------------|--------|----------|
| 2006-01-02T15:04:05-07:00  | ISO8601             | Ok     | Ok       |
| 2006-01-02 15:04:05-07:00  | T replaced by space | Ok     | Ok       |
| 2006-01-02 15:04-07:00     | without seconds     | Err    | Ok       |
| 2006-01-02 15:04:05 -07:00 | space before offset | Ok     | Err      |

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [x] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/connector/src/parser/debezium/simd_json_parser.rs [hunk 1]
```diff
@@ -298,7 +298,7 @@ mod tests {
                 SourceColumnDesc::simple("O_DATE", DataType::Date, ColumnId::from(8)),
                 SourceColumnDesc::simple("O_TIME", DataType::Time, ColumnId::from(9)),
                 SourceColumnDesc::simple("O_DATETIME", DataType::Timestamp, ColumnId::from(10)),
-                SourceColumnDesc::simple("O_TIMESTAMP", DataType::Timestamp, ColumnId::from(11)),
+                SourceColumnDesc::simple("O_TIMESTAMP", DataType::Timestamptz, ColumnId::from(11)),
```
Comment (xiangjinwu) [inline src/connector/src/parser/debezium/simd_json_parser.rs:301]: When tightening the parsing of naive `timestamp`, I also found this typing issue in debezium mysql source: `timestamp` in MySQL should be mapped to `timestamptz` in PostgreSQL. Are there any other places I need to fix in addition to the tests here? @StrikeW

Comment (StrikeW) [reply src/connector/src/parser/debezium/simd_json_parser.rs:301]: I will add a validate check in mysql-cdc to enforce `timestamp` map to `timestampz` after this pr merged.

Comment (StrikeW) [reply src/connector/src/parser/debezium/simd_json_parser.rs:301]: Would you mind taking a look at this part? Not sure whether we need to modify here also.
https://github.com/risingwavelabs/risingwave/blob/9ccdbe368ace5a3ada11a8c82952b24a0104f6d5/src/connector/src/parser/mysql.rs#L74-L81

Comment (xiangjinwu) [reply src/connector/src/parser/debezium/simd_json_parser.rs:301]: Thanks for the info!
* For mysql-cdc validation, it may be easier to be in the same PR if we want to cherry pick it into 1.2.x. Alternatively, I can also make this PR less defensive to not reject such typing mistake during parser until 1.3. But we add the checking in mysql-cdc in 1.2 first.
* I can confirm this `mysql_async` mapping need no change, because the data for `datetime` and `timestamp` look exactly the same. This is different from [debezium](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-temporal-types:~:text=DATETIME%20with%20a,37%3A03Z.). However, we also lose the opportunity to do validation as in the debezium case. Furthermore the mysql client should be configured to set session timezone to utc. IIRC this is already done.

**Review by StrikeW — APPROVED** [review]
LGTM
