### PR TITLE
fix: migrate parameters of memory & parallelism from `risingwave.toml` to cli opts  

### LINKED ISSUE #6742: parallelism and memory should be CN-level command-line arguments
`worker_node_parallelism` and `total_memory_available_bytes` should be CN-level command-line arguments rather than `risingwave.toml`

https://github.com/risingwavelabs/risingwave/blob/86c5d8e9106da8caf17c0ad507fc5e319737d9fd/src/config/risingwave.toml#L14

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fix #6742. Also simplified the argument name because it will show in command-line.

Inspired by #6678

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

Our docs don't seem to cover this part yet.

## Refer to a related PR or issue link (optional)

Fix #6742

### CODE REVIEW

**Review by xxchan — APPROVED** [review]

**Review by yuhao-su — APPROVED** [review]

File: src/risedevtool/src/service_config.rs [hunk 1]
```diff
@@ -39,6 +39,9 @@ pub struct ComputeNodeConfig {
     pub user_managed: bool,
     pub enable_in_memory_kv_state_backend: bool,
     pub connector_rpc_endpoint: String,
+
+    pub total_memory_bytes: usize,
+    pub parallelism: usize,
```
Comment (BugenZhao) [inline src/risedevtool/src/service_config.rs:44]: We may also add a default value in the `use` section in `risedev.yml`.

File: src/tests/simulation/src/cluster.rs [hunk 2]
```diff
@@ -195,6 +195,8 @@ impl Cluster {
                 "192.168.1.1:5690",
                 "--state-store",
                 "hummock+memory-shared",
+                "--parallelism",
+                &conf.compute_node_cores.to_string(),
```
Comment (fuyufjh) [inline src/tests/simulation/src/cluster.rs:199]: To fix the failed test: https://buildkite.com/risingwavelabs/pull-request/builds/13328#0184e806-a28b-4df2-93f5-3d00f8dff702

I debugged locally and found the core number obtained by `default_parallelism` is 1 instead of 2. The cause might be that the `ComputeNodeOpts::parse_from(...)` happened outside the simulation 🤣
