### PR TITLE
fix: cache cancel table list for compactor notification

### LINKED ISSUE #23071: actor seeing inconsistent data when drop backfilling background ddl
### Describe the bug

In `CatalogController` we have `dropped_tables` to temporarily hold the dropping objects so that CN can still query the `dropped_tables` to do CN shared buffer compaction. However, it seems that this mechanism only exists in the call path of `drop_streaming_job` deep down to `drop_object` . However, for canceling a streaming job, it goes through a different call path on `cancel_streaming_jobs` , which does not add the dropping objects to the `dropped_tables` , and then the table will be dropped before the barrier is collected, and then actor will see data inconsistency and cause error in the drop streaming job ddl.

See the flaky test in https://buildkite.com/risingwavelabs/pull-request/builds/81236#01990f20-0d63-4161-ac2e-efee0bda522f, in e2e_test/backfill/sink/different_pk_and_dist_key.slt where we drop a backfilling background ddl sink, it occasionally failed.

### Error message/log

```text

```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Fixes #23071 .

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/meta/src/controller/streaming_job.rs [hunk 1]
```diff
@@ -611,6 +611,24 @@ impl CatalogController {
             }
         }
 
+        let dropped_tables = Table::find()
```
Comment (yezizp2012) [inline src/meta/src/controller/streaming_job.rs:614]: Should we cache the dropped tables for all types of creating jobs? Or it's only necessary for background job. @zwang28

**Comment by yezizp2012** [comment]
I discovered that the mechanism might lead to dirty data in the `dropped_tables` cache. If the `barrier collect` fails or a recovery occurs, the tables are effectively dropped, yet the cache isn't cleared. Could this pose an issue for the compactor? @zwang28

**Comment by wenym1** [comment]
Do we have a plan to unify the handling of dropping and cancelling a job? The two logic seems almost the same to me.

**Comment by wenym1** [comment]
> I discovered that the mechanism might lead to dirty data in the `dropped_tables` cache. If the `barrier collect` fails or a recovery occurs, the tables are effectively dropped, yet the cache isn't cleared. Could this pose an issue for the compactor? @zwang28

This can indeed be a problem. The data of dropped tables won't be clear untill meta node restarts. We may add a logic to clear the `dropped_tables` during global recovery.

**Comment by yezizp2012** [comment]
> Do we have a plan to unify the handling of dropping and cancelling a job? The two logic seems almost the same to me.

Yes, @Chiro11 said that he's going to do some refactoring on it. Let's keep it and wait for his work.
