### PR TITLE
fix(streaming): refine lru eviction policy

### LINKED ISSUE #6500: Bug: watermark_time_ms attempt to add with overflow
### Describe the bug

Executing nexmark_q7 for 30 minutes, it is found that `lru_manager` panic.

image

```rust
 watermark_time_ms += self.barrier_interval_ms as u64 * step;
```

### To Reproduce

1. single node ec2 (commit b4206153d1fcb59d36e4eb33b79dc9520a38499a)
2. change risingwave.toml  total_memory_available_bytes = 4294967290
3. run nexmark q7 30min

### Expected behavior

_No response_

### Additional context

```rust
    last_total_bytes_used = cur_total_bytes_used;
            // watermark_time_ms += self.barrier_interval_ms as u64 * step;
            let diff = match (self.barrier_interval_ms as u64).checked_mul(step) {
                Some(x) => x,
                None => panic!(
                    "barrier_interval_ms {}, step {}",
                    self.barrier_interval_ms, step
                ),
            };

            watermark_time_ms = match watermark_time_ms.checked_add(diff) {
                Some(x) => x,
                None => panic!("watermark_time_ms {}, diff {}", watermark_time_ms, diff),
            };
```

add some panic log for `watermark_time_ms`, try to explore the cause of the failure, and find that the value of `step` has become very large.

image

```rust
 // The strategy works as follow:
            //
            // 1. When the memory usage is below the graceful threshold, we do not evict any caches
            // and reset the step to 0.
            //
            // 2. When the memory usage is between the graceful and aggressive threshold:
            //   - If the last eviction memory usage decrease after last eviction, we set the
            //     eviction step to 1
            //   - or else we set the step to last_step + 1
            //
            // 3. When the memory usage exceeds aggressive threshold:
            //   - If the memory usage decrease after last eviction, we set the eviction step to
            //     last_step
            //   - or else we set the step to last_step * 2

            step = if cur_total_bytes_used < mem_threshold_graceful {
                // Do not evict if the memory usage is lower than `mem_threshold_graceful`
                0
            } else if cur_total_bytes_used < mem_threshold_aggressive {
                // Gracefully evict
                if last_total_bytes_used > cur_total_bytes_used {
                    1
                } else {
                    step + 1
                }
            } else if last_total_bytes_used > cur_total_bytes_used {
                // Aggressively evict
                if step == 0 {
                    2
                } else {
                    step * 2
                }
            } else {
                step
            };
```

According to the calculation algorithm of `step`, it is suspected that the `evict` is not timely enough, the memory usage value has entered a certain state, and the branch is continuously hit, causing the step index to rise.

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Do not allow the eviction watermark grow exceeds the physical now.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #6500

### CODE REVIEW

**Review by Li0k — APPROVED** [review]
Thanks, LGTM

File: src/stream/src/cache/lru_manager.rs [hunk 1]
```diff
@@ -138,7 +139,7 @@ impl LruManager {
                 } else {
                     step + 1
                 }
-            } else if last_total_bytes_used > cur_total_bytes_used {
+            } else if last_total_bytes_used < cur_total_bytes_used {
```
Comment (BugenZhao) [inline src/stream/src/cache/lru_manager.rs:142]: 👀

Comment (yuhao-su) [reply src/stream/src/cache/lru_manager.rs:142]: To fix another bug.😆
