### PR TITLE
fix(meta backup): add missing meta model in meta snapshot

### LINKED ISSUE #8043: meta backup: don't leave out new MetadataModel
During meta backup, we explicitly select which MetadataModel to include in or exclude from a [metadata snapshot](https://github.com/risingwavelabs/risingwave/blob/d88f70cde1b68362079b3490f85c0b482019f60a/src/storage/backup/src/meta_snapshot.rs#L55).
The current issue is we don't enforce a review of selected MetadataModel list, when a new type of MetadataModel is added. That is we may forget to include new MetadataModel type in metadata snapshot when they should be, e.g. currently UDF, system params are left out.

Need to enforce a check after adding new MetadataModel.

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #8043 for release 0.1.17:
- include missing meta model in meta snapshot: SystemParams and Function.
- add format_version field in meta snapshot, for backward compatibility.
- support dry-run option for restore command, to view content of meta snapshot.

Further TODO in release 0.1.18: introduce mandatory check to decide whether new meta model should be included in meta snapshot.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/meta/src/backup_restore/restore.rs [hunk 1]
```diff
@@ -146,31 +165,46 @@ async fn restore_impl(
             target_id
         )));
     }
+    let mut target_snapshot = backup_store.get(target_id).await?;
+    tracing::info!(
```
Comment (hzxa21) [inline src/meta/src/backup_restore/restore.rs:169]: dumb question: will info log be printed to stdout?

File: src/meta/src/backup_restore/backup_manager.rs [hunk 2]
```diff
@@ -188,7 +188,31 @@ impl<S: MetaStore> BackupManager<S> {
...
+            .backup_store
+            .manifest()
+            .snapshot_metadata
+            .iter()
+            .map(|s| s.id)
+            .max();
+        let filtered_ids = ids
+            .iter()
+            .filter(|id| {
+                if let Some(exclude_id) = exclude_id && **id == exclude_id{
```
Comment (hzxa21) [inline src/meta/src/backup_restore/backup_manager.rs:201]: I think `delete_backups` is a low-level API and should be allowed to delete backup of specific IDs without concerns. The guarantee of maintaining at least one backup can be maintained externally. What do you think?

**Review by hzxa21 — APPROVED** [review]
Rest LGTM

File: src/meta/src/backup_restore/restore.rs (hunk 1 above)
Comment (zwang28) [reply src/meta/src/backup_restore/restore.rs:169]: Yes, when using the restore binary, risingwave logger has been properly set [here](https://github.com/risingwavelabs/risingwave/blob/c4516dea1366d9df06ccf7e28ef2bdabf6fb1019/src/storage/backup/cmd/src/bin/backup_restore.rs#L28).

File: src/meta/src/backup_restore/backup_manager.rs (hunk 2 above)
Comment (zwang28) [reply src/meta/src/backup_restore/backup_manager.rs:201]: The latest snapshot is crucial, because its monotonic data (epoch, id) is used to overwrite whenever a snapshot is used.
I'll revert the change to `delete_backups` and find a better place to ensure it later.
