### PR TITLE
fix: estimate size for topn cache extract_if

### LINKED ISSUE #14530: bug(streaming): `TopNCache::estimated_heap_size` wrong
Some user report that the memory metrics is wrong for streaming query with topN

It is because the `TopNCacheState::extract_if` and `TopNCacheState::retain` do not maintain the `kv_size` correctly.

https://github.com/risingwavelabs/risingwave/blob/8c77bb422255f667a0c0806b920a10ed25240972/src/stream/src/executor/top_n/topn_cache_state.rs#L111-L124

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

add estimate size for topn cache extract_if

close #14530

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/stream/src/executor/top_n/topn_cache_state.rs [hunk 1]
```diff
@@ -108,18 +108,25 @@ impl TopNCacheState {
         self.inner.range(range)
     }
 
-    pub fn extract_if<F>(&mut self, pred: F) -> ExtractIf<'_, CacheKey, CompactedRow, F, Global>
+    pub fn extract_if<'a, F1>(
+        &'a mut self,
+        mut pred: F1,
```
Comment (xxchan) [inline src/stream/src/executor/top_n/topn_cache_state.rs:113]: Why `mut` here? And no need to change to `F1`

**Review by xxchan — APPROVED** [review]
Can you add some background to the PR description? Specifically how did you find the issue (what problem are you trying to solve)

File: src/stream/src/executor/top_n/topn_cache_state.rs (hunk 1 above)
Comment (yuhao-su) [reply src/stream/src/executor/top_n/topn_cache_state.rs:113]: Just learn form @BugenZhao, FnMut::call_mut accept &mut self. Calling `pred` will mutate itself.

**Comment by yuhao-su** [comment]
> Can you add some background to the PR description? Specifically how did you find the issue (what problem are you trying to solve)

Added a issue link.

File: src/stream/src/executor/top_n/topn_cache_state.rs [hunk 2]
```diff
@@ -108,18 +108,25 @@ impl TopNCacheState {
         self.inner.range(range)
     }
 
-    pub fn extract_if<F>(&mut self, pred: F) -> ExtractIf<'_, CacheKey, CompactedRow, F, Global>
+    pub fn extract_if<'a, F1>(
```
Comment (xxchan) [inline src/stream/src/executor/top_n/topn_cache_state.rs:111]: This change makes me think:
1. Are there any other places that the size is not correctly maintained?
2. Why this is `kv_heap_size` stuff is in `TopNCacheState`? It looks like a general `BTreeMapWithEstimateSize` or sth.

**Review by st1page — APPROVED** [review]

File: src/stream/src/executor/top_n/topn_cache_state.rs (hunk 2 above)
Comment (yuhao-su) [reply src/stream/src/executor/top_n/topn_cache_state.rs:111]: There are some special usage of an estimated structure. For example https://github.com/singularity-data/risingwave/blob/9cd7f6486e659af72857aef7ac27247305e880c0/src/stream/src/executor/managed_state/join/join_entry_state.rs#L75. It can be hard to provide an EstimatedBtreeMap with an unified semantic.

**Review by BugenZhao — APPROVED** [review]
