### PR TITLE
fix(expr): fix `overlay` function with large range input

### LINKED ISSUE #10699: perf: optimize `overlay` with high `for` input
```
dev=> \timing on
Timing is on.
dev=> SELECT overlay('123' placing '12345' from 1123456 for 1123456); 
 ?column? 
----------
 12312345
(1 row)

Time: 47.893 ms
dev=> SELECT overlay('123' placing '12345' from 1123456789 for 1123456789); 
 ?column? 
----------
 12312345
(1 row)

Time: 10451.279 ms (00:10.451)
dev=> SELECT overlay('123' placing '12345' from 1123456789 for 11234); 
 ?column? 
----------
 12312345
(1 row)

Time: 10423.252 ms (00:10.423)
dev=> SELECT overlay('123' placing '12345' from 11234 for 1123456789); 
 ?column? 
----------
 12312345
(1 row)

Time: 4.833 ms
```

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #10699

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/expr/impl/src/scalar/overlay.rs [hunk 1]
```diff
@@ -125,25 +129,26 @@ mod tests {
...
+        case("aaa", "XY", 123, None, "aaaXY");
+        // count too small or large.
+        case("aaa", "X", 4, Some(-123), "aaaXaaa");
+        case("aaa_", "X", 4, Some(123), "aaaX");
+        // very large start and count
+        case("aaa", "X", i32::MAX, Some(i32::MAX), "aaaX");
 
-        for (s, new_sub_str, start, count, expected) in cases {
+        #[track_caller]
+        fn case(s: &str, new_sub_str: &str, start: i32, count: Option<i32>, expected: &str) {
```
Comment (TennyZhuang) [inline src/expr/impl/src/scalar/overlay.rs:151]: TIL, the error reporting seems more friendly.
