### PR TITLE
fix(config): remove system params from config file

### LINKED ISSUE #7860: Deprecate: Remove system params from config file
- `sstable_size_mb`
- `block_size_kb`
- `bloom_false_positive`
- `data_directory`
- `state_store` (also from CLI of compute and compactor)
- `backup` section
- `checkpoint_frequency`
- `barrier_interval_ms`

### PR DESCRIPTION
**Pull request by Gun9niR**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As title. Closes #7860. The removed config will be acceptable from meta node CLI.

## Documentation

-  My PR contains user-facing changes.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- RisingWave cluster configuration changes

### Release note

System parameters are no longer accepted in the configuration file. Instead, they can be initialized from the CLI of the meta node. Here is a list of the removed configs:

| Name | Section | Argument |
| - | - | - |
| sstable_size_mb | storage | --sstable-size-mb |
| block_size_kb | storage | --block-size-kb |
| bloom_false_positive | storage | --bloom-false-positive |
| data_directory | storage | --data-directory |
| checkpoint_frequency | streaming | --checkpoint-frequency |
| barrier_interval_ms | streaming | --barrier-interval-ms |
| storage_url | backup | --backup-storage-url |
| storage_directory | backup | --backup-storage-directory |

### CODE REVIEW

**Review by xxchan — APPROVED** [review]

**Review by BugenZhao — APPROVED** [review]

**Comment by BugenZhao** [comment]
It seems the end-to-end test becomes much slower after this PR. Would you please help to take a look? 🤔

File: src/meta/src/lib.rs [hunk 1]
```diff
@@ -246,15 +248,15 @@ pub fn start(opts: MetaNodeOpts) -> Pin<Box<dyn Future<Output = ()> + Send>> {
                     .periodic_ttl_reclaim_compaction_interval_sec,
             },
             SystemParams {
-                barrier_interval_ms: Some(config.streaming.barrier_interval_ms),
-                checkpoint_frequency: Some(config.streaming.checkpoint_frequency as u64),
-                sstable_size_mb: Some(config.storage.sstable_size_mb),
-                block_size_kb: Some(config.storage.block_size_kb),
-                bloom_false_positive: Some(config.storage.bloom_false_positive),
+                barrier_interval_ms: Some(opts.barrier_interval_ms),
```
Comment (BugenZhao) [inline src/meta/src/lib.rs:251]: Seems we will extract initial system parameters only from the CLI now. 🤔 Is this the expected behavior? By doing this, we are not able to customize them in the config file and I guess that's why this change leads to end-to-end tests timeout. cc @fuyufjh 

These configuration items do not take effect and we fallback to the default value (like 1000ms, 10 freq) which will waste time on CI.

https://github.com/risingwavelabs/risingwave/blob/632423ae6b18ffb8284d15466f3ba454c3bf42a3/src/config/ci.toml#L6-L10

Comment (fuyufjh) [reply src/meta/src/lib.rs:251]: It seems that we didn't have discussion on this part. Previously, we had decided the `storage_url` can be initialized via command line, which is required by a new cluster.

But for this case, is there some better way to SET these parameters (`barrier_interval_ms` majorly) for CI?

cc. @Gun9niR

Comment (BugenZhao) [reply src/meta/src/lib.rs:251]: Note that we have no guarantee about when these new values of mutable params will take effect after `SET`. So if we decide to initialize them with `SET`, we'd better restart the cluster before running tests in case. This seems a little bit complicated for testing purpose. 😟

Comment (fuyufjh) [reply src/meta/src/lib.rs:251]: Hmmmm, from my understanding the `SET` may not take effect immediately but will eventually propogate to all nodes. Am I correct?

Comment (BugenZhao) [reply src/meta/src/lib.rs:251]: It depends on the implementation. Sometimes for simplicity, a module initializes itself by directly snapshotting the params (like copying an `u32`), instead of subscribing to the changes. In this case, the param only takes effect for new "session"s. If a session has the same lifetime as the node, then it's on the next startup.

But indeed, we can carefully check all implementations and apply the changes ASAP.

Comment (Gun9niR) [reply src/meta/src/lib.rs:251]: > Note that we have no guarantee about when these new values of mutable params will take effect after SET.

That's why I also make mutable params like `barrier_interval_ms` acceptable from CLI.
