### PR TITLE
fix(streaming): correct row concat and enable tpch q21

### LINKED ISSUE #5291: bug: streaming TPC-H Q21 outputs empty result
### Describe the bug

The MView shows 0 results, while the batch query gives 1 rows.

### To Reproduce

After #5292 being merged, just uncomment the Q21 in the e2e test

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

as title

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #5291

### CODE REVIEW

File: src/stream/src/executor/hash_join.rs [hunk 1]
```diff
@@ -786,24 +786,27 @@ impl<K: HashKey, S: StateStore, const T: JoinTypePrimitive> HashJoinExecutor<K,
...
+        let mut check_join_condition =
+            |row_update: &RowRef<'_>, row_matched: &Row| -> StreamExecutorResult<bool> {
+                // TODO(yuhao-su): We should find a better way to eval the expression without concat
+                // two rows.
+                let mut cond_match = true;
+                // if there are non-equi expressions
+                if let Some(ref mut cond) = cond {
+                    let new_row = Self::row_concat(
+                        row_update,
+                        side_update.start_pos,
```
Comment (jon-chuang) [inline src/stream/src/executor/hash_join.rs:798]: nice catch, we can put `update_start_pos` etc into a closure so it only lives as long as to be a parameter for chunk_builder.

**Review by jon-chuang — APPROVED** [review]
Rest LGTM
