### PR TITLE
fix(sqlsmith): limit number of cross joins

### LINKED ISSUE #7889: bug: fuzzing test generates a stuck SQL
### Describe the bug

It's first found in fuzzing test [here](https://buildkite.com/risingwavelabs/main/builds/3049). But it's also reproducible manually in earlier main branch.
The stuck SQL is `WITH with_0 AS (SELECT ((-2147483648) - (INT '326045151')) AS col_0, t_3.ps_comment AS col_1, ((SMALLINT '5714') >> (SMALLINT '26755')) AS col_2, ((INTERVAL '0') / t_9.seller) AS col_3 FROM region AS t_1, orders AS t_2, partsupp AS t_3, nation AS t_4, m1 AS t_5, auction AS t_6, customer AS t_7, m3 AS t_8, auction AS t_9 WHERE ('eCmLGTvlUV') NOT IN ((substr('75B3GHhhEA', (INT '1424354786'))), (repeat('NY1sHcmvym', (INT '1822803048'))), 'k0irJrq3Ca') GROUP BY t_9.item_name, t_2.o_shippriority, t_9.seller, t_3.ps_partkey, t_7.c_nationkey, t_3.ps_comment, t_6.reserve, t_8.col_2, t_6.initial_bid) SELECT ((FLOAT '-214847089') / t_15.col_0) AS col_0, (SMALLINT '119') AS col_1 FROM with_0, m7 AS t_10, m1 AS t_11, m3 AS t_12, m9 AS t_13, hop(auction, auction.date_time, INTERVAL '60', INTERVAL '3600') AS hop_14, m2 AS t_15, hop(person, person.date_time, INTERVAL '60', INTERVAL '3600') AS hop_16 GROUP BY hop_14.date_time, hop_14.description, hop_14.item_name, hop_14.extra, t_11.col_1, hop_14.expires, hop_14.initial_bid, hop_16.state, t_10.col_0, hop_16.email_address, t_15.col_0, t_15.col_2, t_12.col_1, hop_16.credit_card, t_12.col_0 HAVING true LIMIT 36;`

### To Reproduce

1. Create prerequisite table/source.
2. Execute the SQL in psql and get stuck.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #7889 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by lmatz — APPROVED** [review]

File: src/tests/sqlsmith/src/sql_gen/query.rs [hunk 1]
```diff
@@ -239,8 +239,8 @@ impl<'a, R: Rng> SqlGenerator<'a, R> {
 
         // Generate CROSS JOIN
         let mut lateral_contexts = vec![];
-        for _ in 0..self.tables.len() {
-            if self.rng.gen_bool(0.3) {
+        for _ in 0..usize::min(self.tables.len(), 5) {
```
Comment (jon-chuang) [inline src/tests/sqlsmith/src/sql_gen/query.rs:242]: Just curious, this will not affect number of eq joins, right?
