### PR TITLE
fix(sqlparser): `Display` multiple source `INCLUDE` columns correctly

### LINKED ISSUE #18800: bug(source): multiple `INCLUDE` additional columns `Display` inconsistent with parser
It was inconsistent when initially introduced: https://github.com/risingwavelabs/risingwave/pull/13707#discussion_r1429812951

And went through several rounds of fixes (see `src/sqlparser/src/ast/mod.rs`): #14215, #18098

But still remains inconsistent and causes recovery loop.

Reproduce:

```
CREATE TABLE t (raw BYTEA) INCLUDE timestamp AS kafka_ts INCLUDE key AS kafka_key WITH (connector = 'kafka', kafka.brokers = '${RISEDEV_KAFKA_BOOTSTRAP_SERVERS}', topic = 'dummy') FORMAT PLAIN ENCODE BYTES;

SELECT definition FROM rw_tables WHERE name = 't';

RECOVER;
```

cc @tabVersion @KeXiangWang

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Resolves #18800

The `Display` logic had 3 bugs making it inconsistent with `parse_include_options`:
* Multiple items shall not be separated by comma.
* Header key shall be singled quoted.
* Header data type shall not be omitted for varchar. (Seems [undocumented](https://docs.risingwave.com/docs/current/include-clause/) feature)

For example,
* User input: `INCLUDE header 'foo' VARCHAR INCLUDE timestamp`
* Meta catalog `definition` contains: `INCLUDE header foo, INCLUDE timestamp`

Besides fixing the 3 issues, we also update the parsing logic to tolerate the extra comma caused by 1st bug. It is impossible to tolerate the latter 2 bugs.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [x] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/sqlparser/src/ast/mod.rs [hunk 1]
```diff
@@ -2187,6 +2171,36 @@ impl fmt::Display for Statement {
...
+            write!(f, " '{}'", value::escape_single_quote_string(inner_field))?;
+            if let Some(expected_type) = header_inner_expect_type {
+                write!(
+                    f,
+                    " {}",
+                    match expected_type {
+                        DataType::Varchar => "varchar",
+                        DataType::Bytea => "bytea",
+                        t => unreachable!("unparse header expected type: {t}"),
+                    }
```
Comment (xiangjinwu) [inline src/sqlparser/src/ast/mod.rs:2193]: Will refactor the data type logic further in a follow-up PR. This one intends to minimize the changes to parsing logic and focus on `Display`. There is a lot of space to improve for the parsing & handling of data type as well.

**Review by tabVersion — APPROVED** [review]

**Review by KeXiangWang — APPROVED** [review]
LGTM Thanks for the fix!
