### PR TITLE
fix: do not panic when ssl do not setup

### LINKED ISSUE #5953: Kernel crashes on connect
### Describe the bug

**Stack trace:** 

```
2022-10-20T13:36:11.959923Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    2,
).
2022-10-20T13:36:11.960046Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    3,
).
2022-10-20T13:36:11.960098Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    2,
).
2022-10-20T13:36:11.960139Z  INFO risingwave_common_service::metrics_manager: Prometheus listener for Prometheus is set up on http://127.0.0.1:1222
thread 'risingwave-main' panicked at 'Unable to set up a ssl connection, reason: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:1544:SSL alert number 48', /Users/janmensch/Documents/github/risingwave/src/utils/pgwire/src/pg_protocol.rs:631:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: pgwire::pg_protocol::PgStream<S>::ssl::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:631:13
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: pgwire::pg_protocol::Conn<S>::ssl::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:693:51
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process_ssl_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:233:54
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:203:53
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:157:38
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:153:26
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  14: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:116:46
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  17: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  19: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  20: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  23: ___rust_try
  24: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  25: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  26: tokio::runtime::task::harness::poll_future
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  27: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  28: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  29: tokio::runtime::task::raw::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:194:5
  30: tokio::runtime::task::raw::RawTask::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  31: tokio::runtime::task::LocalNotified<S>::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:385:9
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:421:13
  33: tokio::coop::with_budget::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:102:9
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  36: tokio::coop::with_budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:95:5
  37: tokio::coop::budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:72:5
  38: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:420:9
  39: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:387:24
  40: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:372:17
  41: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/macros/scoped_tls.rs:61:9
  42: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:369:5
  43: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:348:45
  44: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/task.rs:42:21
  45: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  46: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  47: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  48: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  49: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  50: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  51: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  52: ___rust_try
  53: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  54: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  55: tokio::runtime::task::harness::poll_future
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  56: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  57: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  58: tokio::runtime::task::raw::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:194:5
  59: tokio::runtime::task::raw::RawTask::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  60: tokio::runtime::task::UnownedTask<S>::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:422:9
  61: tokio::runtime::blocking::pool::Task::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:111:9
  62: tokio::runtime::blocking::pool::Inner::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:346:17
  63: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:321:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/var/folders/fj/dmw16z3n01l9dj2bmx_zc0hc0000gn/T/fsio_8bqcN3ZCuU.sh: line 9: 10080 Abort trap: 6           RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin risingwave --profile "${RISINGWAVE_BUILD_PROFILE}"
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
```

### To Reproduce

I am using the latest `main` at commit `58f07ccb7645e2f0328d4b395f78e8a63fc4155c`

Run `risedev p` and then connect via `psql -h localhost -p 4566 -d dev -U root`

### Expected behavior

_No response_

### Additional context

```
cargo --version 
cargo 1.64.0-nightly (85b500cca 2022-07-24)

openssl version
LibreSSL 2.8.3

psql -V
psql (PostgreSQL) 14.5 (Homebrew)
# problem persists after upgrading to 14.5.5
```

Connecting against a prod instance also fails. Seems to be connected to my SSL setup? 

```
psql "postgresql://Jan:@canary-useast2-eks-a.risingwave.cloud:4566/dev?sslmode=require&options=--tenant%3Drwc-998-test"
psql: error: connection to server at "canary-useast2-eks-a.risingwave.cloud" (3.142.128.2), port 4566 failed: SSL error: certificate verify failed
```

### PR DESCRIPTION
**Pull request by BowenXiao1999**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Currently we do not know why this will happen. But just makes the ssl more robust.

Close #5953.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BowenXiao1999** [comment]
Hmmm, still get some problems..

**Comment by CAJan93** [comment]
> Hmmm, still get some problems..

😢 Let me know if I can help you. What output do you get at the moment? Does it still crash?

File: src/utils/pgwire/src/pg_protocol.rs [hunk 1]
```diff
@@ -620,21 +625,22 @@ impl<S> PgStream<S>
...
+    async fn ssl(&mut self, ssl_ctx: &SslContextRef) -> PsqlResult<PgStream<SslStream<S>>> {
         // Note: Currently we take the ownership of previous Tcp Stream and then turn into a
         // SslStream. Later we can avoid storing stream inside PgProtocol to do this more
         // fluently.
         let stream = self.stream.take().unwrap();
         let ssl = openssl::ssl::Ssl::new(ssl_ctx).unwrap();
         let mut stream = tokio_openssl::SslStream::new(ssl, stream).unwrap();
         if let Err(e) = Pin::new(&mut stream).accept().await {
-            panic!("Unable to set up a ssl connection, reason: {}", e);
+            warn!("Unable to set up a ssl connection, reason: {}", e);
```
Comment (CAJan93) [inline src/utils/pgwire/src/pg_protocol.rs:636]: You only get to this code after terminating the connection.

Comment (CAJan93) [reply src/utils/pgwire/src/pg_protocol.rs:636]: I tried a similar direction with 

```rust 
        if let Err(e) = Pin::new(&mut stream).accept().await {
            tracing::error!("Unable to establish the SSL connection. Error was '{}'", e);
            return PgStream {
                stream: None,
                write_buf: BytesMut::with_capacity(0),
            };
        }
```
But it went nowhere

Comment (CAJan93) [reply src/utils/pgwire/src/pg_protocol.rs:636]: Is there the possibility to set some timeout for `Pin::new(&mut stream).accept().await`. I think if we could do that your code this may work.

Comment (BowenXiao1999) [reply src/utils/pgwire/src/pg_protocol.rs:636]: No, i need to reject this connection. I will finish this later.

Comment (BowenXiao1999) [reply src/utils/pgwire/src/pg_protocol.rs:634]: Expected behaviour is you never login to the pg server but server do not panic (only warning)

Comment (CAJan93) [reply src/utils/pgwire/src/pg_protocol.rs:634]: Yes. I was also surprised by that. I would have expected that the server rejects the connection if SSL fails.

**Comment by CAJan93** [comment]
I can connect this way. Is that intentional? 

```sh 
ls ~/.postgresql/root.crt
psql -h localhost -p 4566 -d dev -U root
```

I assume that I would need to disable SSL via 

```
psql "port=4566 host=localhost user=root dbname=dev sslmode=disable"
```

**Comment by BowenXiao1999** [comment]
> Enforcing SSL: 
>
```
psql "port=4566 host=localhost user=root dbname=dev sslmode=require"
connection to server at "localhost" (127.0.0.1), port 4566 failed: could not read root certificate file "/Users/janmensch/.postgresql/root.crt": no certificate or crl found
```
> I would have expected that the server logs show `Unable to set up a ssl connection, reason`, but they do not. 
>
> I think the reason why we do not get an SSL error is because we never process any SSL message 
>
 ```rust 
    async fn do_process_inner(&mut self) -> PsqlResult<bool> {
        let msg = self.read_message().await?;
        match msg {
            FeMessage::Ssl => self.process_ssl_msg().await?,             # previously we went here 
            FeMessage::Startup(msg) => self.process_startup_msg(msg)?,   # now we go here
            FeMessage::Password(msg) => self.process_password_msg(msg)?,
```


The error shows that psql client do not read corresponding file, so it do not forward a SslRequest to our server, so we do not process ssl msg.

> I can connect this way. Is that intentional? Should the server not reject this or do we want to disable SSL by default?

I think may also due to the file is not a real CA?

**Review by fuyufjh — APPROVED** [review]
LGTM. Anything to block it from being merged?

**Comment by CAJan93** [comment]
Thanks for fixing this @BowenXiao1999 👍
