### PR TITLE
fix(sink): switch remote sink chrono types to java.time.*

### LINKED ISSUE #13684: Chrono types in remote sinks
> * In RisingWave, time / timestamp / timestamptz has a precision of microseconds, neither milli nor nano.
> * When possible, prefer "new" classes in `java.time.*` since Java 8 ([doc](https://www.oracle.com/technical-resources/articles/java/jf14-date-time.html)) over [legacy](https://mail.openjdk.org/pipermail/discuss/2022-May/006077.html) ones in `java.sql.*`.
>   * `date` -> `LocalDate`
>   * `time` -> `LocalTime`
>   * `timestamp` -> `LocalDateTime`
>   * `timestamptz` -> `OffsetDateTime`

It seems that all remote sinks use `java.sql.Time\Date\Timestamp`, and their precision is in milliseconds.

_Originally posted by @xuefengze in https://github.com/risingwavelabs/risingwave/issues/13651#issuecomment-1829051121_

### LINKED ISSUE #14198: `postgres-sink` data is incorrect for the `date/time` type
### Describe the bug

`pg-sink` data is incorrect for the `date/time` type.

rw:
image

pg:
image

### Error message/log

_No response_

### To Reproduce

pg:
```sql
CREATE TABLE test (
  id INT,
  d DATE,
  PRIMARY KEY (id)
);
```

rw:
```sql
CREATE TABLE test (
  id INT,
  d DATE,
  PRIMARY KEY (id)
);
INSERT INTO test VALUES (1, '0001-01-01');
INSERT INTO test VALUES (2, '1550-12-31');
INSERT INTO test VALUES (3, '9999-01-01');
INSERT INTO test VALUES (4, '1970-01-01');
INSERT INTO test VALUES (5, '1000-01-01');

CREATE SINK test_sink
FROM
    test WITH (
    connector = 'jdbc',
    jdbc.url = 'jdbc:postgresql://postgres:5432/mydb?user=myuser&password=123456',
    table.name = 'test',
    type='upsert',
    primary_key = 'id'
);
```

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xuefengze**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

resolve #13684 and fix #14198

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

`cassandra-sink`:
Before:
`timestamp` is allowed to sink into `timestamp` type in cassandra.

After:
`timestamp` cannot be sinked and has to be converted to timestamptz (via AT TIME ZONE) inside RisingWave before sinking out.

</details>

### CODE REVIEW

File: src/jni_core/src/lib.rs [hunk 1]
```diff
@@ -607,27 +610,127 @@ extern "system" fn Java_com_risingwave_java_binding_Binding_iteratorGetTimestamp
...
+                    jvalue {
+                        i: value.minute() as i32,
+                    },
+                    jvalue {
+                        i: value.second() as i32,
+                    },
+                    jvalue {
+                        i: value.nanosecond() as i32,
+                    },
+                    jvalue { l: *utc },
```
[the remark this answers is not in the document]
Comment (xuefengze) [reply src/jni_core/src/lib.rs:724]: It seems that the [rw timestamptz](https://github.com/risingwavelabs/risingwave/blob/main/src/common/src/types/timestamptz.rs#L36) type only stores the microseconds?

**Review by xiangjinwu — APPROVED** [review]
Thanks for the fix!

Also spotted some other references to the legacy classes:
* `connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java`
* `connector-node/risingwave-sink-mock-flink/risingwave-sink-mock-flink-runtime/src/main/java/com/risingwave/mock/flink/runtime/RowDataImpl.java`
* `connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSink.java`
* `connector-node/risingwave-source-cdc/src/main/java/com/risingwave/connector/cdc/debezium/converters/DatetimeTypeConverter.java`

After cleaning these up, is it possible to add a static analysis rule to disallow usage of them? We have this in rust: https://github.com/risingwavelabs/risingwave/blob/df1b9de16492887831a31028314da8fff848ff3a/clippy.toml#L1-L2

File: src/jni_core/src/lib.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (wenym1) [reply src/jni_core/src/lib.rs:724]: Oh I get the idea now. I think maybe it's better to use [static OffsetDateTime	ofInstant(Instant instant, ZoneId zone)](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#ofInstant-java.time.Instant-java.time.ZoneId-). We can create the `Instant` from the raw 64 bit timestamp instead of converting to a datetime and then fetch the year month and data.

And also the `UTC` can be stored as a global ref in the cache to avoid keep fetching it.

File: java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java [hunk 2]
```diff
@@ -240,7 +265,7 @@ static void testJDBCDrop(JdbcDatabaseContainer<?> container, TestType testType)
     @Test
     public void testPostgres() throws SQLException {
         PostgreSQLContainer pg =
-                new PostgreSQLContainer<>("postgres:15-alpine")
+                new PostgreSQLContainer<>("postgres:latest")
```
[the remark this answers is not in the document]
Comment (StrikeW) [reply java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java:268]: Any reason to modify the version here? we should aware the version we are testing against. `latest` is ambiguous.

File: java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java [hunk 3]
```diff
@@ -257,7 +282,7 @@ public void testPostgres() throws SQLException {
     @Test
     public void testMySQL() throws SQLException {
         MySQLContainer mysql =
-                new MySQLContainer<>("mysql:8")
+                new MySQLContainer<>("mysql:latest")
```
Comment (StrikeW) [inline java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java:285]: ditto

**Review by StrikeW — COMMENTED** [review]
Would you mind adding e2e test to cover the case of https://github.com/risingwavelabs/risingwave/issues/14198 in `e2e_test/sink/remote/jdbc.load.slt`?

File: java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java (hunk 3 above)
Comment (xuefengze) [reply java/connector-node/risingwave-connector-test/src/test/java/com/risingwave/connector/sink/jdbc/JDBCSinkTest.java:285]: My local image version is `latest`, forget to change it back.

**Comment by xuefengze** [comment]
`mysql-sink`: When insert `2038-01-19 03:14:07.499999Z`, will get error: 
> message Data truncation: Incorrect datetime value: '2038-01-19 11:14:07.499999'

It appears that mysql jdbc will convert it to the default timezone? Maybe we can cast `offsetdatetime` to `localdatetime` before write to solve this issue?
https://github.com/mysql/mysql-connector-j/blob/release/8.x/src/main/protocol-impl/java/com/mysql/cj/protocol/a/OffsetDateTimeValueEncoder.java#L72-L83

**Comment by xiangjinwu** [comment]
> my local timezone +8

It is better to set the session/connection timezone to UTC when interacting with MySQL (and other systems as well).

https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-known-issues-limitations.html
> When Connector/J retrieves timestamps for a daylight saving time (DST) switch day using the `getTimeStamp()` method on the result set, some of the returned values might be wrong. In order to avoid such errors, we recommend setting a connection time zone that uses a monotonic clock by, for example, setting [connectionTimeZone=UTC](https://dev.mysql.com/doc/connector-j/en/connector-j-connp-props-datetime-types-processing.html#cj-conn-prop_connectionTimeZone), and configuring other date-time connection properties according to your needs; see [Section 6.6, “Handling of Date-Time Values”](https://dev.mysql.com/doc/connector-j/en/connector-j-date-time.html) for details.

File: e2e_test/sink/remote/jdbc.check.pg.slt [hunk 4]
```diff
@@ -3,17 +3,17 @@
 query I
 select * from t_remote_0 order by id;
 ----
-1 Alex 28208 281620391 4986480304337356659 28162.0391 2.03 28162.0391 2023-03-20 10:18:30
```
Comment (wenym1) [inline e2e_test/sink/remote/jdbc.check.pg.slt:6]: Any reason to change from a normal datetime to a strange one?

File: java/connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSink.java [hunk 5]
```diff
@@ -88,13 +87,11 @@ public void write(Iterator<SinkRow> rows) {
...
-                            values = ((Timestamp) row.get(i)).getTime();
-                        } else if (row.get(i) instanceof java.sql.Date) {
+                        if (row.get(i) instanceof LocalDateTime) {
                             values =
-                                    ChronoUnit.DAYS.between(
-                                            LocalDate.ofEpochDay(0),
-                                            ((java.sql.Date) row.get(i)).toLocalDate());
+                                    ((LocalDateTime) row.get(i))
+                                            .toInstant(ZoneOffset.UTC)
+                                            .toEpochMilli();
```
Comment (xiangjinwu) [inline java/connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSink.java:94]: cc @xxhZs regarding #13420 #13677 I am not sure whether we need to test for all 4 `LocalDate`/`LocalTime`/`LocalDateTime`/`OffsetDateTime` out of `Object` ...

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#timestamp-without-timezone-timestampntz
Also note that:
* RIsingWave `timestamp` is DeltaLake `TimestampNtz` (`isAdjustedToUTC=false`)
* RisingWave `timestamptz` is DeltaLake `Timestamp` (`isAdjustedToUTC=true`)

**Review by wenym1 — APPROVED** [review]
Rest LGTM! Thanks for the PR

File: e2e_test/sink/remote/jdbc.check.pg.slt (hunk 4 above)
Comment (xuefengze) [reply e2e_test/sink/remote/jdbc.check.pg.slt:6]: > Would you mind adding e2e test to cover the case of https://github.com/risingwavelabs/risingwave/issues/14198 in e2e_test/sink/remote/jdbc.load.slt?

cover the case of #14198.

File: java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java [hunk 6]
```diff
@@ -135,21 +135,21 @@ private static BigDecimal castDecimal(Object value) {
...
         }
     }
 
-    private static Date castDate(Object value) {
+    private static LocalDate castDate(Object value) {
         try {
-            Long days = castLong(value) - 1;
-            return Date.valueOf(LocalDate.of(1, 1, 1).plusDays(days));
+            Long days = castLong(value);
+            return LocalDate.ofEpochDay(days);
```
[the remark this answers is not in the document]
Comment (xuefengze) [reply java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/JsonDeserializer.java:152]: It seems that there are no remote sinks using `JsonDeserializer` currently?

File: java/connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSink.java (hunk 5 above)
Comment (xuefengze) [reply java/connector-node/risingwave-sink-deltalake/src/main/java/com/risingwave/connector/DeltaLakeSink.java:94]: https://github.com/risingwavelabs/risingwave/pull/14277

**Comment by xiangjinwu** [comment]
> After cleaning these up, is it possible to add a static analysis rule to disallow usage of them?

I figured this out:
```diff
diff --git a/java/tools/maven/checkstyle.xml b/java/tools/maven/checkstyle.xml
index 4bd0d510e0..f681633272 100644
--- a/java/tools/maven/checkstyle.xml
+++ b/java/tools/maven/checkstyle.xml
@@ -191,10 +191,24 @@ This file is based on the checkstyle file of Apache Beam.
             <property name="illegalPkgs" value="io.netty"/>
             <message key="import.illegal" value="{0}; Use flink-shaded-netty instead."/>
         </module>
+        <!--
         <module name="IllegalImport">
             <property name="illegalPkgs" value="com.google.common"/>
             <message key="import.illegal" value="{0}; Use flink-shaded-guava instead."/>
         </module>
+        -->
+        <module name="IllegalImport">
+            <property name="illegalClasses" value="java.util.Date, java.sql.Date, java.sql.Timestamp, java.sql.Time"/>
+            <message key="import.illegal" value="{0}; Use java.time.* instead."/>
+        </module>
+        <module name="IllegalImport">
+            <property name="illegalClasses" value="java.text.DateFormat, java.text.SimpleDateFormat"/>
+            <message key="import.illegal" value="{0}; Use java.time.* instead."/>
+        </module>
+        <module name="IllegalImport">
+            <property name="illegalClasses" value="java.util.Calendar, java.util.GregorianCalendar"/>
+            <message key="import.illegal" value="{0}; Use java.time.* instead."/>
+        </module>
 
         <module name="RedundantModifier">
             <!-- Checks for redundant modifiers on various symbol definitions.
diff --git a/java/tools/maven/suppressions.xml b/java/tools/maven/suppressions.xml
index 5e19f59eae..11b4774359 100644
--- a/java/tools/maven/suppressions.xml
+++ b/java/tools/maven/suppressions.xml
@@ -30,5 +30,4 @@ under the License.
 
     <suppress files=".*" checks="javadoc"/>
     <suppress files=".*" checks="AvoidStarImport"/>
-    <suppress files=".*" checks="IllegalImport"/>
 </suppressions>
\ No newline at end of file
```

**Review by xiangjinwu — APPROVED** [review]
