### PR TITLE
fix: make pulsar source exactly once

### LINKED ISSUE #22486: bug: pulsar re-ingest some data each time recovery
### Describe the bug

```
dev=> create table s1 (a int, b varchar) with (
  connector = 'pulsar',
  topic = 'persistent://public/default/topic-1',
  service.url = 'pulsar://localhost:6650',      
  scan.startup.mode = 'earliest'
) FORMAT PLAIN ENCODE JSON
;
CREATE_TABLE
dev=> 
dev=> 
dev=> 
dev=> select * from s1 ;
 a  | b  
----+----
  3 | 4
  1 | 2
  5 | 6
  9 | 10
  7 | 8
 11 | 12
 15 | 16
 13 | 14
 17 | 18
 19 | 20
(10 rows)

dev=> 
dev=> recover ;
RECOVER
dev=> 
dev=> select * from s1 ;
 a  | b  
----+----
  3 | 4
  1 | 2
  5 | 6
  9 | 10
  7 | 8
 11 | 12
 15 | 16
 13 | 14
 17 | 18
 19 | 20
 15 | 16
 19 | 20
 17 | 18
(13 rows)

dev=> recover ;
RECOVER
dev=> select * from s1 ;
 a  | b  
----+----
  3 | 4
  1 | 2
  5 | 6
  9 | 10
  7 | 8
 11 | 12
 15 | 16
 13 | 14
 17 | 18
 19 | 20
 15 | 16
 19 | 20
 17 | 18
 15 | 16
 19 | 20
 17 | 18
(16 rows)

dev=> select * from s1 order by a ;
 a  | b  
----+----
  1 | 2
  3 | 4
  5 | 6
  7 | 8
  9 | 10
 11 | 12
 13 | 14
 15 | 16
 15 | 16
 15 | 16
 17 | 18
 17 | 18
 17 | 18
 19 | 20
 19 | 20
 19 | 20
(16 rows)
```

### Error message/log

```text

```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

close #22486 

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/connector/src/source/pulsar/source/reader.rs [hunk 1]
```diff
@@ -80,6 +80,9 @@ impl SplitReader for PulsarSplitReader {
     }
 }
 
+// entry_id, batch_index
+type PulsarFilterOffset = (u64, Option<i32>);
```
Comment (xiangjinwu) [inline src/connector/src/source/pulsar/source/reader.rs]: Why not make it a struct?
```
struct PulsarFilterOffset {
    entry_id: u64,
    batch_index: Option<i32>,
}
```

File: src/connector/src/source/pulsar/source/reader.rs [hunk 2]
```diff
@@ -193,9 +201,12 @@ impl SplitReader for PulsarBrokerReader {
                         ConsumerOptions::default().with_initial_position(InitialPosition::Latest),
                     )
                 } else {
+                    let start_message_id = parse_message_id(m.as_str())?;
+                    already_read_offset =
+                        Some((start_message_id.entry_id, start_message_id.batch_index));
                     builder.with_options(pulsar::ConsumerOptions {
                         durable: Some(false),
-                        start_message_id: parse_message_id(m.as_str()).ok(),
```
Comment (xiangjinwu) [inline src/connector/src/source/pulsar/source/reader.rs:198]: Subtle difference: `parse_message_id` error used to be ignored (`ok`) but now bubbles up (`?` on line 204 above)

Could you confirm if the new behavior is better?

File: e2e_test/source_inline/pulsar/issue-22486.slt.serial
Comment (xiangjinwu) [inline e2e_test/source_inline/pulsar/issue-22486.slt.serial:1]: This new test file gives false confidence. It can pass without the fix:
https://buildkite.com/risingwavelabs/pull-request/builds/77951

Comment (xiangjinwu) [reply e2e_test/source_inline/pulsar/issue-22486.slt.serial:1]: Enhanced the test to repro the issue and validate the fix:
https://buildkite.com/risingwavelabs/pull-request/builds/78003

File: src/connector/src/source/pulsar/source/reader.rs (hunk 2 above)
Comment (tabVersion) [reply src/connector/src/source/pulsar/source/reader.rs:198]: We made the message state ourselves, not by the sdk. 
If something goes wrong, eg. cannot parse the message_id, the prev behavior is calling `ok()`, which swallows the error and allow the source starts from the beginning silently. But the error should be bubbled up and involve human maintenance.

File: src/connector/src/source/pulsar/source/reader.rs [hunk 3]
```diff
@@ -80,6 +80,15 @@ impl SplitReader for PulsarSplitReader {
     }
 }
 
+/// Filter offset for pulsar messages
+#[derive(Debug, Clone, PartialEq, Eq)]
```
Comment (xiangjinwu) [inline src/connector/src/source/pulsar/source/reader.rs]: How is `PartialEq`/`Eq` used?

**Review by xiangjinwu — APPROVED** [review]
