### PR TITLE
fix: column aware row encoding: improve the implementation and add bench

### LINKED ISSUE #16763: perf: improve the performance of `column_aware_row_encoding::Deserializer`
The current implementation of `ValueRowDeserializer` is not efficient, which didn't fully utilize the performance of our row encoding format.

https://github.com/risingwavelabs/risingwave/blob/d1b4612fee0c05c1cb4c77bb757f58e5f3ff5092/src/common/src/util/value_encoding/column_aware_row_encoding.rs#L205-L259

> As shown in the figure below, the main time consumption is due to container operations.
>
> This encoding is rather friendly for random access, isn't it? The sorted column_id is obviously intended to facilitate binary search.

image

https://github.com/risingwavelabs/rfcs/blob/75091f0c7f197f718b8343eb121932df5530ddb1/rfcs/0090-table-schema-change.md#column-aware-row-encoding

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Resolves #16763

Unfortunately, currently we don't ensure the persisted column IDs to be sorted. For example, `create table t (a varchar, b int, c int)` will create a state table that has column ids `1,2,3,0`, where `0` always refers to `_row_id`. 

As a result, I [reverted](https://github.com/risingwavelabs/risingwave/pull/17818/commits/98a452da6fb6da52a6d03e960fb6b5cc3f285991) the order-based implementation and use a hash-table now. 

### Benchmark result (on my MacBook)

```
Benchmarking bench_column_aware_row_encoding_decode: Collecting 100 samples in estimated 5.0018 s (1
bench_column_aware_row_encoding_decode
                        time:   [445.71 ns 448.84 ns 452.01 ns]
                        change: [-49.821% -49.204% -48.648%] (p = 0.00 < 0.05)
                        Performance has improved.
```

### Why `ahash::HashMap`?

According to my benchmark, `ahash::HashMap` is the fastest implementation.

```
ahash::HashMap       445.47 ns
hashbrown::HashMap   509.70 ns
std::collections::HashMap   595.98 ns
```

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [x] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/common/src/util/value_encoding/column_aware_row_encoding.rs [hunk 1]
```diff
@@ -46,6 +37,15 @@ bitflags! {
     }
 }
 
+fn column_ids_are_sorted(column_ids: &[ColumnId]) -> bool {
```
Comment (BugenZhao) [inline src/common/src/util/value_encoding/column_aware_row_encoding.rs:40]: Can use `is_sorted`.

**Comment by fuyufjh** [comment]
The sorted implementation is still 10% faster than this hash-table implementation.

`448.84 ns -> 403.56 ns (89.91%)`

Considering the effort of refactoring the code and additional logic for compatibility, perhaps we can postpone it until necessary.

File: src/common/src/util/value_encoding/column_aware_row_encoding.rs [hunk 2]
```diff
@@ -214,12 +206,16 @@ impl ValueRowDeserializer for Deserializer {
...
         let offsets = &encoded_bytes[offsets_start_idx..data_start_idx];
         let data = &encoded_bytes[data_start_idx..];
-        let mut datums: Vec<Option<Datum>> = vec![None; self.schema.len()];
-        let mut contained_indices = BTreeSet::new();
+
+        // initialize datums with default values
+        let mut datums: Vec<Datum> = vec![None; self.schema.len()];
+        for (i, datum) in &self.default_column_values {
+            datums[*i].clone_from(datum);
+        }
```
Comment (fuyufjh) [inline src/common/src/util/value_encoding/column_aware_row_encoding.rs:214]: Part of the performance gain is because I initialized the default values no matter whether it's overwritten. Thus, we simply return `Ok(datums)`.

File: src/common/src/util/value_encoding/column_aware_row_encoding.rs [hunk 3]
```diff
@@ -176,7 +168,7 @@ impl ValueRowSerializer for Serializer {
 /// Should non-null default values be specified, a new field could be added to Deserializer
 #[derive(Clone)]
 pub struct Deserializer {
-    needed_column_ids: BTreeMap<i32, usize>,
+    required_column_ids: HashMap<i32, usize>,
```
Comment (BugenZhao) [inline src/common/src/util/value_encoding/column_aware_row_encoding.rs:171]: Interesting. I thought `BTreeMap` is faster when there are only a few entries: https://arc.net/l/quote/okdycbqi

According to this, can we also benchmark the case for a table containing less than 6 columns?

File: src/common/src/util/value_encoding/column_aware_row_encoding.rs (hunk 2 above)
Comment (BugenZhao) [reply src/common/src/util/value_encoding/column_aware_row_encoding.rs:214]: This step of processing is not specific to the current row. I'm wondering if preprocessing it into `self.default_row`, then directly cloning the full row can perform even better. 🤔

**Review by BugenZhao — APPROVED** [review]

**Review by stdrc — APPROVED** [review]

File: src/common/src/util/value_encoding/column_aware_row_encoding.rs (hunk 3 above)
Comment (fuyufjh) [reply src/common/src/util/value_encoding/column_aware_row_encoding.rs:171]: Added bench `column_aware_row_encoding_4_columns`. Observed a similar performance improvement.

```
Benchmarking column_aware_row_encoding_16_columns_encode: Collecting 100 samples in estimated 5.0015
column_aware_row_encoding_16_columns_encode
                        time:   [491.00 ns 492.30 ns 493.95 ns]
                        change: [-3.6361% -2.8341% -2.0340%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  6 (6.00%) high mild
  4 (4.00%) high severe

Benchmarking column_aware_row_encoding_16_columns_decode: Collecting 100 samples in estimated 5.0011
column_aware_row_encoding_16_columns_decode
                        time:   [445.62 ns 448.76 ns 451.61 ns]
                        change: [-51.073% -50.248% -49.515%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

Benchmarking column_aware_row_encoding_4_columns_encode: Collecting 100 samples in estimated 5.0009 s (23M iter
column_aware_row_encoding_4_columns_encode
                        time:   [221.45 ns 224.51 ns 228.98 ns]
                        change: [+0.1302% +0.7332% +1.4856%] (p = 0.03 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  2 (2.00%) high mild
  5 (5.00%) high severe

Benchmarking column_aware_row_encoding_4_columns_decode: Collecting 100 samples in estimated 5.0004 s (38M iter
column_aware_row_encoding_4_columns_decode
                        time:   [131.47 ns 131.82 ns 132.26 ns]
                        change: [-46.562% -46.074% -45.656%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
  5 (5.00%) high severe
```
