### PR TITLE
fix(stream): left temporal join handle non-matched rows incorrectly

### LINKED ISSUE #15257: Wrong temporal join output with non-lookup condition
### Describe the bug

> If LHS matches a row in RHS and in `st1`, but the row is filter out in `st2`, we should expect a matched empty row in the result.

_Originally posted by @yuhao-su in https://github.com/risingwavelabs/risingwave/issues/15228#issuecomment-1963348322_

The behavior is wrong even on current main branch.
            

### Error message/log

_No response_

### To Reproduce

The slt file:

```
statement ok
SET RW_IMPLICIT_FLUSH TO true;

statement ok
create table stream(id1 int, a1 int, b1 int) APPEND ONLY;

statement ok
create table version(id2 int, a2 int, b2 int, primary key (id2));

statement ok
create materialized view v as select id1, a1, id2, a2 from stream left join version FOR SYSTEM_TIME AS OF PROCTIME() on id1 = id2 and a1 > a2

statement ok
insert into version values(1, 11, 111);

statement ok
insert into stream values(1, 10, 111);

query IIII rowsort
select * from v;
----
1 10 NULL NULL

statement ok
drop materialized view v;

statement ok
drop table stream;

statement ok
drop table version;
```

### Expected behavior

The slt should pass

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TennyZhuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

See tests for details

Close #15257 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/stream/src/executor/temporal_join.rs [hunk 1]
```diff
@@ -412,117 +586,96 @@ impl<K: HashKey, S: StateStore, const T: JoinTypePrimitive> TemporalJoinExecutor
...
-                            if let Some(chunk) = builder.take() {
-                                let row_matched =
-                                    std::mem::take(&mut row_matched_bitmap_builder).finish();
-                                yield (chunk, row_matched);
-                            }
+                    let epoch = prev_epoch.expect("Chunk data should come after some barrier.");
+
+                    let full_schema = full_schema.clone();
+
+                    if T == JoinType::Inner {
```
Comment (chenzl25) [inline src/stream/src/executor/temporal_join.rs:593]: It seems it didn't handle the case of inner join with other conditions.

Comment (TennyZhuang) [reply src/stream/src/executor/temporal_join.rs:593]: Good point, forget to handle that

Comment (TennyZhuang) [reply src/stream/src/executor/temporal_join.rs:593]: In fact, inner join with cond can be optimized to a normal `WHERE` clause. But I can handle it here first.

**Comment by TennyZhuang** [comment]
@chenzl25 Fixed, PTAL

**Review by chenzl25 — APPROVED** [review]
LGTM! thanks!

File: src/stream/src/executor/temporal_join.rs [hunk 2]
```diff
@@ -310,6 +309,170 @@ async fn align_input(left: Executor, right: Executor) {
...
+            op: Op,
+            left_row: impl Row,
+            right_size: usize,
+            matched: bool,
+        ) -> Option<StreamChunk>;
+    }
+
+    pub(super) struct Inner;
+    pub(super) struct LeftOuter;
+    pub(super) struct LeftOuterWithCond;
```
Comment (stdrc) [inline src/stream/src/executor/temporal_join.rs:348]: 😄 Looks really similar to https://github.com/risingwavelabs/risingwave/blob/8ea55a038514b4be7bdd4cc97c49016b5eb4b564/src/stream/src/executor/aggregation/agg_group.rs#L36-L51

I slightly prefer naming the structs by their immediate semantics instead of the join modes. However it's not a strong opinion, up to you😄

**Review by stdrc — APPROVED** [review]
