### PR TITLE
feat: fix internal table id in replace_table

### LINKED ISSUE #11565: Bug: panic when alter append only table with watermark
```SQL
dev=> create table t (
    tm timestamp,
    watermark for tm as tm - interval '5 seconds'
) append only;
NOTICE:  APPEND ONLY TABLE is currently an experimental feature.
CREATE_TABLE
dev=> alter table t add a int;
ERROR:  QueryError: internal error: transport error
```

meta log:
```
thread 'risingwave-main' panicked at 'assertion failed: fragment_graph.internal_tables().is_empty()', src/meta/src/rpc/ddl_controller.rs:746:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by wugouzi**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
As title. Close #11565.

## Checklist

- [x] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by st1page — COMMENTED** [review]
We can be more strict here to check each table's schema

**Comment by wugouzi** [comment]
> We can be more strict here to check each table's schema

Are two tables with same schema the same table?

**Comment by st1page** [comment]
> > We can be more strict here to check each table's schema
> 
> Are two tables with same schema the same table?

Currently, the internal tables with the same table id should has same schema :thinking:

File: src/meta/src/stream/stream_graph/fragment.rs [hunk 1]
```diff
@@ -273,6 +274,7 @@ impl StreamFragmentGraph {
         let fragments: HashMap<_, _> = proto
             .fragments
             .into_iter()
+            .sorted_by(|a, b| a.0.cmp(&b.0))
```
Comment (BugenZhao) [inline src/meta/src/stream/stream_graph/fragment.rs:277]: May I ask why do we need this?

File: src/meta/src/stream/stream_graph/fragment.rs [hunk 2]
```diff
@@ -345,6 +347,39 @@ impl StreamFragmentGraph {
...
+    //    which is fixed.
+    /// Set internal tables' `table_id`s according to a list of internal tables
+    pub fn fit_internal_table_ids(&mut self, mut old_tables: Vec<Table>) -> MetaResult<()> {
+        let mut new_ids = Vec::new();
+        for fragment in self.fragments.values() {
+            for table in &fragment.internal_tables {
+                new_ids.push(table.id);
+            }
+        }
+        assert_eq!(new_ids.len(), old_tables.len());
```
Comment (BugenZhao) [inline src/meta/src/stream/stream_graph/fragment.rs:366]: I guess it'll be better to make this assertion an internal error.

File: src/meta/src/stream/stream_graph/fragment.rs [hunk 3]
```diff
@@ -345,6 +347,39 @@ impl StreamFragmentGraph {
...
+        old_tables.sort_by(|a, b| a.id.cmp(&b.id));
+        new_ids.sort();
+        let id_map = new_ids
+            .into_iter()
+            .zip_eq_fast(old_tables.into_iter())
+            .collect::<HashMap<_, _>>();
+        for fragment in self.fragments.values_mut() {
+            for table in &mut fragment.internal_tables {
+                let old_table = id_map.get(&table.id).unwrap();
+                assert_eq!(old_table.get_columns(), table.get_columns());
```
Comment (BugenZhao) [inline src/meta/src/stream/stream_graph/fragment.rs:376]: Ditto

File: src/meta/src/stream/stream_graph/fragment.rs (hunk 1 above)
Comment (wugouzi) [reply src/meta/src/stream/stream_graph/fragment.rs:277]: Because iiuc iter visits pairs in arbitrary order. By this sort, we can fill internal table ids in a controlled way, only after which we can build a one-to-one correspondence between the internal table ids.

Comment (BugenZhao) [reply src/meta/src/stream/stream_graph/fragment.rs:277]: Hmmm. It looks like `table_id_gen` does not rely on the order it's called. All it does is add an offset to the local ID generated by the **frontend**. 🤔

Comment (wugouzi) [reply src/meta/src/stream/stream_graph/fragment.rs:277]: Yeah, you are right. I misunderstand it.

**Review by BugenZhao — APPROVED** [review]

File: src/meta/src/stream/stream_graph/fragment.rs [hunk 4]
```diff
@@ -345,6 +346,53 @@ impl StreamFragmentGraph {
...
+                new_ids.push(table.id);
+            }
+        }
+        if new_ids.len() != old_tables.len() {
+            return Err(MetaError::from(anyhow!(
+                "Different number of internal tables.\n
+                New: {}, Old: {}",
+                new_ids.len(),
+                old_tables.len(),
+            )));
```
Comment (BugenZhao) [inline src/meta/src/stream/stream_graph/fragment.rs:363]: We may simply use `bail!` here. :)
