### PR TITLE
fix(frontend): dedup column ids (close #7905)

### LINKED ISSUE #7905: bug: unable to run mv query when it's a protobuf source
### Describe the bug

```
thread 'thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at '' panicked at 'assertion failed: self.remaining() >= dst.len()assertion failed: self.remaining() >= dst.len()assertion failed: self.remaining() >= dst.len()', ', ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:::254254254:::999


stack backtrace:
thread 'risingwave-streaming-actor' panicked at 'assertion failed: self.remaining() >= dst.len()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:254:9
   0: rust_begin_unwind
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:114:5
   3: bytes::buf::buf_impl::Buf::copy_to_slice
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:254:9
   4: <&mut T as bytes::buf::buf_impl::Buf>::copy_to_slice
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:1220:13
   5: risingwave_common::util::value_encoding::deserialize_str
             at ./risingwave/src/common/src/util/value_encoding/mod.rs:187:5
   6: risingwave_common::util::value_encoding::deserialize_value
             at ./risingwave/src/common/src/util/value_encoding/mod.rs:149:47
   7: risingwave_common::util::value_encoding::inner_deserialize_datum
             at ./risingwave/src/common/src/util/value_encoding/mod.rs:62:19
   8: risingwave_common::util::value_encoding::deserialize_datum
             at ./risingwave/src/common/src/util/value_encoding/mod.rs:53:5
   9: risingwave_common::row::owned_row::RowDeserializer<D>::deserialize
             at ./risingwave/src/common/src/row/owned_row.rs:154:25
  10: risingwave_storage::table::batch_table::storage_table::StorageTableIterInner<S>::into_stream::{{closure}}
             at ./risingwave/src/storage/src/table/batch_table/storage_table.rs:692:28
  11: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  12: <risingwave_storage::table::batch_table::storage_table::StorageTable<S>::iter_with_encoded_key_range::{{closure}}::__Enum6710908321195091250<__Variant0,__Variant1,__Variant2> as futures_core::stream::Stream>::poll_next
             at ./risingwave/src/storage/src/table/batch_table/storage_table.rs:451:9
  13: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  14: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  15: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  16: risingwave_storage::table::batch_table::storage_table::<impl risingwave_storage::table::TableIter for S>::next_row::{{closure}}
             at ./risingwave/src/storage/src/table/batch_table/storage_table.rs:361:13
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/future/future.rs:125:9
  18: risingwave_storage::table::TableIter::collect_data_chunk::{{closure}}
             at ./risingwave/src/storage/src/table/mod.rs:82:34
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/future/future.rs:125:9
  20: <async_stack_trace::StackTraced<F,_> as core::future::future::Future>::poll
             at ./risingwave/src/utils/async_stack_trace/src/lib.rs:182:23
  21: risingwave_stream::executor::backfill::BackfillExecutor<S>::snapshot_read::{{closure}}
             at ./risingwave/src/stream/src/executor/backfill.rs:328:14
  22: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  23: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  24: <S as futures_core::stream::TryStream>::try_poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:196:9
  25: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/try_stream/mod.rs:1002:9
  26: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/try_stream/try_next.rs:32:9
  27: risingwave_stream::executor::backfill::BackfillExecutor<S>::execute_inner::{{closure}}
             at ./risingwave/src/stream/src/executor/backfill.rs:125:33
  28: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  29: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  30: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  31: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  32: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  33: risingwave_stream::executor::wrapper::trace::metrics::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/trace.rs:83:44
  34: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  35: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  36: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  37: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  38: <async_stack_trace::StackTraced<F,_> as core::future::future::Future>::poll
             at ./risingwave/src/utils/async_stack_trace/src/lib.rs:182:23
  39: risingwave_stream::executor::wrapper::trace::stack_trace::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/trace.rs:120:70
  40: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  41: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  42: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  43: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  44: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/epoch_check.rs:31:44
  45: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  46: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  47: risingwave_stream::executor::simple::SimpleExecutorWrapper<E>::execute_inner::{{closure}}
             at ./risingwave/src/stream/src/executor/simple.rs:73:5
  48: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  49: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  50: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  51: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  52: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  53: risingwave_stream::executor::wrapper::trace::metrics::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/trace.rs:83:44
  54: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  55: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  56: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  57: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  58: <async_stack_trace::StackTraced<F,_> as core::future::future::Future>::poll
             at ./risingwave/src/utils/async_stack_trace/src/lib.rs:182:23
  59: risingwave_stream::executor::wrapper::trace::stack_trace::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/trace.rs:120:70
  60: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  61: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  62: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  63: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/next.rs:32:9
  64: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./risingwave/src/stream/src/executor/wrapper/epoch_check.rs:31:44
  65: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  66: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  67: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./risingwave/src/stream/src/executor/dispatch.rs:258:9
  68: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
  69: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  70: <&mut S as futures_core::stream::Stream>::poll_next
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:104:9
  71: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.11/src/stream_ext/next.rs:42:9
  72: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  73: <async_stack_trace::StackTraced<F,_> as core::future::future::Future>::poll
             at ./risingwave/src/utils/async_stack_trace/src/lib.rs:182:23
  74: risingwave_stream::executor::actor::Actor<C>::run_consumer::{{closure}}
             at ./risingwave/src/stream/src/executor/actor.rs:164:13
  75: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/future/maybe_done.rs:68:48
  76: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/join.rs:126:24
  77: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/future/poll_fn.rs:58:9
  78: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./risingwave/src/stream/src/executor/actor.rs:131:9
  79: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}::{{closure}}
             at ./risingwave/src/stream/src/task/stream_manager.rs:653:50
  80: async_stack_trace::manager::TraceReporter::trace::{{closure}}::{{closure}}::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/select.rs:517:49
  81: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/future/poll_fn.rs:58:9
  82: async_stack_trace::manager::TraceReporter::trace::{{closure}}::{{closure}}
             at ./risingwave/src/utils/async_stack_trace/src/manager.rs:124:21
  83: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:348:35
  84: tokio::task::task_local::LocalKey<T>::scope_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:233:19
  85: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:345:13
  86: async_stack_trace::manager::TraceReporter::trace::{{closure}}
             at ./risingwave/src/utils/async_stack_trace/src/manager.rs:131:13
  87: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/either.rs:109:32
  88: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  89: task_stats_alloc::allocation_stat::{{closure}}::{{closure}}::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/select.rs:517:49
  90: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/future/poll_fn.rs:58:9
  91: task_stats_alloc::allocation_stat::{{closure}}::{{closure}}
             at ./risingwave/src/utils/task_stats_alloc/src/lib.rs:124:26
  92: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:348:35
  93: tokio::task::task_local::LocalKey<T>::scope_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:233:19
  94: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/task_local.rs:345:13
  95: task_stats_alloc::allocation_stat::{{closure}}
             at ./risingwave/src/utils/task_stats_alloc/src/lib.rs:131:9
  96: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  97: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  98: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  99: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
 100: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
 101: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panic/unwind_safe.rs:271:9
 102: std::panicking::try::do_call
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:483:40
 103: std::panicking::try
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:447:19
 104: std::panic::catch_unwind
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panic.rs:140:14
 105: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
 106: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
 107: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
 108: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
 109: tokio::runtime::task::LocalNotified<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
 110: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
 111: tokio::runtime::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
 112: tokio::runtime::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
 113: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
 114: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
 115: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
 116: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
 117: tokio::runtime::scheduler::multi_thread::worker::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
 118: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
 119: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
 120: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
 121: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
 122: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
 123: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
 124: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
 125: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panic/unwind_safe.rs:271:9
 126: std::panicking::try::do_call
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:483:40
 127: std::panicking::try
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:447:19
 128: std::panic::catch_unwind
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panic.rs:140:14
 129: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
 130: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
 131: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
 132: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
 133: tokio::runtime::task::UnownedTask<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
 134: tokio::runtime::blocking::pool::Task::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
 135: tokio::runtime::blocking::pool::Inner::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17


*** async stack trace context of current task ***

Actor 25: `CREATE MATERIALIZED VIEW total_user_visit_1min AS SELECT window_start AS report_ts, COUNT(DISTINCT user_id) AS uv FROM TUMBLE(live_stream_metrics, report_timestamp, INTERVAL '1' MINUTE) GROUP BY window_start` [3.953000002s]
  Epoch <initial> [!!! 3.953000002s]
    ProjectExecutor 1900000068 (actor 25, executor 104) [!!! 3.953000002s]
      BackfillExecutor (actor 25, executor 102) [!!! 3.953000002s]
        backfill_snapshot_read [!!! 3.948000002s]  <== current


 136: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

You can either reproduce manually or automatically via Docker Compose:

**To run manually:**

1, `./risedev p` Start the RisingWave server.
2, `rpk container start` Start a Kafka.
3, Clone https://github.com/risingwavelabs/risingwave-demo.git and cd to the livestream directory:
4, `python3 -m http.server 8000` Start a static file server at port 8000.
5, Download the datagen release binary that's suitable for your platform: https://github.com/risingwavelabs/risingwave-demo/releases/tag/v1.0.10
6, Run datagen: `./datagen --format protobuf --mode livestream --qps 2 kafka --brokers message_queue:29092` (replace 'message_queue:29092' with your kafka addresses)

**To run automatically:**

To run the services using Docker Compose (recommended as it's simpler), you can create a file called `docker-compose.yml` with the following content:

```
---
version: "3"
services:
  risingwave:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - playground
    expose:
      - "4566"
    ports:
      - "4566:4566"
    environment:
      RUST_BACKTRACE: "1"
    container_name: risingwave
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5
  message_queue:
    image: docker.redpanda.com/vectorized/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://message_queue:29092,OUTSIDE://localhost:9092
    ports:
      - 29092:29092
    container_name: message_queue
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9092
      interval: 1s
      timeout: 5s
      retries: 5
  datagen:
    image: ghcr.io/risingwavelabs/demo-datagen:v1.0.10
    depends_on: [message_queue]
    command:
      - /bin/sh
      - -c
      - /datagen --format protobuf --mode livestream --qps 2 kafka --brokers message_queue:29092
    restart: always
    container_name: datagen
  file_server:
    image: halverneus/static-file-server:latest
    volumes:
      - "./:/demo"
    restart: always
    environment:
      FOLDER: /demo
    container_name: file_server
volumes:
  message_queue:
    external: false
name: risingwave-compose
```

You will also need to download https://github.com/risingwavelabs/risingwave-demo/blob/main/livestream/schema this in the same directory with docker-compose.yml.

Either way, you will need to type the following SQL commands:

```sql
CREATE SOURCE live_stream_metrics_pb WITH (
    connector = 'kafka',
    topic = 'live_stream_metrics',
    properties.bootstrap.server = 'message_queue:29092',
    scan.startup.mode = 'earliest'
) ROW FORMAT PROTOBUF MESSAGE 'livestream.schema.LiveStreamMetrics' ROW SCHEMA LOCATION 'http://file_server:8080/schema';

CREATE MATERIALIZED VIEW live_stream_metrics AS
SELECT
    client_ip,
    user_agent,
    user_id,
    room_id,
    video_bps,
    video_fps,
    video_rtt,
    video_lost_pps,
    video_longest_freeze_duration,
    video_total_freeze_duration,
    to_timestamp(report_timestamp) as report_timestamp,
    country
FROM
    live_stream_metrics_pb;

CREATE MATERIALIZED VIEW total_user_visit_1min AS
SELECT
    window_start AS report_ts,
    COUNT(DISTINCT user_id) as uv
FROM
    TUMBLE(
        live_stream_metrics,
        report_timestamp,
        INTERVAL '1' MINUTE
    )
GROUP BY
    window_start;
```

The query always failed in the second MV. I've confirmed that it's not an Mv-on-Mv issue because when I changed the "source" to "table", the first MV `live_stream_metrics` still worked. 

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

dedup column ids (close #7905)

## Checklist

- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/common/src/catalog/column.rs [hunk 1]
```diff
@@ -291,6 +297,25 @@ impl ColumnCatalog {
     }
 }
 
+pub fn columns_extend(preserved_columns: &mut Vec<ColumnCatalog>, columns: Vec<ColumnCatalog>) {
```
Comment (BugenZhao) [inline src/common/src/catalog/column.rs:300]: Does `ColumnIdGenerator` help here? See `check_and_add_timestamp_column`.

Comment (soundOfDestiny) [reply src/common/src/catalog/column.rs:300]: > Does `ColumnIdGenerator` help here? See `check_and_add_timestamp_column`.

We wish proto columns would remain their own ids invariant

**Comment by tabVersion** [comment]
Can you explain further how the bug is introduced?

**Comment by soundOfDestiny** [comment]
> Can you explain further how the bug is introduced?

`build_stream_source_reader`, which is called in `SourceExecutor`, cannot accept duplicate column ids:
```
async fn build_stream_source_reader(
        &self,
        source_desc: &SourceDesc,
        state: ConnectorState,
    ) -> StreamExecutorResult<BoxSourceWithStateStream> {
let column_ids = source_desc
            .columns
            .iter()
            .map(|column_desc| column_desc.column_id)
            .collect_vec();
```

**Review by tabVersion — APPROVED** [review]
don't get why column_ids will duplicate but the solution LGTM

**Comment by soundOfDestiny** [comment]
> don't get why column_ids will duplicate but the solution LGTM

because `_rw_kafka_timestamp` field is added recently, which is assigned column id #1 in `check_and_add_timestamp_column`, and it duplicates with the first field in protobuf

**Comment by BugenZhao** [comment]
By not using the `ColumnIdGenerator`, we'll get wrong `next_column_id`, which is required to support adding columns of schema change.

https://github.com/risingwavelabs/risingwave/blob/966d2900efa06ecdd7cdd0062f43997fd5a863b8/src/frontend/src/handler/create_table.rs#L107-L113

> We wish proto columns would remain their own ids invariant

Is this something we assume in another part of RisingWave?

**Comment by soundOfDestiny** [comment]
> By not using the `ColumnIdGenerator`, we'll get wrong `next_column_id`, which is required to support adding columns of schema change.
> 
> https://github.com/risingwavelabs/risingwave/blob/966d2900efa06ecdd7cdd0062f43997fd5a863b8/src/frontend/src/handler/create_table.rs#L107-L113
> 
> > We wish proto columns would remain their own ids invariant
> 
> Is this something we assume in another part of RisingWave?

I'm not sure but I guess not. Feel free to refactor 😄

**Comment by BugenZhao** [comment]
> > We wish proto columns would remain their own ids invariant
> 
> Is this something we assume in another part of RisingWave?

cc @tabVersion 🥺
