### PR TITLE
fix(common): ignore field ids when comparing `struct` for backward compatibility

### LINKED ISSUE #22041: bug: `sink into table` always fail on `struct` column equality check
### Describe the bug

For `sink into table` we require the upstream streaming job to have same data type with the downstream table. However the equality on `struct` data type always fail due to internal invisible differences - even when the field names and data types match.

`lhs.equals_datatype(rhs)` shall be used instead of `lhs == rhs`

https://github.com/risingwavelabs/risingwave/blob/ad53aac274f297f4b6cb72b116641b2d7c9ed8ff/src/frontend/src/handler/create_sink.rs#L660-L669

### Error message/log

```text
ERROR:  Failed to run the query

Caused by:
  column type mismatch: Struct(StructType { fields: [("foo", Int32)] }) vs Struct(StructType { fields: [("foo", Int32)] }), column name: "$expr10001"
```

### To Reproduce

```sql
create table t (f1 struct<foo int>);
create sink sk into t as select row(3)::struct<foo int> as f1;
```

### Expected behavior

The sink shall be created successfully.

Note that as sink-into-table is working within SQL rather than to an external system, it matches fields by position rather than by name. For example, `struct<a int, b real>` does not match `struct<b real, a int>`.

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

2.4.0

### Additional context

Tables or sinks created before upgrading to 2.4.0 are not affected. They do not have field ids assigned and the struct cannot be altered.

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Fixes #22041.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/common/src/types/struct_type.rs [hunk 1]
```diff
@@ -45,7 +45,7 @@ impl Debug for StructType {
     }
 }
 
-#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
+#[derive(Clone, Debug, PartialOrd, Ord)]
```
Comment (BugenZhao) [inline src/common/src/types/struct_type.rs:48]: We may also override the derived impl of `Ord`. The behavior should be consistent with `Eq`.

File: src/common/src/types/struct_type.rs [hunk 2]
```diff
@@ -63,6 +63,18 @@ struct StructTypeInner {
...
+    fn eq(&self, other: &Self) -> bool {
+        self.fields == other.fields
+    }
+}
+impl Eq for StructTypeInner {}
+impl std::hash::Hash for StructTypeInner {
+    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
+        self.fields.hash(state);
+    }
+}
```
Comment (BugenZhao) [inline src/common/src/types/struct_type.rs]: Shall we use `#[educe(PartialEq(ignore), Hash(ignore))]`, and add some explicit comments?
