### PR TITLE
fix(values): fix pk indices and output watermark cols of StreamValues

### LINKED ISSUE #10879: bug: min/max over StreamValues panic: the order columns must appear in the state table
### Describe the bug

_No response_

### Error message/log

```text
thread 'risingwave-streaming-actor' panicked at 'the order columns must appear in the state table', /Users/xiangjin/primary/risingwave-dev/src/stream/src/executor/aggregation/minput.rs:129:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:1932:5
   5: core::option::Option<T>::expect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:898:21
   6: risingwave_stream::executor::aggregation::minput::MaterializedInputState<S>::new::{{closure}}
             at ./src/stream/src/executor/aggregation/minput.rs:127:17
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
  11: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  12: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  17: itertools::Itertools::collect_vec
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:9
  18: risingwave_stream::executor::aggregation::minput::MaterializedInputState<S>::new
             at ./src/stream/src/executor/aggregation/minput.rs:124:45
  19: risingwave_stream::executor::aggregation::agg_state::AggState<S>::create::{{closure}}
             at ./src/stream/src/executor/aggregation/agg_state.rs:97:41
  20: <F as futures_core::future::TryFuture>::try_poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
  21: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_future/into_future.rs:34:9
  22: <F as futures_core::future::TryFuture>::try_poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
  23: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_maybe_done.rs:79:57
  24: <F as futures_core::future::TryFuture>::try_poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
  25: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_join_all.rs:162:27
  26: risingwave_stream::executor::aggregation::agg_group::AggGroup<S,Strtg>::create::{{closure}}
             at ./src/stream/src/executor/aggregation/agg_group.rs:226:14
  27: risingwave_stream::executor::simple_agg::SimpleAggExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/simple_agg.rs:304:14
  28: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  29: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  30: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  31: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  32: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  33: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:124:23
  34: risingwave_stream::executor::wrapper::trace::instrument_await_tree::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:100:10
  35: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  36: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:24:1
  37: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  38: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  39: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  40: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  41: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_check.rs:31:44
  42: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  43: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  44: <S as futures_core::stream::TryStream>::try_poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:196:9
  45: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/mod.rs:1068:9
  46: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/try_next.rs:32:9
  47: risingwave_stream::executor::wrapper::epoch_provide::epoch_provide::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_provide.rs:33:26
  48: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  49: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  50: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  51: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  52: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  53: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:46:69
  54: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  55: risingwave_stream::executor::wrapper::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/wrapper/update_check.rs:27:1
  56: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  57: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  58: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  59: risingwave_stream::executor::project::Inner::execute::{{closure}}
             at ./src/stream/src/executor/project.rs:169:5
  60: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  61: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  62: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  63: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  64: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  65: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:124:23
  66: risingwave_stream::executor::wrapper::trace::instrument_await_tree::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:100:10
  67: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  68: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:24:1
  69: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  70: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  71: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  72: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  73: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_check.rs:31:44
  74: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  75: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  76: <S as futures_core::stream::TryStream>::try_poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:196:9
  77: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/mod.rs:1068:9
  78: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/try_next.rs:32:9
  79: risingwave_stream::executor::wrapper::epoch_provide::epoch_provide::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_provide.rs:33:26
  80: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  81: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  82: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  83: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  84: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  85: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:46:69
  86: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  87: risingwave_stream::executor::wrapper::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/wrapper/update_check.rs:27:1
  88: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  89: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


*** await tree context of current task ***

Actor 227: `CREATE MATERIALIZED VIEW mv AS SELECT min(1)` [961.360ms]
  Epoch <initial> [960.192ms]
    MaterializeExecutor E300000003 (actor 227, operator 3) [960.027ms]
      expect_first_barrier [960.027ms]
        ProjectExecutor E300000002 (actor 227, operator 2) [960.027ms]
          SimpleAggExecutor-E300000001 (actor 227, operator 1) [960.027ms]  <== current
```

### To Reproduce

```
create materialized view mv as select min(1);
```

### Expected behavior

Works just like `sum`:

```
create materialized view mv as select sum(1);
```

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

min/max over a normal table is okay

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #10879.

## Checklist

- ~~[ ] I have written necessary rustdoc comments~~
- ~~[ ] I have added necessary unit tests and integration tests~~
- ~~[ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
- ~~[ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- ~~[ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)~~

- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details]~~(https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- ~~[ ] My PR contains user-facing changes.~~

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/stream_values.rs [hunk 1]
```diff
@@ -37,17 +37,15 @@ impl StreamValues {
...
         let ctx = logical.ctx();
-        let mut watermark_columns = FixedBitSet::with_capacity(logical.schema().len());
-        (0..(logical.schema().len() - 1)).for_each(|i| watermark_columns.set(i, true));
         let base = PlanBase::new_stream(
             ctx,
             logical.schema().clone(),
             logical.logical_pk().to_vec(),
             logical.functional_dependency().clone(),
             Distribution::Single,
+            true,
```
Comment (stdrc) [inline src/frontend/src/optimizer/plan_node/stream_values.rs:46]: `append_only`

File: src/frontend/src/optimizer/plan_node/stream_values.rs [hunk 2]
```diff
@@ -37,17 +37,15 @@ impl StreamValues {
     /// `StreamValues` should enforce `Distribution::Single`
     pub fn new(logical: LogicalValues) -> Self {
         let ctx = logical.ctx();
-        let mut watermark_columns = FixedBitSet::with_capacity(logical.schema().len());
-        (0..(logical.schema().len() - 1)).for_each(|i| watermark_columns.set(i, true));
```
Comment (BugenZhao) [inline src/frontend/src/optimizer/plan_node/stream_values.rs:41]: This is semantically correct for a bounded operator, but I'm not sure whether it's useful. 🤔

**Review by BugenZhao — APPROVED** [review]
