### PR TITLE
fix(batch): make batch range scan sequentially to avoid OOM

### LINKED ISSUE #15636: Batch query with large filter condition, upstream MV with lots of keys fails with CN OOM
## Repro Scripts

[create.sql.log](https://github.com/risingwavelabs/risingwave/files/14569335/create.sql.log)
[insert.sql.log](https://github.com/risingwavelabs/risingwave/files/14569337/insert.sql.log)
[query.sql.log](https://github.com/risingwavelabs/risingwave/files/14569339/query.sql.log)

python script to generate these: https://github.com/kwannoel/risingwave-dev-scripts/blob/main/wide_table.py.

You can generate versions to stdout with less row and columns to easily see the structure of the sql.

e.g.
```
# view usage
./wide_table.py
./wide_table.py create 4
./wide_table.py insert 3 3
```

You can also use `explain` on the batch query (`query.sql.log`)

## Repro steps

```
./risedev d full
# open localhost:3001, look at CN memory usage
psql -f create.sql.log
psql -f insert.sql.log
psql -f query.sql.log
# mem usage should spike
```

## Observations

1. Halving the number of filter conditions also halves the mem usage.
2. Can try varying the PK as well.

## Suggested next steps

Get a heap profile

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #15636

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [x] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM!

File: src/batch/src/executor/row_seq_scan.rs [hunk 1]
```diff
@@ -319,28 +318,28 @@ impl<S: StateStore> RowSeqScanExecutor<S> {
...
-        let range_scans = select_all(range_scans.into_iter().map(|range_scan| {
-            let table = table.clone();
-            let histogram = histogram.clone();
-            Box::pin(Self::execute_range(
-                table,
-                range_scan,
+        // WARN: DO NOT use `select` to execute range scans concurrently
+        //       it can consume too much memory if there're too many ranges.
+        for range in range_scans {
+            let stream = Self::execute_range(
```
Comment (kwannoel) [inline src/batch/src/executor/row_seq_scan.rs:324]: Not sure if it should be a default. I'm thinking a session variable can easily enable / disable this feature.

Comment (kwannoel) [reply src/batch/src/executor/row_seq_scan.rs:324]: Perhaps we can do something like:
if range_scans.len() > some_arbitrary_threshold, 
then do sequential. Else do parallel.

Comment (chenzl25) [reply src/batch/src/executor/row_seq_scan.rs:324]: Make it default LGTM. Previously, point-lookup is also performed concurrently, but I changed it to sequential, because lookup-join encountered a similar issue as well.
