### PR TITLE
fix(hummock manager): preserve SST order in `commit_epoch` (close #8875)

### LINKED ISSUE #8875: storage: preserve order of SSTs in `commit_epoch`
### Describe the bug

as title

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix(hummock manager): preserve SST order in `commit_epoch`

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/meta/src/hummock/manager/mod.rs [hunk 1]
```diff
@@ -1388,39 +1388,47 @@ where
                         == sst.get_table_ids().len();
                 if is_trivial_adjust {
                     *compaction_group_id = *group_table_ids.first_key_value().unwrap().0;
-                    is_sst_belong_to_group_declared = true;
+                    // is_sst_belong_to_group_declared = true;
```
Comment (zwang28) [inline src/meta/src/hummock/manager/mod.rs:1391]: nit:

**Review by zwang28 — APPROVED** [review]

File: src/meta/src/hummock/manager/mod.rs (hunk 1 above)
Comment (soundOfDestiny) [reply src/meta/src/hummock/manager/mod.rs:1391]: > nit:

This is deliberate in case someone may use this `is_sst_belong_to_group_declared` in the future.
