### PR TITLE
fix(binder): don't error when search_path is empty

### LINKED ISSUE #11470: pg_dump failed on catalog resolution
### Describe the bug

_No response_

### Error message/log

```text
pg_dump: error: query failed: ERROR:  QueryError: Bind error: failed to bind expression: pg_catalog.pg_is_in_recovery()

Caused by:
  Catalog error: first valid schema not found: no schema has been selected to create in
pg_dump: detail: Query was: SELECT pg_catalog.pg_is_in_recovery()
```

### To Reproduce

```
pg_dump --username=root --no-password --host=127.0.0.1 --port=4566  dev
```

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TennyZhuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #11470 

The PR includes a minor fix, which is not the root cause.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/common/src/session_config/search_path.rs [hunk 1]
```diff
@@ -68,7 +68,10 @@ impl TryFrom<&[&str]> for SearchPath {
     fn try_from(value: &[&str]) -> Result<Self, Self::Error> {
         let mut real_path = vec![];
         for p in value {
-            real_path.push(p.trim().to_string());
+            let p = p.trim();
+            if !p.is_empty() {
+                real_path.push(p.to_string());
+            }
```
Comment (TennyZhuang) [inline src/common/src/session_config/search_path.rs:74]: Just a minor fix including in the PR, not the real root cause.

**Review by yezizp2012 — APPROVED** [review]

File: src/common/src/session_config/search_path.rs (hunk 1 above)
Comment (st1page) [reply src/common/src/session_config/search_path.rs:74]: should leave some comments here with the issue's URL?

**Review by st1page — APPROVED** [review]
