### PR TITLE
fix(binder): ignore hidden column for natural join

### LINKED ISSUE #10617: bug(binder): natural join should ignore the hidden columns
thanks @stdrc find the bug

```SQL
dev=> create table t(v int);
CREATE_TABLE
dev=> create materialized view mv1 as select v from t where v > 10;
CREATE_MATERIALIZED_VIEW
dev=> create materialized view mv2 as select v from t where v < 10;
CREATE_MATERIALIZED_VIEW
dev=> explain select * from mv1 natural join mv2;
                                          QUERY PLAN                                           
-----------------------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchLookupJoin { type: Inner, predicate: mv1.t._row_id = mv2.t._row_id AND mv1.v = mv2.v }
   └─BatchExchange { order: [], dist: UpstreamHashShard(mv1.t._row_id) }
     └─BatchScan { table: mv1, columns: [v, t._row_id] }
(4 rows)
```

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #10617.

## Checklist

- ~~[ ] I have written necessary rustdoc comments~~
- [x] I have added necessary unit tests and integration tests
- ~~[ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
- ~~[ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- ~~[ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)~~

- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details]~~(https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- ~~[ ] My PR contains user-facing changes.~~

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]

File: src/frontend/src/binder/relation/join.rs [hunk 1]
```diff
@@ -141,7 +141,7 @@ impl Binder {
                     .context
                     .indices_of
                     .iter()
-                    .filter(|(s, _)| *s != "_row_id") // filter out `_row_id`
```
Comment (BugenZhao) [inline src/frontend/src/binder/relation/join.rs:144]: 😄😄😄😄😄

**Review by BugenZhao — APPROVED** [review]

File: src/frontend/src/binder/relation/join.rs (hunk 1 above)
Comment (xiangjinwu) [inline src/frontend/src/binder/relation/join.rs:144]: So the name is `t._row_id` in this test case and was not filtered out as expected. Do we have other places checking for `_row_id` instead of `is_hidden`?

**Review by xiangjinwu — APPROVED** [review]
