### PR TITLE
fix(streaming): use correct dist key in pk in state table for hash join

### LINKED ISSUE #7698: panicked at `vnode 151 should not be accessed by this table`
### Describe the bug

```
create table t (src int, dst int);

create materialized view cycle_3 as
select t1.src p1, t1.dst p2, t2.dst p3 from
t t1 join t t2 join t t3 where t1.dst = t2.src and t2.src = t3.dst and t3.dst = t1.src;

insert into t values (1, 2), (2, 1);
flush;
```

```
 StreamMaterialize { columns: [p1, p2, p3, t._row_id(hidden), t._row_id#1(hidden), t.src(hidden), t._row_id#2(hidden), t.dst(hidden)], pk_columns: [t._row_id, t._row_id#1, p2, t.src, t._row_id#2, t.dst, p1] }
 └─StreamHashJoin { type: Inner, predicate: t.src = t.dst AND t.src = t.dst }
   ├─StreamExchange { dist: HashShard(t.src) }
   | └─StreamHashJoin { type: Inner, predicate: t.dst = t.src }
   |   ├─StreamExchange { dist: HashShard(t.dst) }
   |   | └─StreamTableScan { table: t, columns: [src, dst, _row_id] }
   |   └─StreamExchange { dist: HashShard(t.src) }
   |     └─StreamTableScan { table: t, columns: [src, dst, _row_id] }
   └─StreamExchange { dist: HashShard(t.dst) }
     └─StreamTableScan { table: t, columns: [dst, _row_id] }
(10 rows)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- use correct dist key in pk in state table for hash join

#8377
close #7698

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/frontend/src/catalog/table_catalog.rs [hunk 1]
```diff
@@ -122,8 +122,11 @@ pub struct TableCatalog {
     /// Per-table catalog version, used by schema change. `None` for internal tables and tests.
     pub version: Option<TableVersion>,
 
-    /// the column indices which could receive watermarks.
+    /// The column indices which could receive watermarks.
     pub watermark_columns: FixedBitSet,
+
+    /// The distribution key indices in pk
```
Comment (st1page) [inline src/frontend/src/catalog/table_catalog.rs:128]:
```suggestion
    /// Optional field specifies the distribution key indices in pk. See https://github.com/risingwavelabs/risingwave/issues/8377 for more information.
```

File: e2e_test/streaming/bug_fixes/issue_7698.slt [hunk 2]
```diff
@@ -0,0 +1,19 @@
+# https://github.com/risingwavelabs/risingwave/issues/7698
+
+statement ok
+SET RW_IMPLICIT_FLUSH TO true;
+
+statement ok
+create table t (src int, dst int);
+
+statement ok
+create materialized view cycle_3 as select t1.src p1, t1.dst p2, t2.dst p3 from t t1, t t2, t t3 where t1.dst = t2.src and t2.src = t3.dst and t3.dst = t1.src;
```
Comment (st1page) [inline e2e_test/streaming/bug_fixes/issue_7698.slt:10]: add it to the planner test?

File: src/frontend/src/optimizer/plan_node/stream_hash_join.rs [hunk 3]
```diff
@@ -145,6 +146,27 @@ impl StreamHashJoin {
...
+
+        for (l_dk_idx, r_dk_idx) in left_dk_indices.iter().zip_eq_fast(right_dk_indices.iter()) {
+            for dk_idx_in_jk in left_jk_indices.iter().positions(|idx| idx == l_dk_idx) {
+                if right_jk_indices[dk_idx_in_jk] == *r_dk_idx {
+                    dk_indices_in_jk.push(dk_idx_in_jk);
+                    break;
+                }
+            }
+        }
+        dk_indices_in_jk
```
Comment (st1page) [inline src/frontend/src/optimizer/plan_node/stream_hash_join.rs:168]:
```suggestion
        assert_eq!(dk_indices_in_jk.len(), left_dk_indices.len());
        dk_indices_in_jk
```

**Review by st1page — APPROVED** [review]
LGTM!
