### PR TITLE
fix: fix missing rewrite of table fragments during migration to sql backend

### LINKED ISSUE #19808: bug: secret refer informations in table fragments are NOT rewrite during migration to SQL backend
### Describe the bug

_No response_

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### LINKED ISSUE #19825: bug: some dirty states of catalog in table fragments breaks the sql migration
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/7c389f1486b93198d64ba7af1cee776cfa41020d/src/ctl/src/cmd_impl/meta/migration.rs#L465

This should be the result of having executed `alter set schema`, and then dropping the old schema. But the catalog within the table fragment was not updated.

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Fix #19808 .
Fix #19825 .

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  My PR contains critical fixes that are necessary to be merged into the latest release. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by yezizp2012** [comment]
I'm not sure whether this PR updates every fields where secrets are referenced in the streaming metadata. @yuhao-su Please help to confirm that.

File: src/ctl/src/cmd_impl/meta/migration.rs [hunk 1]
```diff
@@ -968,6 +979,62 @@ pub async fn migrate(from: EtcdBackend, target: String, force_clean: bool) -> an
...
+                visit_map_secret_refs(&mut inner.secret_refs);
+                inner.info.as_mut().map(visit_info);
+            }
+        }
+        PbNodeBody::StreamCdcScan(node) => {
+            node.cdc_table_desc
+                .as_mut()
+                .map(|desc| visit_map_secret_refs(&mut desc.secret_refs));
+        }
+        PbNodeBody::CdcFilter(_) => {}
```
Comment (yuhao-su) [inline src/ctl/src/cmd_impl/meta/migration.rs:1025]: Can you remove this line?

**Comment by yuhao-su** [comment]
LGTM. Thanks!

**Review by yuhao-su — APPROVED** [review]
