### PR TITLE
fix(standalone): ensure meta service successfully bound to the listen address before starting other services

### LINKED ISSUE #11169: Starting 2 playgrounds will make both terminated
### Describe the bug

As title. Just report this issue. Not sure if it's a problem/fixable.

### Error message/log

```text
2023-07-24T15:59:55.872806+02:00 DEBUG risingwave_common_service::observer_manager: re-subscribe success
thread 'risingwave-main' panicked at 'error type notification', src/compute/src/observer/observer_manager.rs:35:17
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Alternative to #16341. Follow the idea of https://github.com/risingwavelabs/risingwave/pull/16341#issuecomment-2063438847. Make @xxchan happy happy.

Resolve #11169.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
* **#16410** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/16410?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BugenZhao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/common/metrics/src/monitor/connection.rs [hunk 1]
```diff
@@ -521,13 +521,19 @@ impl Endpoint {
 #[cfg(not(madsim))]
 #[easy_ext::ext(RouterExt)]
 impl<L> tonic::transport::server::Router<L> {
-    pub async fn monitored_serve_with_shutdown<ResBody>(
+    /// Serve the given service while monitoring the connection.
+    ///
+    /// Calling the function will first bind the given service to the given address. Awaiting the
```
Comment (BugenZhao) [inline src/common/metrics/src/monitor/connection.rs:526]: 👀

File: src/meta/node/src/server.rs [hunk 2]
```diff
@@ -366,8 +386,9 @@ pub async fn start_service_as_election_follower(
                     },
                 }
             },
-        )
-        .await;
+        );
+    started::set();
```
Comment (BugenZhao) [inline src/meta/node/src/server.rs:390]: 👀

File: src/meta/node/src/server.rs [hunk 3]
```diff
@@ -822,8 +843,9 @@ pub async fn start_service_as_election_leader(
...
```
Comment (wenym1) [inline src/meta/node/src/server.rs:847]: Can we check whether the server has started by connecting to the port like risedev does? Or we add some retry policy when other nodes try to connect to meta?

In some corner cases the current way still cannot ensure meta service starts before others. For example,
```
meta: started::set()
CN: start and connect
meta: server.await
```

Comment (BugenZhao) [reply src/meta/node/src/server.rs:847]: I guess the title of the PR might be misleading.

We don't have to verify that the service has actually started; confirming a successful binding to the listen address should suffice. This is because we're to resolve #11169, while the startup order of meta node and compute node does not matter since there's a retry mechanism.

Comment (wenym1) [reply src/meta/node/src/server.rs:847]: But I think we are only able to bind the address on `server.await`. After `TcpIncoming::new` is returned, the address is not bound yet.

```
#[tokio::main]
async fn main() {
    let socket1 = tonic::transport::server::TcpIncoming::new("127.0.0.1:8080".parse().unwrap(), true, None);
    let socket2 = tonic::transport::server::TcpIncoming::new("127.0.0.1:8080".parse().unwrap(), true, None);
}
```

The code can run successfully.

Intuitively, binding an address may involve IO, and the method should be async. But before `server.await` there is no await.

Comment (BugenZhao) [reply src/meta/node/src/server.rs:847]: > The code can run successfully.

Is that because `TcpIncoming::new` returns `Result`? 😄

Comment (wenym1) [reply src/meta/node/src/server.rs:847]: My bad 🤡

**Review by wenym1 — APPROVED** [review]
LGTM!

**Review by yezizp2012 — APPROVED** [review]

**Review by kwannoel — APPROVED** [review]
LGTM

**Review by xxchan — APPROVED** [review]
happy happy
