### PR TITLE
fix: mark mview created after command finished and fix dirty clean

### LINKED ISSUE #5755: bug(recovery): query result mismatch due to recovery of mview that did not finish creating
https://buildkite.com/risingwavelabs/pull-request/builds/9902#0183c136-80e2-4650-bde3-b32e34c86ad1

### LINKED ISSUE #6031: bug(recovery): thread panic of pinned version assertion
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/10783#01840ec2-9c2e-4fc1-b3dc-4a066b5b7b74
```
thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
--
  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9
  | thread '<unnamed>' panicked at 'pinning a older version 1. Current is 1', src/storage/src/hummock/local_version/pinned_version.rs:102:9


```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title,
1. mark mview created when command finished with ckpt and fix `clear_changes` in checkpoint control. The two bugs are the root cause of the check fail in #5755 .
2. add `INITIAL` state for table fragment, so we can notify delete on fragment mapping correctly.
3. fix pining version assertion.
4. set `RW_IMPLICIT_FLUSH` to true firstly when re-connect to frontend while `--kill-frontend` enabled, which will also cause query result mismatch.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Fix #5755 
Fix #6031

### CODE REVIEW

File: src/meta/src/barrier/mod.rs [hunk 1]
```diff
@@ -185,19 +185,23 @@ where
...
     ///
     /// Returns whether there are still remaining stashed commands to finish.
-    fn finish_commands(&mut self, checkpoint: bool) -> bool {
+    async fn finish_commands(&mut self, checkpoint: bool) -> MetaResult<bool> {
         if checkpoint {
-            self.finished_commands
-                .drain(..)
-                .flat_map(|c| c.notifiers)
-                .for_each(Notifier::notify_finished);
+            for command in self.finished_commands.drain(..) {
```
Comment (BugenZhao) [inline src/meta/src/barrier/mod.rs:190]: How about moving this out of `if`, in case there're some commands with `checkpoint = false` to finish?

File: proto/meta.proto [hunk 2]
```diff
@@ -35,10 +35,12 @@ message TableFragments {
   // The state of the fragments of this table
   enum State {
     UNSPECIFIED = 0;
+    // The materialized view is initialized.
+    INITIALIZED = 1;
```
Comment (BugenZhao) [inline proto/meta.proto:39]: How about `initial`?

**Review by BugenZhao — APPROVED** [review]
LGTM! Good catch!!

**Review by BugenZhao — APPROVED** [review]
The meta & stream part LGTM.
