### PR TITLE
fix(metric): fix backfill snapshot read metric

### LINKED ISSUE #15408: bug(metric): backfill metric doesn't count the last chunk
### Describe the bug

It breaks the loop early [here](https://github.com/risingwavelabs/risingwave/blob/ead3e53d61b9c57a9fb0ef3d488b7af6801aeeb1/src/stream/src/executor/backfill/no_shuffle_backfill.rs#L305) before updating metrics [here](https://github.com/risingwavelabs/risingwave/blob/ead3e53d61b9c57a9fb0ef3d488b7af6801aeeb1/src/stream/src/executor/backfill/no_shuffle_backfill.rs#L406)

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #15408

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/stream/src/executor/backfill/no_shuffle_backfill.rs [hunk 1]
```diff
@@ -403,22 +405,6 @@ where
...
-                    .inc_by(cur_barrier_snapshot_processed_rows);
-
-                self.metrics
-                    .backfill_upstream_output_row_count
-                    .with_label_values(&[
-                        upstream_table_id.to_string().as_str(),
-                        self.actor_id.to_string().as_str(),
-                    ])
-                    .inc_by(cur_barrier_upstream_processed_rows);
-
```
Comment (kwannoel) [inline src/stream/src/executor/backfill/no_shuffle_backfill.rs:421]: If we remove this, we won't report the metrics until backfill is complete.

We can instead report the metrics change at the part where we do `break 'backfill_loop` in `snapshot_read`, since that's the only place we miss the metrics reporting.

https://github.com/risingwavelabs/risingwave/blob/5163877eae7a65eb13e377316acd55a596ed9f8a/src/stream/src/executor/backfill/arrangement_backfill.rs#L304

https://github.com/risingwavelabs/risingwave/blob/5163877eae7a65eb13e377316acd55a596ed9f8a/src/stream/src/executor/backfill/no_shuffle_backfill.rs#L305

**Review by kwannoel — APPROVED** [review]
LGTM, thanks!
