### PR TITLE
fix: avro timestamp_mills and timestamp_micros parse to timestamptz

### LINKED ISSUE #8495: bug: avro `Timestamp` should map to `timestamptz`
### Describe the bug

As per avro [specification](https://avro.apache.org/docs/1.11.1/specification/#timestamp-millisecond-precision):

> The `timestamp-millis` logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one millisecond. Please note that time zone information gets lost in this process. Upon reading a value back, we can only reconstruct the instant, but not the original representation. In practice, such timestamps are typically displayed to users in their local time zones, therefore they may be displayed differently depending on the execution environment.
> A `timestamp-millis` logical type annotates an Avro long, where the long stores the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.

(The above also applies to `timestamp-micros`)

> The `local-timestamp-millis` logical type represents a timestamp in a local timezone, regardless of what specific time zone is considered local, with a precision of one millisecond.
> A `local-timestamp-millis` logical type annotates an Avro long, where the long stores the number of milliseconds, from 1 January 1970 00:00:00.000.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

resolve #8495 

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Connector (sources & sinks)

### Release note

it is related to avro parser's behavior. 

according to [avro's doc](https://avro.apache.org/docs/1.11.1/specification/#timestamp-millisecond-precision)

> The timestamp-millis logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one millisecond. Please note that time zone information gets lost in this process. Upon reading a value back, we can only reconstruct the instant, but not the original representation. **In practice, such timestamps are typically displayed to users in their local time zones, therefore they may be displayed differently depending on the execution environment.**
A timestamp-millis logical type annotates an Avro long, where the long stores the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.

> The timestamp-micros logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one microsecond. Please note that time zone information gets lost in this process. Upon reading a value back, we can only reconstruct the instant, but not the original representation. **In practice, such timestamps are typically displayed to users in their local time zones, therefore they may be displayed differently depending on the execution environment.**
A timestamp-micros logical type annotates an Avro long, where the long stores the number of microseconds from the unix epoch, 1 January 1970 00:00:00.000000 UTC.

we should warn users that we can only get i64 part and no timezone data. Users should be aware that the time displayed by us and by the upstream can be different as they may not be in the timezone. 

for type `local-timestamp-millis`, we should mark it as won't support because, at the moment, the relied rust crate does not support the type. 

</details>

### CODE REVIEW

File: src/connector/src/parser/avro/util.rs [hunk 1]
```diff
@@ -281,32 +281,12 @@ pub(crate) fn from_avro_value(value: Value, value_schema: &Schema) -> Result<Dat
...
-                millis / 1_000,
-                (millis % 1_000) as u32 * 1_000_000,
-            )
-            .map_err(|e| {
-                let err_msg = format!(
-                    "avro parse error.wrong timestamp millis value {}, err {:?}",
-                    millis, e
-                );
+        Value::TimestampMicros(t) | Value::TimestampMillis(t) => {
+            ScalarImpl::Int64(i64_to_timestamptz(t).map_err(|e| {
```
Comment (xiangjinwu) [inline src/connector/src/parser/avro/util.rs:285]: `i64_to_timestamptz` is used to guess the unit when it is not clear from the context. At this place we know it is micro or milli:
```
Value::TimestampMicros(us) => ScalarImpl::Int64(us),
Value::TimestampMillis(ms) => ScalarImpl::Int64(ms.checked_mul(1000).ok_or_else(|| ...)?),
```

The unit test below is actually an example of misuse: `1620000000000 us` = `1620000000 ms` should be `1970-01-19 18:00:00Z`, which is outside out the valid guess range. `i64_to_timestamptz` guessed the unit to be ms / s, and returned `1620000000000000 us` which is `2021-05-03 00:00:00Z`.

File: src/connector/src/parser/avro/parser.rs [hunk 2]
```diff
@@ -425,24 +423,12 @@ mod test {
...
-                    let datetime = Some(ScalarImpl::NaiveDateTime(
-                        NaiveDateTimeWrapper::with_secs_nsecs(
-                            millis / 1000,
-                            (millis % 1000) as u32 * 1_000_000,
-                        )
-                        .unwrap(),
-                    ));
-                    assert_eq!(row[i], datetime);
+                    let millis = Some(ScalarImpl::Int64(millis));
+                    assert_eq!(row[i], millis);
```
Comment (xiangjinwu) [inline src/connector/src/parser/avro/parser.rs:427]: Is this supposed to be `millis * 1000`? How did the test pass?

**Review by xiangjinwu — APPROVED** [review]
rest lgtm
