### PR TITLE
fix: temporarily skip the deleted S3 Object

### LINKED ISSUE #11041: bug(s3 connector): failed to recovery after deleting some objects
### Describe the bug

Failed to recovery after deleting some objects

### Error message/log

```text
2023-07-19T03:49:34.205304505Z ERROR risingwave_stream::task::stream_manager: actor exit, actor: 48, error: Executor error: Connector erro
r: internal error: S3 GetObject from eric-demo-singapore error: service error
  backtrace of `StreamExecutorError`:
   0: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_stream::executor::error::Inner>>::from
             at ./src/stream/src/executor/error.rs:102:10
   1: <T as core::convert::Into<U>>::into
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/convert/mod.rs:717:9
   2: risingwave_stream::executor::error::StreamExecutorError::connector_error
             at ./src/stream/src/executor/error.rs:89:45
   3: risingwave_stream::executor::stream_reader::StreamReaderWithPause<_,M>::data_stream::{{closure}}
             at ./src/stream/src/executor/stream_reader.rs:60:32
   4: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
   5: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:196:9
   6: <futures_util::stream::try_stream::into_stream::IntoStream<St> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/into_stream.rs:3
8:9
   7: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
   8: <futures_util::stream::try_stream::MapOk<St,F> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:102:13
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  10: futures_util::stream::select_with_strategy::poll_side
  11: futures_util::stream::select_with_strategy::poll_inner
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/select_with_strategy.rs:243
:11
  12: <futures_util::stream::select_with_strategy::SelectWithStrategy<St1,St2,Clos,State> as futures_core::stream::Stream>::poll_next
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/select_with_strategy.rs:270
:17
  13: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
```

### To Reproduce

1. create a S3 source/table with some files in S3 bucket
2. shutdown RW cluster
3. remove that file
4. start RW cluster

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shanicky**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

as title, try to temporarily fix #11041 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/connector/src/source/filesystem/s3/source/reader.rs [hunk 1]
```diff
@@ -65,9 +67,30 @@ impl S3FileReader {
...
+            &object_name,
+            split.offset,
+        )
+        .await
+        .map_err(|sdk_err| sdk_err.into_service_error())
+        {
+            Ok(s) => s,
+            Err(GetObjectError::NoSuchKey(_)) => {
+                tracing::warn!("S3 Object {} not found, ignoring", object_name);
+                return Ok(());
```
Comment (tabVersion) [inline src/connector/src/source/filesystem/s3/source/reader.rs:83]: should we also mark the file's state as done in state store to prevent looking for the file second time?

**Review by tabVersion — APPROVED** [review]
rest LGTM

File: src/connector/src/source/filesystem/s3/source/reader.rs (hunk 1 above)
Comment (shanicky) [reply src/connector/src/source/filesystem/s3/source/reader.rs:83]: Yes, the residual status still exists in the state store. The enumerator needs to initiate split reduction to push the delete command.

This is just a temporary solution, otherwise the deleted split will prevent the cluster from starting and it will remain in the recovery state.

Comment (tabVersion) [reply src/connector/src/source/filesystem/s3/source/reader.rs:83]: never mind. it is ok to leave it for now.
