### PR TITLE
fix(pgwire): fix corner case processing in parse and bind msg

### LINKED ISSUE #11392: bug: null value of timestamp is not well handled in pgwire
### Describe the bug

The java program below returned this error:
```
org.postgresql.util.PSQLException: ERROR: ParseError: internal error: Unsupported oid 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at DatabaseTest.main(DatabaseTest.java:29)
```

### Error message/log

```text
2023-08-02T19:18:23.143837+08:00 ERROR pgwire::pg_protocol: error when process message error=ParseError: internal error: Unsupported oid 0
thread 'risingwave-main' panicked at 'range end out of bounds: 18446744073709551615 <= 2', /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:261:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: bytes::bytes::Bytes::slice
             at /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:261:9
   3: <bytes::bytes::Bytes as bytes::buf::buf_impl::Buf>::copy_to_bytes
             at /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:565:23
   4: pgwire::pg_message::FeBindMessage::parse::{{closure}}
             at ./src/utils/pgwire/src/pg_message.rs:180:17
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
   9: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  15: pgwire::pg_message::FeBindMessage::parse
             at ./src/utils/pgwire/src/pg_message.rs:177:22
  16: pgwire::pg_message::FeMessage::read::{{closure}}
             at ./src/utils/pgwire/src/pg_message.rs:274:21
  17: pgwire::pg_protocol::PgStream<S>::read::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:833:40
  18: pgwire::pg_protocol::Conn<S>::read::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:925:38
  19: pgwire::pg_protocol::PgProtocol<S,SM>::read_message::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:274:60
```

### To Reproduce

```java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DatabaseTest {
    public static void main(String[] args) {

        String url = "jdbc:postgresql://localhost:4566/dev"; // Replace with your url
        String user = "root"; // Replace with your username
        String password = ""; // Replace with your password

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            // Create table
            String createTableQuery = "CREATE TABLE IF NOT EXISTS t (v TIMESTAMP)";

            PreparedStatement createTableStatement = connection.prepareStatement(createTableQuery);
            createTableStatement.execute();

            // Insert into table
            String insertQuery = "INSERT INTO t (v) VALUES (?) ";

            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);

            // Fill in the placeholders
            insertStatement.setTimestamp(1, null);

            insertStatement.execute();

        } catch (SQLException e) {
            System.out.println("Error while interacting with the database");
            e.printStackTrace();
        }
    }
}
```

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ZENOTME**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #11392

Fix two corner case missing in message process:
1. https://www.postgresql.org/docs/15/protocol-message-formats.html#:~:text=Placing%20a%20zero%20here%20is%20equivalent%20to%20leaving%20the%20type%20unspecified.
2. https://www.postgresql.org/docs/15/protocol-message-formats.html#:~:text=%2D1%20indicates%20a%20NULL%20parameter%20value.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- ~~[ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
- ~~[ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- ~~[ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)~~

- ~~[ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))~~

## Documentation

- [x] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/frontend/src/binder/mod.rs [hunk 1]
```diff
@@ -137,11 +137,11 @@ pub struct Binder {
 pub struct ParameterTypes(Arc<RwLock<HashMap<u64, Option<DataType>>>>);
 
 impl ParameterTypes {
-    pub fn new(specified_param_types: Vec<DataType>) -> Self {
+    pub fn new(specified_param_types: Vec<Option<DataType>>) -> Self {
```
Comment (liurenjie1024) [inline src/frontend/src/binder/mod.rs:140]: IIUC, data types should not be none?

**Review by liurenjie1024 — APPROVED** [review]
LGTM

File: src/frontend/src/binder/mod.rs (hunk 1 above)
Comment (liurenjie1024) [reply src/frontend/src/binder/mod.rs:140]: Oh, my bad.
