### PR TITLE
fix: source_status_is_up still reporting after `Drop Source`

### LINKED ISSUE #12343: bug(metrics) source_status_is_up still reporting after drop source
### Describe the bug

I created a source and then drop it. But the `source_status_is_up` is still reporting.

- 1003 1004 1005 are created after the previous one deleted, But currently all of them are exist.
image

https://grafana.test.risingwave-cloud.xyz/explore?orgId=1&left=%7B%22datasource%22:%22P2453400D1763B4D9%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P2453400D1763B4D9%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22source_status_is_up%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221694736000000%22,%22to%22:%221694764800000%22%7D%7D

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

v1.1.4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rossil2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Resolve #12343.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/meta/src/rpc/metrics.rs [hunk 1]
```diff
@@ -77,13 +83,13 @@ pub struct MetaMetrics {
...
-    pub level_compact_cnt: IntGaugeVec,
+    pub level_compact_cnt: LabelGuardedIntGaugeVec<1>,
     /// The number of compact tasks
-    pub compact_frequency: IntCounterVec,
+    pub compact_frequency: LabelGuardedIntCounterVec<4>,
     /// Size of each level
-    pub level_file_size: IntGaugeVec,
+    pub level_file_size: LabelGuardedIntGaugeVec<1>,
     /// Hummock version size
     pub version_size: IntGauge,
```
Comment (Rossil2012) [inline src/meta/src/rpc/metrics.rs:94]: How to refactor IntGauge with LabelGuardedIntGauge<N>? There are no LabelGuardedIntGauge::\<N\>::new or a macro like `register_guarded_int_gauge` to build it. cc @tabVersion @wenym1.

File: src/common/src/metrics/guarded_metrics.rs [hunk 2]
```diff
@@ -208,6 +208,14 @@ impl<T: MetricVecBuilder, const N: usize> LabelGuardedMetricVec<T, N> {
         }
     }
 
+    pub fn reset(&self) {
+        self.inner.reset()
+    }
+
+    pub fn remove_label_values(&self, labels: &[&str; N]) -> prometheus::Result<()> {
```
Comment (wenym1) [inline src/common/src/metrics/guarded_metrics.rs:215]: Why we still need `remove_label_values`? It is automatically handled when the labeled is not used any more.

File: src/common/src/metrics/guarded_metrics.rs [hunk 3]
```diff
@@ -208,6 +208,14 @@ impl<T: MetricVecBuilder, const N: usize> LabelGuardedMetricVec<T, N> {
         }
     }
 
+    pub fn reset(&self) {
```
Comment (wenym1) [inline src/common/src/metrics/guarded_metrics.rs:211]: Where is it used?

File: src/meta/src/rpc/metrics.rs (hunk 1 above)
Comment (wenym1) [reply src/meta/src/rpc/metrics.rs:94]: The `LabelGuardedXxx` is only used for `XxxVec`. The `IntGauge` without any label does not need to use as a label guarded one.

File: src/common/src/metrics/guarded_metrics.rs (hunk 3 above)
Comment (Rossil2012) [reply src/common/src/metrics/guarded_metrics.rs:211]: https://github.com/risingwavelabs/risingwave/blob/main/src/meta/src/rpc/metrics.rs#L768

File: src/common/src/metrics/guarded_metrics.rs (hunk 2 above)
Comment (Rossil2012) [reply src/common/src/metrics/guarded_metrics.rs:215]: https://github.com/risingwavelabs/risingwave/blob/main/src/meta/src/hummock/metrics_utils.rs#L249
Since Meta handles the removal of Hummock metrics, maybe we should leave it untouched and change only the `source_is_up` that directly related to #12343?

Comment (wenym1) [reply src/common/src/metrics/guarded_metrics.rs:215]: Previously the `reset` and `remove_label_values` are used because we were releasing the unused label manually. With the label guarded metrics, the labels will be automatically removed when the label is not used anymore. So we can either change only the metrics related to the issue, or we change some other current logic to remove the original calls on `reset` and `remove_label_values`.

**Review by tabVersion — APPROVED** [review]
it is ok not migrate all metrics as long as fixing the problem, good work!
