### PR TITLE
fix(optimizer): can't apply pull_up_correlated_predicate_agg_rule with non-null-propagating expr

### LINKED ISSUE #19835: PullUpCorrelatedPredicateAggRule is wrong for non-null-propagating expression
### Describe the bug

I couldn't create a sample as I don't know how to how to create an empty array of rows. But a query like below return a `null` map when the subquery return no rows. I expected it to return an empty map instead.

Also, couldn't we simplify the syntax by removing the explicit `array()` ?

### Error message/log

_No response_

### To Reproduce

```sql
select map_from_entries(array(select row(foo.id, foo.name) from foo where foo.id=unrelated.id))
```

### Expected behavior

Return an empty map instead of null

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

version | PostgreSQL 13.14.0-RisingWave-2.0.4 (2d757981a1f747c057f79bfb4a19fffbde563ece)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

fix #19835

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  My PR contains critical fixes that are necessary to be merged into the latest release. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs [hunk 1]
```diff
@@ -153,55 +153,32 @@ impl Rule for PullUpCorrelatedPredicateAggRule {
...
-
-            // Only all expr in conjunctions are null, we can apply this rule, otherwise, bail out.
-            if top_filter
-                .predicate()
-                .conjunctions
-                .iter()
-                .any(|expr| !Strong::is_null(expr, top_proj_null_bitset.clone()))
-            {
-                return None;
-            }
```
Comment (chenzl25) [inline src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:204]: Why this logic needed to be changed?

Comment (xxchan) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:204]: I don't get why previously we check top_filter. I think we should check the output exprs instead

Comment (chenzl25) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:204]: Checking top_filter to ensure the null agg row generated by left outer join finally could be eliminated by the filter. If it could be eliminated, then we can allow the transformation, even if we meet `count`, `array`, and other aggs will generate a not null output when input is empty.

File: src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs [hunk 2]
```diff
@@ -153,55 +153,32 @@ impl Rule for PullUpCorrelatedPredicateAggRule {
...
-            // When group input is empty, not count agg would return null.
+        // If the `group by + proj` doesn't return null for empty input, we can't apply this rule.
+        {
+            // When group input is empty, if the agg is not `count`, it would return null.
             let null_agg_pos = agg_calls
                 .iter()
                 .positions(|agg_call| {
                     !matches!(agg_call.agg_type, AggType::Builtin(PbAggKind::Count))
                 })
                 .collect_vec();
```
Comment (chenzl25) [inline src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:165]: Shall we add `array` aggregation here?

Comment (xxchan) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:165]: array subquery is planned as `array_agg + coalesce`

Comment (xxchan) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:165]: and `array_agg` is null-propagating

Comment (chenzl25) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:165]: OK, I see.

File: src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs (hunk 1 above)
Comment (xxchan) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:204]: Oh, I think the condition can be:
`top_filter is null OR all of top_proj are null`

Comment (chenzl25) [reply src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:204]: Yes, you can construct a planner test case I think.

File: src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs [hunk 3]
```diff
@@ -185,21 +178,26 @@ impl Rule for PullUpCorrelatedPredicateAggRule {
...
 
-            // Only all expr in conjunctions are null, we can apply this rule, otherwise, bail out.
-            if top_filter
+            let top_filter_all_null = top_filter
                 .predicate()
                 .conjunctions
                 .iter()
-                .any(|expr| !Strong::is_null(expr, top_proj_null_bitset.clone()))
-            {
+                .all(|expr| Strong::is_null(expr, top_proj_null_bitset.clone()));
```
Comment (chenzl25) [inline src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:196]: It should be any.
```suggestion
                .any(|expr| Strong::is_null(expr, top_proj_null_bitset.clone()));
```

File: src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs [hunk 4]
```diff
@@ -185,21 +178,26 @@ impl Rule for PullUpCorrelatedPredicateAggRule {
...
             // Shift the top project expressions to the right by apply_left schema len, because it is used to check null-rejected by the top filter.
             let apply_left_schema = apply_left.schema().len();
+            let mut top_proj_all_null = true;
             let mut top_proj_null_bitset =
                 FixedBitSet::with_capacity(top_project.base.schema().len() + apply_left_schema);
             for (i, expr) in top_proj_exprs.iter().enumerate() {
                 if Strong::is_null(expr, agg_null_bitset.clone()) {
                     top_proj_null_bitset.insert(i + apply_left_schema);
+                } else {
+                    top_proj_all_null = false;
```
Comment (chenzl25) [inline src/frontend/src/optimizer/rule/pull_up_correlated_predicate_agg_rule.rs:188]: When `Strong::is_null` return false, it means we can't get any useful information, so we shouldn't allow apply rule based on it.

**Review by chenzl25 — APPROVED** [review]
Rest LGTM! Thanks

**Comment by maingoh** [comment]
@xxchan I don't see this commit in the latest tags `2.0.6` or `2.1.2` or `v2.2.0-rc.1`. I am wondering if will be tagged or if it has been forgotten ? Thank you !

**Comment by xxchan** [comment]
I think it can be cherry-picked into 2.2 which hasn't been released yet
