### PR TITLE
fix: Logs should use localtime

### LINKED ISSUE #6034: bug: risingwave logs should use localtime.
### Describe the bug

Risingwave's log is using some fixed time zone, but it should use localtime to improve user experience.

### To Reproduce

image
image

### Expected behavior

Report log using local time.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liurenjie1024**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Risingwave's log should use local time rather utc time.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

Closes #6034

### CODE REVIEW

**Review by BugenZhao — APPROVED** [review]

File: src/utils/runtime/src/lib.rs [hunk 1]
```diff
@@ -95,7 +96,8 @@ pub fn init_risingwave_logger(settings: LoggerSettings) {
         // Configure log output to stdout
         let fmt_layer = tracing_subscriber::fmt::layer()
             .compact()
-            .with_ansi(settings.colorful);
+            .with_ansi(settings.colorful)
+            .with_timer(time::LocalTime::rfc_3339());
```
Comment (BugenZhao) [inline src/utils/runtime/src/lib.rs:100]:
```suggestion
            .with_timer(time::OffsetTime::local_rfc_3339().unwrap());
```

**Comment by liurenjie1024** [comment]
Yes, it's required by formatter.

**Review by BowenXiao1999 — APPROVED** [review]

**Review by BugenZhao — APPROVED** [review]
