### PR TITLE
fix: ban cross database stream query with upstream only

### LINKED ISSUE #23080: bug: RW Standalone Panic when using process-time temporal join with cross-database lookup table
### Describe the bug

We've found that RW Standalone (v2.5.1) panics when using a process-time temporal join with a lookup table that exists in a different database.

### Error message/log

```text
thread 'rw-standalone-meta' panicked at src/meta/src/barrier/info.rs:108:44:
no entry found for key
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/panicking.rs:261:5
   3: core::option::expect_failed
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/option.rs:2024:5
   4: core::option::Option<T>::expect
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/option.rs:933:21
   5: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/collections/hash/map.rs:1426:23
   6: risingwave_meta::barrier::info::InflightDatabaseInfo::fragment
             at ./risingwave/src/meta/src/barrier/info.rs:108:44
   7: risingwave_meta::barrier::info::InflightDatabaseInfo::build_edge::{{closure}}
             at ./risingwave/src/meta/src/barrier/info.rs:314:36
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/ops/function.rs:305:13
   9: core::option::Option<T>::map
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/option.rs:1119:29
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/iter/adapters/map.rs:107:26
  11: core::ops::function::FnOnce::call_once
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/ops/function.rs:250:5
  12: core::iter::adapters::chain::and_then_or_clear
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/iter/adapters/chain.rs:333:13
  13: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/iter/adapters/chain.rs:84:9
  14: risingwave_meta::barrier::edge_builder::FragmentEdgeBuilder::new
             at ./risingwave/src/meta/src/barrier/edge_builder.rs:94:21
  15: risingwave_meta::barrier::info::InflightDatabaseInfo::build_edge
             at ./risingwave/src/meta/src/barrier/info.rs:312:27
  16: risingwave_meta::barrier::checkpoint::control::DatabaseCheckpointControl::handle_new_barrier
             at ./risingwave/src/meta/src/barrier/checkpoint/control.rs:1006:25
  17: risingwave_meta::barrier::checkpoint::control::CheckpointControl::handle_new_barrier
             at ./risingwave/src/meta/src/barrier/checkpoint/control.rs:251:13
  18: risingwave_meta::barrier::worker::GlobalBarrierWorker<C>::run_inner::{{closure}}
             at ./risingwave/src/meta/src/barrier/worker.rs:477:37
  19: risingwave_meta::barrier::worker::GlobalBarrierWorker<risingwave_meta::barrier::context::GlobalBarrierWorkerContextImpl>::run::{{closure}}
             at ./risingwave/src/meta/src/barrier/worker.rs:236:37
  20: <task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/task-local-0.1.0/src/lib.rs:391:31
  21: task_local::LocalKey<T>::scope_inner
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/task-local-0.1.0/src/lib.rs:217:19
  22: <task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/task-local-0.1.0/src/lib.rs:387:19
  23: await_tree::root::TreeRoot::instrument::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/await-tree-0.3.2-alpha.2/src/root.rs:47:34
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/future/future.rs:124:9
  25: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tracing-0.1.41/src/instrument.rs:321:9
  26: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:331:17
  27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/loom/std/unsafe_cell.rs:16:9
  28: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:320:30
  29: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:532:19
  30: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/panic/unwind_safe.rs:272:9
  31: std::panicking::try::do_call
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panicking.rs:587:40
  32: std::panicking::try
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panicking.rs:550:19
  33: std::panic::catch_unwind
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panic.rs:359:14
  34: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
  35: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:15
  37: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
  38: tokio::runtime::task::LocalNotified<S>::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:463:9
  39: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:674:22
  40: tokio::task::coop::with_budget
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/task/coop/mod.rs:167:5
  41: tokio::task::coop::budget
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/task/coop/mod.rs:133:5
  42: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:594:9
  43: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:542:24
  44: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:507:21
  45: tokio::runtime::context::scoped::Scoped<T>::set
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context/scoped.rs:40:9
2025-09-03T20:13:54.320474379Z  INFO            rw-streaming actor{otel.name="Actor 2" actor_id=2 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize 200000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.320329587Z  INFO            rw-streaming actor{otel.name="Actor 4" actor_id=4 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize 400000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.320338212Z  INFO            rw-streaming actor{otel.name="Actor 11" actor_id=11 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize B00000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.320339671Z  INFO            rw-streaming actor{otel.name="Actor 12" actor_id=12 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize C00000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.320340421Z  INFO            rw-streaming actor{otel.name="Actor 6" actor_id=6 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize 600000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.320454671Z  INFO            rw-streaming actor{otel.name="Actor 1" actor_id=1 prev_epoch=9155066874757120 curr_epoch=9155066874822656}:executor{otel.name="Materialize 100000004"}: risingwave_stream::common::table::state_table: switch to new op consistency level new_epoch=EpochPair { curr: 9155066876395520, prev: 9155066874822656 } prev_op_consistency_level=Inconsistent op_consistency_level=LogStoreEnabled table_id=11
2025-09-03T20:13:54.326879504Z  INFO  rw-standalone-frontend handle_query{mode="simple query" session_id=1 sql=CREATE SUBSCRIPTION sub_t1 FROM t1 WITH (retention = '1D')}: pgwire_query_log: status="ok" time=9ms
2025-09-03T20:13:54.337686546Z  INFO  rw-standalone-frontend handle_query{mode="simple query" session_id=1 sql=CREATE DATABASE d2}: pgwire_query_log: status="ok" time=10ms
2025-09-03T20:13:54.338299004Z  INFO  rw-standalone-frontend handle_query{mode="simple query" session_id=1 sql=USE d2}: pgwire_query_log: status="ok" time=0ms
2025-09-03T20:13:54.403787921Z  INFO  rw-standalone-frontend handle_query{mode="simple query" session_id=1 sql=CREATE TABLE t2 (a INT)}: pgwire_query_log: status="ok" time=65ms
2025-09-03T20:13:54.404997837Z  INFO  rw-standalone-frontend handle_query{mode="simple query" session_id=1 sql=CREATE MATERIALIZED VIEW mv1 AS SELECT t2.* FROM t2 JOIN d1.public.t1 FOR SYSTEM_TIME AS OF PROCTIME() ON t1.a = t2.a}: risingwave_expr::sig: found 1180 functions


*** await tree context of current task ***

Global Barrier Worker [6.592s]


  46: tokio::runtime::context::set_scheduler::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context.rs:180:26
  47: std::thread::local::LocalKey<T>::try_with
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/thread/local.rs:311:12
  48: std::thread::local::LocalKey<T>::with
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/thread/local.rs:275:15
  49: tokio::runtime::context::set_scheduler
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context.rs:180:9
  50: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:502:9
  51: tokio::runtime::context::runtime::enter_runtime
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context/runtime.rs:65:16
  52: tokio::runtime::scheduler::multi_thread::worker::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:494:5
  53: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/multi_thread/worker.rs:460:45
  54: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/task.rs:42:21
  55: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tracing-0.1.41/src/instrument.rs:321:9
  56: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:331:17
  57: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/loom/std/unsafe_cell.rs:16:9
  58: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:320:30
  59: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:532:19
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/core/src/panic/unwind_safe.rs:272:9
  61: std::panicking::try::do_call
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panicking.rs:587:40
  62: std::panicking::try
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panicking.rs:550:19
  63: std::panic::catch_unwind
             at ./rustc/f9e0239a7bc813b4aceffc7f069f4797cde3175c/library/std/src/panic.rs:359:14
  64: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
  65: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
  66: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:15
  67: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
  68: tokio::runtime::task::UnownedTask<S>::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:500:9
  69: tokio::runtime::blocking::pool::Task::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:161:9
  70: tokio::runtime::blocking::pool::Inner::run
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:511:17
  71: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

Minimum reproducible SLT:

```
statement ok
CREATE DATABASE d1;

statement ok
USE d1;

statement ok
CREATE TABLE t1(a int PRIMARY KEY);

statement ok
CREATE SUBSCRIPTION sub_t1 FROM t1 WITH (retention = '1D');

statement ok
CREATE DATABASE d2;

statement ok
USE d2;

statement ok
CREATE TABLE t2(a int);

statement ok
CREATE MATERIALIZED VIEW mv1 AS
SELECT
t2.*
FROM t2
INNER JOIN d1.public.t1 FOR SYSTEM_TIME AS OF PROCTIME()
ON t1.a = t2.a;
```

### Expected behavior

I expect that process-time temporal joins with tables in a different database should work.

### How did you deploy RisingWave?

Docker (RisingWave Standalone v2.5.1)

### The version of RisingWave

v2.5.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Resolved #23080 .

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/logical_scan.rs [hunk 1]
```diff
@@ -608,20 +608,21 @@ impl ToStream for LogicalScan {
         ctx: &mut ToStreamContext,
     ) -> Result<crate::optimizer::plan_node::StreamPlanRef> {
         if self.predicate().always_true() {
-            // Force rewrite scan type to cross-db scan
-            if self.core.table_catalog.database_id != self.base.ctx().session_ctx().database_id() {
-                Ok(StreamTableScan::new_with_stream_scan_type(
-                    self.core.clone(),
-                    StreamScanType::CrossDbSnapshotBackfill,
+            if self.core.cross_database() && ctx.stream_scan_type() == StreamScanType::UpstreamOnly
```
Comment (wenym1) [inline src/frontend/src/optimizer/plan_node/logical_scan.rs:611]: Here we used to rewrite the `stream_scan_type` to `CrossDbSnapshotBackfill`. Is it correct not to do it any more in this PR?

Comment (wenym1) [reply src/frontend/src/optimizer/plan_node/logical_scan.rs:611]: Oh, we force rewrite in stream_table_scan.

**Review by chenzl25 — APPROVED** [review]
LGTM
