### PR TITLE
fix(jdbc-sink): use upsert SQL to handle potential duplicate event

### LINKED ISSUE #10251: JDBC sink may encounter duplicate key on downstream
### Describe the bug

```
CREATE SINK s2_postgres
FROM    lineitem_rw WITH (
        connector = 'jdbc',
        jdbc.url = 'jdbc:postgresql://localhost:5432/postgres?user=postgres&password=xxx',
        table.name = 't_lineitem',
        type='upsert'
);
```
JDBC sink uses an `INSERT INTO` statement to insert data into the downstream database, which cannot handle duplication on the primary key. In theory, we would not encounter duplication for each sink executor but I do encounter one time in my testing. Then sink executor fails and causes the Meta to enter the recovery process and rebuild the streaming graph, but it will fail again and again. Because the duplication still exists after recovery.

We should use SQL that can handle conflict for example the [INSERT ... ON DUPLICATE KEY UPDATE](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html) for MySQL sink to resolve the potential conflicts. cc @fuyufjh 

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### LINKED ISSUE #10303: JDBC sink creates prepare statement for each row which is unnecessary

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
1. use upsert SQL for INSERT and UPDATE event
2. create prepare statement once and reuse it multiple times
3. refactor sql dialect implementation

close #10251 
close #10303 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java [hunk 1]
```diff
@@ -78,6 +69,38 @@ public JDBCSink(JDBCSinkConfig config, TableSchema tableSchema) {
                             String.format(ERROR_REPORT_TEMPLATE, e.getSQLState(), e.getMessage()))
                     .asRuntimeException();
         }
+
+        // Upsert sink must have primary key
+        if (config.isUpsertSink() && pkColumnNames.isEmpty()) {
```
Comment (wenym1) [inline java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java:74]: We shall add this logic to JdbcSinkFactory.validate to report error on the create sink statement.

File: java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java [hunk 2]
```diff
@@ -78,6 +69,38 @@ public JDBCSink(JDBCSinkConfig config, TableSchema tableSchema) {
...
+        }
+
+        try {
+            var upsertSql =
+                    jdbcDialect.getUpsertStatement(
+                            config.getTableName(),
+                            List.of(tableSchema.getColumnNames()),
+                            pkColumnNames);
+            // MySQL and Postgres have upsert SQL
+            assert (upsertSql.isPresent());
```
Comment (wenym1) [inline java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java:88]: Seems that assert is disabled in java by default. We may write our own assert method.

File: java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java [hunk 3]
```diff
@@ -229,14 +198,14 @@ private PreparedStatement generatePreparedStatement(
                     stmt.setBigDecimal(placeholderIdx++, (java.math.BigDecimal) row.get(i));
                     break;
                 case INTERVAL:
-                    if (targetDbType == DatabaseType.POSTGRES) {
+                    if (jdbcDialect instanceof PostgresDialect) {
```
Comment (wenym1) [inline java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java:201]: Can we introduce the abstraction of processing interval and jsonb in the `JdbcDialect` interface so that we don't need to do a special hack here.

File: java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java [hunk 4]
```diff
@@ -272,33 +241,31 @@ private PreparedStatement generatePreparedStatement(
...
-        }
-        return stmt;
     }
 
     @Override
     public void write(Iterator<SinkRow> rows) {
         while (rows.hasNext()) {
             try (SinkRow row = rows.next()) {
-                PreparedStatement stmt = prepareStatement(row);
+                Optional<PreparedStatement> stmt;
```
Comment (wenym1) [inline java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java:250]: We shall move the `stmt = preparedXxxStatement` to after checking `row.getOp() == Data.Op.UPDATE_DELETE`, so that the return type of preparedXxxStatement can avoid using `Optional`.

**Review by wenym1 — COMMENTED** [review]
Rest LGTM

File: java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java (hunk 2 above)
Comment (wenym1) [reply java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/JDBCSink.java:81]: We may also add `-ea` in the argline configuration of the surefire plugin.
