### PR TITLE
fix: dedup staging sst on storage table read

### LINKED ISSUE #14659: bug: storage table read can read the same staging SST multiple times
### Describe the bug

Found by #14488

When caller uses a read epoch larger than the max committed epoch of the CN hummock version to perform read via storage table , there is a chance that the same staging SST will be added into the merge iterator multiple times. Examples:
```
- Table 1 Shard 1 produces IMM 1
- Table 1 Shard 2 produces IMM 2
- IMM 1 and IMM 2 are compacted into SST 1 as a Staging SST
- SST 1 is added to both Shard 1's and Shard 2's read version
- Storage table read from Table 1 will use duplicate SST 1 to construct merge iterator 
```

This bug will cause inefficiency in storage read for a short period after SSTs are flushed to S3 and before SSTs are committed to hummock version. **This bug will not cause incorrect result** to be produced because `UserKeyIterator` will only expose one kv entry with the latest epoch. 

Related: https://github.com/risingwavelabs/risingwave/pull/6071#discussion_r1010151607

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hzxa21**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
fix #14659 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by Li0k — APPROVED** [review]
LGTM

File: src/storage/src/hummock/store/version.rs [hunk 1]
```diff
@@ -537,22 +537,29 @@ pub fn read_filter_for_batch(
...
     let (min_epoch, max_epoch) = (max_mce_version.max_committed_epoch(), epoch);
     // prune imm and sst with max_mce
     for (staging_imms, staging_ssts) in staging_vec {
-        imm_vec.extend(
-            staging_imms
-                .into_iter()
-                .filter(|imm| imm.min_epoch() > min_epoch && imm.min_epoch() <= max_epoch),
-        );
+        imm_vec.extend(staging_imms.into_iter().filter(|imm| {
+            // There shouldn't be duplicated IMMs because merge imm only operates on a single shard.
```
Comment (wenym1) [inline src/storage/src/hummock/store/version.rs:548]: Previously I thought merge imm will merge the data of all shards because I saw the parameter `instance_id` of `build_shared_buffer_batch` is an option, and I thought the reason for this is that merge imm will merge the imms from multiple shards🤣 But it seems that only in testing we will have `build_shared_buffer_batch` with None instance_id. Can we by the way in this PR to change the None `instance_id` parameter of `build_shared_buffer_batch` to an explicit instance id?

**Review by wenym1 — APPROVED** [review]
