### PR TITLE
fix(connector): handle update insert and delete + subset pk + handle delete mapping

### LINKED ISSUE #20178: PG sink can use subset of downstream pg table columns
Currently validation blocks us from crreating a sink if the downstream has more columns.

Our implementation allows compatibility for unspecified columns, it will just fill these in with nulls.

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Closes #20178. Also the tests were only running on my machine previously and not CI, and hence there were several regressions. I have added them to `e2e-sink-test.sh` in this PR.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  My PR contains critical fixes that are necessary to be merged into the latest release. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by kwannoel** [comment]
* **#20238** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/20238?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/20238?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by chenzl25 — APPROVED** [review]
LGTM

File: ci/scripts/e2e-sink-test.sh [hunk 1]
```diff
@@ -73,7 +73,18 @@ echo "--- killing risingwave cluster: ci-1cn-1fe-switch-to-pg-native"
 risedev ci-kill
 
 echo "--- starting risingwave cluster"
-risedev ci-start ci-1cn-1fe
+risedev ci-start ci-inline-source-test
```
Comment (kwannoel) [inline ci/scripts/e2e-sink-test.sh:76]:
```suggestion
# Use ci-inline-source-test since it will configure ports, db, host etc... env vars via risedev-env.
# These are required for cli tools like psql have env vars correctly configured.
risedev ci-start ci-inline-source-test
```

File: src/connector/src/sink/postgres.rs [hunk 2]
```diff
@@ -424,13 +424,14 @@ impl PostgresSinkWriter {
...
         for (op, row) in chunk.rows() {
             match op {
-                Op::UpdateInsert | Op::UpdateDelete => {
-                    bail!("UpdateInsert and UpdateDelete should have been normalized by the sink executor")
-                }
-                Op::Insert => {
+                // FIXME(kwannoel): Use on conflict do update for `UpdateInsert`, ignore `UpdateDelete`.
+                // Op::UpdateInsert | Op::UpdateDelete => {
+                //     bail!("UpdateInsert and UpdateDelete should have been normalized by the sink executor")
+                // }
```
Comment (kwannoel) [inline src/connector/src/sink/postgres.rs:430]:
```suggestion
```

File: src/stream/src/common/compact_chunk.rs [hunk 3]
```diff
@@ -232,9 +232,6 @@ impl StreamChunkCompactor {
     ///   have three kind of patterns Insert, Delete or Update.
     /// - For the update (-old row, +old row), when old row is exactly same. The two rowOp will be
     ///   removed.
-    ///
-    /// All UPDATE INSERT and UPDATE DELETE will be converted to INSERT and DELETE, and dropped according to
-    /// certain rules (see `merge_insert` and `merge_delete` for more details).
```
Comment (fuyufjh) [inline src/stream/src/common/compact_chunk.rs:237]: @st1page
