### PR TITLE
fix(regress test runner): ignore syntax on empty line and last case

### LINKED ISSUE #6411: test: unexpected PG regress test results comparison of the last turned-off cases
### Describe the bug

At #6410 , in the modified `float4.sql`, I made a workaround to make the regress test succeed by adding `--@ ` to the last three lines, thus the last 4 lines are
```sql
--@ 	offset 0) s;
--@ 
--@ -- clean up, lest opr_sanity complain
--@ drop type xfloat4 cascade;
```

However, if we turn off the last case the right way, i.e., the last 4 lines being:
```sql
--@ 	offset 0) s;

-- clean up, lest opr_sanity complain
--@ drop type xfloat4 cascade;
```

Although the last test case is turned off, the expected output and the actual output are still compared, producing:
```
2022-11-16T16:16:24.625315Z ERROR risingwave_regress_test::schedule: query input:
-- clean up, lest opr_sanity complain
--@ drop type xfloat4 cascade;
2022-11-16T16:16:24.625587Z ERROR risingwave_regress_test::schedule: Diff:
-NOTICE:  drop cascades to 6 other objects
-DETAIL:  drop cascades to function xfloat4in(cstring)
-drop cascades to function xfloat4out(xfloat4)
-drop cascades to cast from xfloat4 to real
-drop cascades to cast from real to xfloat4
-drop cascades to cast from xfloat4 to integer
-drop cascades to cast from integer to xfloat4
```

### To Reproduce

modify the last 4 lines of `src/tests/regress/data/sql/float4.sql` to be 
```sql
--@ 	offset 0) s;

-- clean up, lest opr_sanity complain
--@ drop type xfloat4 cascade;
```

and run

```sh
rm -rf `pwd`/src/tests/regress/output

./risedev k
./risedev clean-data
./risedev d

RUST_BACKTRACE=1 target/debug/risingwave_regress_test -h 127.0.0.1 \
  -p 4566 \
  -u root \
  --input `pwd`/src/tests/regress/data \
  --output `pwd`/src/tests/regress/output \
  --schedule `pwd`/src/tests/regress/data/schedule \
  --mode risingwave
```
, we'll get
```
2022-11-16T16:16:24.625315Z ERROR risingwave_regress_test::schedule: query input:
-- clean up, lest opr_sanity complain
--@ drop type xfloat4 cascade;
2022-11-16T16:16:24.625587Z ERROR risingwave_regress_test::schedule: Diff:
-NOTICE:  drop cascades to 6 other objects
-DETAIL:  drop cascades to function xfloat4in(cstring)
-drop cascades to function xfloat4out(xfloat4)
-drop cascades to cast from xfloat4 to real
-drop cascades to cast from real to xfloat4
-drop cascades to cast from xfloat4 to integer
-drop cascades to cast from integer to xfloat4
```

### Expected behavior

Succeed without error

### Additional context

#6410 #5440

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

The ignore syntax `--@ ` introduced by #6329 does not work well when used on an empty line or on last test case. This PR fixes #6411.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

Fixes #6411

### CODE REVIEW

File: src/tests/regress/data/sql/float4.sql [hunk 1]
```diff
@@ -349,6 +349,6 @@ SELECT '-9223380000000000000'::float4::int8;
 --@   from (select bits::integer::xfloat4::float4 as flt
 --@           from testdata
 --@ 	offset 0) s;
---@ 
---@ -- clean up, lest opr_sanity complain
```
Comment (xiangjinwu) [inline src/tests/regress/data/sql/float4.sql:353]: This was actually leveraging another bug that we did not treat `--@ \n` as an empty line, and there is no corresponding line in expected output file. After we fixed both issues in this PR. either left or right could be correctly broken up into individual test cases.

**Review by lmatz — APPROVED** [review]
