### PR TITLE
fix(ci): backwards compat test for 1.9 should use etcd

### LINKED ISSUE #16819: Bug: Data directory is already used by another cluster with id "cbe8cac7-e873-461b-85c6-df8d8604600b", path hummock_001/cluster_id/0.)
### Describe the bug

Error Message: Data directory is already used by another cluster with id "cbe8cac7-e873-461b-85c6-df8d8604600b", path hummock_001/cluster_id/0.).

This is seen when upgrading a cluster from v1.9 to the latest `main`, via `risedev`.

### Error message/log

```text
called `Result::unwrap()` on an `Err` value: ObjectStore(Internal error: Data directory is already used by another cluster with id "cbe8cac7-e873-461b-85c6-df8d8604600b", path hummock_001/cluster_id/0.)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1654:5
   3: unwrap<alloc::sync::Arc<risingwave_meta::hummock::manager::HummockManager, alloc::alloc::Global>, risingwave_meta::hummock::error::Error>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1077:23
   4: {async_fn#0}
             at ./src/meta/node/src/server.rs:480:27
   5: {async_block#1}
             at ./src/meta/node/src/server.rs:336:10
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Closes #16819 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by yezizp2012 — APPROVED** [review]

File: ci/scripts/backwards-compat-test.sh [hunk 1]
```diff
@@ -53,6 +53,8 @@ full-without-monitoring:
     - use: compactor
 EOF
   else
+     # For versions >= 1.9.0, the default config will default to sql backend,
+     # breaking backwards compat
```
Comment (kwannoel) [inline ci/scripts/backwards-compat-test.sh:57]:
```suggestion
     # breaking backwards compat, so we must specify meta-backend: etcd
```
