### PR TITLE
fix(bloom filter): remove incorrect function `may_match` (close #8071)

### LINKED ISSUE #8071: storage: `may_match` becomes incorrect after refactor of table id in bloom filter
### Describe the bug

as title

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

as title
`may_match` becomes incorrect since #7502 

## Checklist

- [x] I have added necessary unit tests and integration tests
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/storage/src/hummock/sstable/mod.rs [hunk 1]
```diff
@@ -155,19 +154,6 @@ impl Sstable {
         !self.filter_reader.is_empty()
     }
 
-    pub fn may_match(&self, dist_key: &[u8]) -> bool {
```
Comment (Li0k) [inline src/storage/src/hummock/sstable/mod.rs:158]: how can we handle the fail_point `disable_bloom_filter` if we remove this branch

Comment (soundOfDestiny) [reply src/storage/src/hummock/sstable/mod.rs:158]: > how can we handle the fail_point `disable_bloom_filter` if we remove this branch

this fail point has been ineffective for a long time 😢 
at least since #7492

Comment (Li0k) [reply src/storage/src/hummock/sstable/mod.rs:158]: Can we also remove the failpoint test at this PR ?

Comment (soundOfDestiny) [reply src/storage/src/hummock/sstable/mod.rs:158]: > Can we also remove the failpoint test at this PR ?

fixed

**Review by Li0k — APPROVED** [review]
LGTM

PTAL @hzxa21  any comments on failpoint ?
