### PR TITLE
fix: map_contains with polymorphic type

### LINKED ISSUE #21146: map_contains returns Bind error for varchar
### Describe the bug

dev=> SELECT map_contains(MAP{'a':'1','b':'2'}, 'ab');
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: map_contains(MAP {'a': '1', 'b': '2'}, 'ab')
  2: Bind error: Cannot implicitly cast ''ab':Varchar' to polymorphic type Any

### Error message/log

```text

```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xxchan**
fix #21146

Signed-off-by: xxchan <xxchan22f@gmail.com>

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/expr/impl/src/scalar/array.rs [hunk 1]
```diff
@@ -134,10 +134,31 @@ fn map_access<'a>(
...
+/// db error: ERROR: Failed to run the query
+///
+/// Caused by these errors (recent errors listed first):
+///   1: Failed to bind expression: map_contains(MAP {1: 1}, 1.0)
+///   2: Bind error: Cannot check if numeric exists in map(integer,integer)
+///
+///
+/// query error
+/// select map_contains(MAP{1:1}, NULL::varchar);
+/// ----
```
Comment (xxchan) [inline src/expr/impl/src/scalar/array.rs:156]: These are breaking change, but I assume it's fine since it's frontend-only change
