### PR TITLE
fix(test): Use tokio time pausing in ut to avoid unstable clocks for periodic barriers

### LINKED ISSUE #23899: unit test `test_next_barrier_with_different_intervals` failed
### Buildkite URL

https://buildkite.com/risingwavelabs/pull-request/builds/86423#019ac5c5-2ca5-41f6-805d-e0e84b3a56a3/160-3787

### Description and Insights

```
thread 'barrier::schedule::tests::test_next_barrier_with_different_intervals' (86345) panicked at src/meta/src/barrier/schedule.rs:937:9:
--
assertion `left == right` failed
left: 2
right: 1
```

cc @Chiro11 @wenym1

### PR DESCRIPTION
**Pull request by Chiro11**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Close #23899

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

File: src/meta/src/barrier/schedule.rs [hunk 1]
```diff
@@ -903,7 +903,7 @@ mod tests {
         }
     }
 
-    #[tokio::test]
+    #[tokio::test(start_paused = true)]
```
Comment (BugenZhao) [inline src/meta/src/barrier/schedule.rs:906]: 😯 Interesting to know

**Review by BugenZhao — APPROVED** [review]
LGTM
