### PR TITLE
fix: clean the verbose logs of "failed to send message to actor"

### LINKED ISSUE #6968: clean the verbose logs of "failed to send message to actor"
e.g.

```
2022-12-19T05:22:18.019458Z ERROR risingwave_stream::task::stream_manager: actor exit actor=680 error=failed to send message to actor 668: Chunk(
    StreamChunk { cardinality = 9, capacity = 9, data = 
    +---+------+------+--------------+-----------+-------------------------+--------------------+
    | + | 1090 | 1006 | 2078693.480  | nightTime | 2015-07-15 00:00:00.220 | 227298301173833896 |
    | + | 1130 | 1001 | 1875145.304  | nightTime | 2015-07-15 00:00:00.232 | 227298301173833905 |
    | + | 1274 | 1101 | 2215088.700  | nightTime | 2015-07-15 00:00:00.607 | 227298301173834193 |
    | + | 1371 | 1101 | 48247611.488 | nightTime | 2015-07-15 00:00:00.661 | 227298301173834234 |
    | + | 1400 | 1101 | 3948811.188  | nightTime | 2015-07-15 00:00:00.757 | 227298301173834308 |
    | + | 1400 | 1014 | 37841343.104 | nightTime | 2015-07-15 00:00:00.790 | 227298301173834333 |
    | + | 1400 | 1101 | 8667487.428  | nightTime | 2015-07-15 00:00:00.823 | 227298301173834358 |
    | + | 1500 | 1101 | 7225358.244  | nightTime | 2015-07-15 00:00:00.940 | 227298301173834448 |
    | + | 1500 | 1101 | 4628273.036  | nightTime | 2015-07-15 00:00:00.996 | 227298301173834491 |
    +---+------+------+--------------+-----------+-------------------------+--------------------+ },
```

No need to print the detailed DataChunk, I think

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

```
// println!("{:?}", &chunk);
StreamChunk { cardinality: 4, capacity: 4, .. }

// println!("{:#?}", &chunk);
StreamChunk { cardinality: 4, capacity: 4, data: 
+----+---+---+
|  + | 1 | 6 |
|  - | 2 |   |
| U- | 3 | 7 |
| U+ | 4 |   |
+----+---+---+
 }
```

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

None

## Refer to a related PR or issue link (optional)

Closes #6968

### CODE REVIEW

File: src/common/src/array/stream_chunk.rs [hunk 1]
```diff
@@ -276,13 +276,22 @@ impl StreamChunk {
...
+                f,
+                "StreamChunk {{ cardinality = {}, capacity = {}, data = \n{} }}",
+                self.cardinality(),
+                self.capacity(),
+                self.to_pretty_string()
+            )
+        } else {
+            write!(
+                f,
+                "StreamChunk {{ cardinality = {}, capacity = {}, data = ... }}",
```
Comment (BugenZhao) [inline src/common/src/array/stream_chunk.rs:290]: How about refactoring with `debug_struct`? This can be represented with an optional `finish_non_exhaustive`.

https://github.com/risingwavelabs/risingwave/blob/3d067c7e9e66688d7d16bb6faa27e6267047b5b0/src/stream/src/executor/exchange/input.rs#L53-L59

Comment (fuyufjh) [reply src/common/src/array/stream_chunk.rs]: However, it's not applicable to the alternated format, because the `self.to_pretty_string()` need to be printed directly without being quoted in `"`

**Review by BugenZhao — APPROVED** [review]
