### PR TITLE
fix(common): `ListArray::from_protobuf` expects wrong cardinality of inner array

### LINKED ISSUE #8082: bug: casting `NULL` as boolean array has wrong protobuf encoding or decoding
### Describe the bug

Panics at https://github.com/risingwavelabs/risingwave/blob/fef993916abdefea04cb2f236d7590a3aba90cb0/src/common/src/array/column_proto_readers.rs#L71

### To Reproduce

```
create table t(v1 int);
insert into t values(1), (2), (3);
select CAST(NULL as bool[]) from t;
```

### Expected behavior

```sql
query T
select CAST(NULL as bool[]) from t;
----
NULL
NULL
NULL
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

The internal of `ListArray` stores its data flattened. For example, `values (array[1]), (array[]::int[]), (null), (array[2, 3]);` stores an inner `I32Array` with `[1, 2, 3]`, along with offset array `[0, 1, 1, 1, 3]` and null bitmap `TTFT`.

The cardinality of this inner array is not the length of outer array, but the last element of offset array.

Fixes #8082

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

**Review by kwannoel — APPROVED** [review]
> The internal of ListArray stores its data flattened. For example, values (array[1]), (array[]::int[]), (null), (array[2, 3]); stores an inner I32Array with [1, 2, 3], along with offset array [0, 1, 1, 1, 3] and null bitmap TTFT.
>
> The cardinality of this inner array is not the length of outer array, but the last element of offset array.

Can we add this as a doc to `struct ListArray`? It is a good explanation.

File: src/common/src/array/list_array.rs [hunk 1]
```diff
@@ -32,8 +32,6 @@ use crate::types::{
     DatumRef, Scalar, ScalarRefImpl, ToDatumRef,
 };
 
-/// This is a naive implementation of list array.
-/// We will eventually move to a more efficient flatten implementation.
```
Comment (xiangjinwu) [inline src/common/src/array/list_array.rs:36]: https://github.com/risingwavelabs/risingwave/pull/1080#discussion_r830728215
