### PR TITLE
fix: remove `privatelink.targets` from with_options in frontend

### LINKED ISSUE #14879: PrivateLink related attributes are denied as unknown fields
### Describe the bug

```
CREATE SOURCE IF NOT EXISTS live_stream_metrics (
  client_ip varchar,
  user_id varchar,
  report_timestamp timestamp,
)
WITH (
  connector='kafka',
  topic='live_stream_metrics',
  privatelink.endpoint='xxx',
  privatelink.targets='[{"port": 9092}]',
  properties.bootstrap.server='b0-kafka.demosrc.risingwave.internal:9092',
  scan.startup.mode='latest'
) ROW FORMAT JSON
```
`privatelink.targets` is denied as an unknown field.

### Error message/log

```text
"msg": "ERROR: Failed to run the query\n\nCaused by these errors (recent errors listed first):\n  1: gRPC request to meta service failed: Internal error\n  2: Unknown fields in the WITH clause: {\"privatelink.targets\": \"[{\\\"port\\\": 9092}]\"}\n (SQLSTATE XX000)"
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #14879 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/connector/src/common.rs [hunk 1]
```diff
@@ -41,7 +41,7 @@ use crate::source::nats::source::NatsOffset;
 // The file describes the common abstractions for each connector and can be used in both source and
 // sink.
 
-pub const BROKER_REWRITE_MAP_KEY: &str = "broker.rewrite.endpoints";
```
Comment (tabVersion) [inline src/connector/src/common.rs:44]: won't the renaming causing backward compatibility issue?
& why we need to change the key?

File: src/connector/src/common.rs [hunk 2]
```diff
@@ -224,6 +220,20 @@ pub struct KafkaCommon {
...
+#[derive(Debug, Clone, Deserialize, WithOptions)]
+pub struct KafkaPrivateLinkCommon {
+    #[serde(rename = "privatelink.targets")]
+    pub private_link_targets: Option<String>,
+
+    #[serde(rename = "privatelink.endpoint")]
+    pub private_link_endpoint: Option<String>,
+
+    #[serde(rename = "privatelink.broker.rewrite.endpoints")]
+    #[serde_as(as = "Option<JsonString>")]
```
Comment (tabVersion) [inline src/connector/src/common.rs:233]: nice to see `serde_as` also support json string

**Review by tabVersion — COMMENTED** [review]
lgtm as long as it won't cause backward compatibility issue.

File: src/connector/src/common.rs (hunk 1 above)
Comment (StrikeW) [reply src/connector/src/common.rs:44]: Oh, didn't realize that. I revert it back.
Previously the field cannot be deserialized correctly, so I try to change the name and it works, but I found there is a mistake.

**Review by tabVersion — APPROVED** [review]
thanks for your effort!

File: src/connector/src/common.rs [hunk 3]
```diff
@@ -224,6 +220,20 @@ pub struct KafkaCommon {
...
+pub struct KafkaPrivateLinkCommon {
+    #[serde(rename = "privatelink.targets")]
+    pub private_link_targets: Option<String>,
+
+    #[serde(rename = "privatelink.endpoint")]
+    pub private_link_endpoint: Option<String>,
+
+    #[serde(rename = "broker.rewrite.endpoints")]
+    #[serde_as(as = "Option<JsonString>")]
+    pub broker_rewrite_map: Option<HashMap<String, String>>,
```
Comment (xxchan) [inline src/connector/src/common.rs:234]:
```suggestion
    // These two fields are only used in frontend to generate `broker_rewrite_map`
    #[serde(rename = "privatelink.targets")]
    pub private_link_targets: Option<String>,
    #[serde(rename = "privatelink.endpoint")]
    pub private_link_endpoint: Option<String>,

    /// This is generated from `private_link_targets` and `private_link_endpoint`, instead of given by users.
    #[serde(rename = "broker.rewrite.endpoints")]
    #[serde_as(as = "Option<JsonString>")]
    pub broker_rewrite_map: Option<HashMap<String, String>>,
```

Do I understand correctly?

**Review by xxchan — COMMENTED** [review]
I think this approach still have some flaws. e.g., `privatelink.endpoint` is actually removed in the frontend. So adding the config item can make things more complex as we actually have partial config passed and persisted. (They seem to be unused though)

https://github.com/risingwavelabs/risingwave/blob/ded73afefa465108d3a2baf559ec8380e4b4eda5/src/frontend/src/utils/with_options.rs#L142


Maybe we should also remove `privatelink.targets` here similarly instead. (If I understand it correctly that these fields are only used in frontend)
https://github.com/risingwavelabs/risingwave/blob/ded73afefa465108d3a2baf559ec8380e4b4eda5/src/connector/src/source/kafka/private_link.rs#L221

**Comment by xxchan** [comment]
> Our current approach of rejecting unknown fields (in `create_source.rs`) is still WRONG - and to be honest I do not have a solution either ... Certain properties (e.g. the one in this issue) are only **used** in compute node but the **check** happens in frontend, assuming most properties shall be used/checked in frontend - which is wrong or hard to maintain. 🥲

_Originally posted by @xiangjinwu in https://github.com/risingwavelabs/risingwave/issues/14879#issuecomment-1918293836_
            

I'm not sure whether I understand it correctly: Our current approach is that for some properties that are only used in frontend (and not in the config structs), we "consume" them in frontend. 

This has problems
- error prone
- we don't have them listed in the yaml

I think the root problem is that we don't have some structs faithfully reflect the WITH OPTIONS syntax. `ConnectorProperties` is actually only a subset used by the compute node. 

It seems to me that this PR is trying to add those properties only used by the frontend to the `ConnectorProperties`. This approach sounds acceptable to me, but we might need to consider more thoroughly. Otherwise, I'd prefer keeping the current status ("consume the properties") if possible and refactor the part later.

File: src/connector/src/common.rs (hunk 3 above)
Comment (StrikeW) [reply src/connector/src/common.rs:234]: Yes.

File: src/connector/src/source/kafka/private_link.rs [hunk 4]
```diff
@@ -211,16 +213,18 @@ fn is_kafka_connector(with_properties: &BTreeMap<String, String>) -> bool {
...
     let mut broker_rewrite_map = HashMap::new();
-    let servers = get_property_required(properties, kafka_props_broker_key(properties))?;
+    let servers = get_property_required(with_options, kafka_props_broker_key(with_options))?;
     let broker_addrs = servers.split(',').collect_vec();
-    let link_target_value = get_property_required(properties, PRIVATE_LINK_TARGETS_KEY)?;
+    let link_target_value = get_property_required(with_options, PRIVATE_LINK_TARGETS_KEY)?;
     let link_targets: Vec<AwsPrivateLinkItem> =
         serde_json::from_str(link_target_value.as_str()).map_err(|e| anyhow!(e))?;
+    // remove the private link targets from WITH options, as they are useless after we constructed the rewrite mapping
+    with_options.remove(PRIVATE_LINK_TARGETS_KEY);
```
Comment (xxchan) [inline src/connector/src/source/kafka/private_link.rs:227]: If we go this way, we do not need to add them in the `KafkaPrivateLinkCommon` at all. And they are not passed there. We only need one of these two solution.

Comment (xxchan) [reply src/connector/src/source/kafka/private_link.rs:227]: I guess only adding this line without any other changes in this PR is enough to fix the issue.

Comment (StrikeW) [reply src/connector/src/source/kafka/private_link.rs:227]: We can remove `private_link_targets` and `private_link_endpoint` from `KafkaPrivateLinkCommon`, and I'd like to move privatelink related properties to a dedicated structure instead put it in `KafkaCommon`

**Review by xxchan — APPROVED** [review]
LGTM. Please try to double check it works. Thanks!

**Comment by StrikeW** [comment]
Tested
