### PR TITLE
fix: flush error for Startup/Password/SslError

### LINKED ISSUE #7137: bug(pgwire): psql got `SSL SYSCALL error` for login failure
### Describe the bug

```
$ psql -h localhost -p 4566 -d dev -U xxxx
psql: error: connection to server at "localhost" (127.0.0.1), port 4566 failed: SSL SYSCALL error: EOF detected

$ psql -h localhost -p 4566 -d xxx -U root
psql: error: connection to server at "localhost" (127.0.0.1), port 4566 failed: SSL SYSCALL error: EOF detected
```

By the way, when SSL is disabled:

```
$ PGSSLMODE=disable  psql -h localhost -p 4566 -d xxx -U root
psql: error: connection to server at "localhost" (127.0.0.1), port 4566 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

### To Reproduce

As above

### Expected behavior

Postgres: 

```
$ psql -h localhost -p 5432 dev -U xxx -E
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  role "xxx" does not exist

$ psql -h localhost -p 5432 xxx -U eric -E
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "xxx" does not exist
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BowenXiao1999**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Should close #7137

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

File: src/utils/pgwire/src/pg_protocol.rs [hunk 1]
```diff
@@ -243,6 +246,7 @@ where
     }
 
     fn process_startup_msg(&mut self, msg: FeStartupMessage) -> PsqlResult<()> {
+        println!("Start to process start up");
```
Comment (fuyufjh) [inline src/utils/pgwire/src/pg_protocol.rs:249]: remove or use `tracing`

**Comment by BowenXiao1999** [comment]
Test locally it can print out normal error message. (Provide evidence later)

**Review by fuyufjh — APPROVED** [review]
