### PR TITLE
fix(meta): pin & unpin snapshot for mview creation with correct order

### LINKED ISSUE #5592: bug: BatchQuery executor read with expired epoch under parallel e2e
Recently we've enabled the watermark checking, and some bugs of reading with expired epochs are revealed. The batch query executor may read with an expired epoch under parallel e2e, which might be caused by the epoch of creating mview failing to be pinned.

https://buildkite.com/risingwavelabs/pull-request/builds/9338#01837ead-70bb-4053-8d84-d9ef51e23c5f

The `unpin` here might be problematic. With concurrent DDL, a calling of `unpin` may also unpin the snapshot for other creating mviews.

https://github.com/risingwavelabs/risingwave/blob/e081731b77142e44a50f1caaf7decc6accf15107/src/meta/src/barrier/schedule.rs#L185-L199

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As explained in #5592. This PR introduces a simple `SnapshotManager` for pinning & unpinning the snapshot during mview creation.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #5592

### CODE REVIEW

File: src/meta/src/barrier/mod.rs [hunk 1]
```diff
@@ -755,13 +760,8 @@ where
         }
         if self.enable_recovery {
             // If failed, enter recovery mode.
-            let (new_epoch, actors_to_track, create_mview_progress) =
-                self.recovery(state.in_flight_prev_epoch, false).await;
-            *tracker = CreateMviewProgressTracker::default();
-            tracker.add(new_epoch, actors_to_track, vec![]);
-            for progress in &create_mview_progress {
-                tracker.update(progress);
-            }
```
Comment (BugenZhao) [inline src/meta/src/barrier/mod.rs:764]: As we won't recover the creating-mview for now, I think there should be no DDL to track and no progress to update.

**Review by yezizp2012 — APPROVED** [review]
LGTM
