### PR TITLE
fix(unit tests fail on tmpfs): Improved error message and workaround for testing

### LINKED ISSUE #8278: bug(unit tests): Cache unit tests fail when `/tmp` is a `tmpfs` drive
### Describe the bug

If a user's `/tmp` directory is hosted on a `tmpfs` drive (or any RAM disk) then the Hummock Cache unit tests will fail. Specifically, the unit tests in `hummock/file_cache/cache.rs` and `hummock/file_cache/file.rs` will fail when attempting to open a file with the `O_DIRECT` option.  

This failure happens because `tmpfs` and other RAM disks do not support Direct IO; so, if you attempt to open a file with `O_DIRECT` and that file is on a `tmpfs` drive the `open` function will return an error and then the call to `unwrap` will fault.

See: https://ask.fedoraproject.org/t/need-direct-io-for-ramfs-or-tmpfs-or-is-there-another-linux-ram-disk-that-supports-direct-io/3528

Tests which fail due to this issue:
- `test_cache_curd`
- `test_cache_grow`
- `test_recovery`
- `test_file_cache`

### To Reproduce

Create a `tmpfs` drive and update the `test_cache_grow` unit test to put its temporary directory on the `tmpfs` drive. Then run the `test_cache_grow` unit test. The test should then fault with an `Invalid Argument` error.

### Expected behavior

Either for the unit tests to have successfully run or for the tests to fail with an error explaining that the temporary directories cannot be on a `tmpfs` drive and instructions on how to configure the unit tests to use a different location for the temporary directories.

### Additional context

I think the fix can simply be:

1. The ability for a developer to specify a different location for temporary directories to be created when unit tests are run.
1. A note in the Developer Guide explaining that tests will fail if the location of the temporary directory is a `tmpfs` drive and instructions on how override the default location of `/tmp` and provide their own path. This note should include the error message that will be returned so that a developer can search the document if their unit tests fail and find instructions on how to get the unit tests to work.
2. (Optionally) When running a unit tests that uses a temporary directory, check if the temporary directory is on a `tmpfs` drive and, if it is, fail the test and provide an explanatory error message to the user.  You can use the `statfs` in libc to check if a file is on a `tmpfs` drive (https://stackoverflow.com/questions/26635846/how-to-tell-if-a-file-is-on-tmpfs-given-its-path-on-linux).

### PR DESCRIPTION
**Pull request by erichgess**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #8278.

The original issue was created because some unit tests fail if `/tmp` is on a TmpFS file system.

This PR adds two changes:
1. When creating a cache file, it checks if the file is being created on a TmpFS file system, and panics with a descriptive error message.  This previous error message was `Invalid Argument`.
2. An environment variable was added which allows a developer to override what directory temp files for the failing tests are placed in.  If the dev sets `RISINGWAVE_TEST_DIR` then unit tests will place temporary files under that path. Thus, if a dev's machine has `/tmp` on TmpFS they can use `RISINGWAVE_TEST_DIR` to specify a location that is on a valid file system.

To check that the cache location uses a valid file system, I added a new field `fs_type` to the `CacheFileOptions` which will store the file system of the cache file path. This is then checked to make sure that it is not TmpFS and if it is, RW will panic. I added `fs_type` to `CacheFileOptions` because other properties of the file system (such as block size) are already kept there. Alternatively, I could call `statfs` on `path` in `CacheFile::open`, but it seemed unnecessary as that would be duplicating the call made immediately before `CacheFile::open`.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/storage/src/hummock/file_cache/file.rs [hunk 1]
```diff
@@ -82,6 +86,9 @@ impl CacheFile {
     pub async fn open(path: impl AsRef<Path>, options: CacheFileOptions) -> Result<Self> {
         options.assert();
 
+        assert!(options.fs_type != FsType::Tmpfs,
+            "Attempting to create cache file on a TmpFS file system. TmpFS cannot be used because it does not support Direct IO.");
```
Comment (lmatz) [inline src/storage/src/hummock/file_cache/file.rs:90]: The helpful guidance in the developer guide is nice, wonder if you'd like to also put it into the assertion message?

**Review by lmatz — APPROVED** [review]
LGTM, thanks for the fix

File: src/storage/src/hummock/file_cache/file.rs (hunk 1 above)
Comment (erichgess) [reply src/storage/src/hummock/file_cache/file.rs:90]: The bit about using an environment variable to override the location of the cache file? That guidance really only applies if running unit tests, so I could put something like `"Attempting to create cache file on a TmpFS file system. TmpFS cannot be used because it does not support Direct IO. If you are running unit tests, you can use the env var RISINGWAVE_TEST_DIR to specify a valid location for the cache file."`

File: src/storage/src/hummock/file_cache/file.rs [hunk 2]
```diff
@@ -82,6 +86,9 @@ impl CacheFile {
     pub async fn open(path: impl AsRef<Path>, options: CacheFileOptions) -> Result<Self> {
         options.assert();
 
+        assert!(options.fs_type != FsType::Tmpfs,
```
Comment (hzxa21) [inline src/storage/src/hummock/file_cache/file.rs:89]: nits: is `CacheFileOptions::assert` a better place to put this check?

**Review by hzxa21 — APPROVED** [review]
Thanks for the PR!

File: src/storage/src/hummock/file_cache/file.rs (hunk 2 above)
Comment (erichgess) [reply src/storage/src/hummock/file_cache/file.rs:89]: Yes, I think that would be a more fitting place.
