### PR TITLE
fix(pgwire):cancel replace smallint,int,bigint param as xx::smallint,xx::int,xx::bigint 

### LINKED ISSUE #6163: According to the Sysbench benchmark, prepare statements perform worse than non-prepare statements so much
### Describe the bug

Prepare statement performance is almost 1000 times worse than non-prepare statement. Need investigation.

### To Reproduce

# prepare statement:

```
sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-bbef335 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 6.99 qps: 6.99 (r/w/o: 6.99/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 1.00 qps: 1.00 (r/w/o: 1.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 16 tps: 3.99 qps: 3.99 (r/w/o: 3.99/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 16 tps: 2.00 qps: 2.00 (r/w/o: 2.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 9s ] thds: 16 tps: 2.00 qps: 2.00 (r/w/o: 2.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
```

# disable prepare statement:

```shell
 sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--db-ps-mode=disable \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-bbef335 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 2996.46 qps: 2996.46 (r/w/o: 2996.46/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 2994.13 qps: 2994.13 (r/w/o: 2994.13/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 2827.23 qps: 2827.23 (r/w/o: 2827.23/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 2830.63 qps: 2830.63 (r/w/o: 2830.63/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 2930.31 qps: 2930.31 (r/w/o: 2930.31/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 2974.51 qps: 2974.51 (r/w/o: 2974.51/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 16 tps: 2849.87 qps: 2849.87 (r/w/o: 2849.87/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 16 tps: 2903.19 qps: 2903.19 (r/w/o: 2903.19/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 9s ] thds: 16 tps: 2773.98 qps: 2773.98 (r/w/o: 2773.98/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ZENOTME**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

as title. fix #6163 

After the fix, the performance of enabling prepare statement is close to disabling prepare statement.

```
sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-81dd8df (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 3665.38 qps: 3665.38 (r/w/o: 3665.38/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 3700.13 qps: 3700.13 (r/w/o: 3700.13/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 3719.56 qps: 3719.56 (r/w/o: 3719.56/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 3715.93 qps: 3715.93 (r/w/o: 3715.93/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 3715.31 qps: 3715.31 (r/w/o: 3715.31/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 3708.85 qps: 3708.85 (r/w/o: 3708.85/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00

```

```
sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev --db-ps-mode=disable \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-81dd8df (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 3781.90 qps: 3781.90 (r/w/o: 3781.90/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 3906.95 qps: 3906.95 (r/w/o: 3906.95/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 3915.26 qps: 3915.26 (r/w/o: 3915.26/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 3915.68 qps: 3915.68 (r/w/o: 3915.68/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 3872.32 qps: 3872.32 (r/w/o: 3872.32/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 3591.19 qps: 3591.19 (r/w/o: 3591.19/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 16 tps: 3895.55 qps: 3895.55 (r/w/o: 3895.55/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
```

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#6163

### CODE REVIEW

File: src/utils/pgwire/src/pg_extended.rs [hunk 1]
```diff
@@ -238,6 +238,10 @@ pub struct PreparedStatement {
     param_types: Vec<TypeOid>,
 }
 
+lazy_static::lazy_static!{
```
Comment (ZENOTME) [inline src/utils/pgwire/src/pg_extended.rs:241]: > Though it's not the bottleneck for this case, I think we can use a pre-compiled regex with LazyLock here.

Seems once_cell is an unstable feature. To prevent to use unstable features as much as possible, I think using lazy_static here is acceptable 🤔.  @BugenZhao

Comment (BugenZhao) [reply src/utils/pgwire/src/pg_extended.rs]: Don't worry about that. We are relying on unstable features in tons of places. 🤣

- #5385

**Review by BowenXiao1999 — APPROVED** [review]
Can you also summarize the reason?
Is it because cast overhead?

**Comment by ZENOTME** [comment]
> Can you also summarize the reason? Is it because cast overhead?

I summarize this bug in #6163.
