### PR TITLE
fix(optimizer): handle non-injective changes of `logical_rewrite_for_stream`

### LINKED ISSUE #8216: bug: mv with join and duplicate output columns has row indices hidden
### Describe the bug

See below.

### To Reproduce

```
---- START
-- Setup
CREATE TABLE auction (
    id bigint,
    item_name character varying,
    description character varying,
    initial_bid bigint,
    reserve bigint,
    date_time timestamp,
    expires timestamp,
    seller bigint,
    category bigint,
    extra character varying,
    PRIMARY KEY (id)
);

CREATE TABLE alltypes1 (
    c1 boolean,
    c2 smallint,
    c3 int,
    c4 bigint,
    c5 real,
    c6 double,
    c7 numeric,
    c8 date,
    c9 character varying,
    c10 time,
    c11 timestamp,
    c13 interval,
    c14 STRUCT < a int >,
    c15 int[],
    c16 character varying[]
);

CREATE MATERIALIZED VIEW m5 AS
SELECT
    t_2.expires AS col_0,
    t_2.expires AS col_1
FROM
    auction AS t_2
GROUP BY
    t_2.reserve,
    t_2.initial_bid,
    t_2.expires
HAVING
    TRUE;

-- EXPLAIN (trace) CREATE MATERIALIZED VIEW m7 AS SELECT t_0.col_0 AS col_0, t_0.col_0 AS col_1 FROM m5 AS t_0 GROUP BY t_0.col_0 HAVING (TIME '01:36:09') IN (SELECT TIME '01:11:11' AS col_0 FROM alltypes1 AS t_1);
CREATE MATERIALIZED VIEW m7 AS
SELECT
    t_0.col_0 AS col_0,
    t_0.col_0 AS col_1
FROM
    m5 AS t_0
GROUP BY
    t_0.col_0
HAVING (TIME '01:36:09') IN (
        SELECT
            TIME '01:11:11' AS col_0
        FROM
            alltypes1 AS t_1);
select * from m7;
```

output
```
 col_0 
-------
(0 rows)

```

### Expected behavior

Return both columns.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by st1page**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #8216 

```
dev=>     create table t(x int);
CREATE_TABLE
dev=> explain create materialized view mv as     SELECT t.x x1, t.x x2 FROM t join t tt ON t.x=tt.x;
                                                                                      QUERY PLAN                                                                                       
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [t.x(hidden), x1, t._row_id(hidden), t._row_id#1(hidden), t.x#1(hidden), x2], pk_columns: [t._row_id, t._row_id#1, x2, t.x#1], pk_conflict: "no check" }
 └─StreamProject { exprs: [t.x, t.x, t._row_id, t._row_id, t.x, t.x] }
   └─StreamHashJoin { type: Inner, predicate: t.x = t.x }
     ├─StreamExchange { dist: HashShard(t.x) }
     | └─StreamTableScan { table: t, columns: [x, _row_id] }
     └─StreamExchange { dist: HashShard(t.x) }
       └─StreamTableScan { table: t, columns: [x, _row_id] }
(7 rows)


```
## Checklist For Contributors

- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### CODE REVIEW

File: src/frontend/src/optimizer/mod.rs [hunk 1]
```diff
@@ -294,8 +295,35 @@ impl PlanRoot {
...
+                    } else {
+                        let mut output_indices = (0..plan.schema().len()).collect_vec();
+                        #[allow(unused_assignments)]
+                        let (mut map, mut target_size) = out_col_change.into_parts();
+
+                        // TODO(st1page): https://github.com/risingwavelabs/risingwave/issues/7234
+                        // assert_eq!(target_size, output_indices.len());
+                        target_size = plan.schema().len();
+                        let mut tar_exists = vec![false; target_size];
+                        for i in map.iter_mut().flatten() {
```
Comment (jon-chuang) [inline src/frontend/src/optimizer/mod.rs:312]: I'm not so sure how robust this method is. I don't think we can ensure the ordering of the columns in this case.

An actual solution is to ignore a line below:

```rust
self.out_fields = out_col_change.rewrite_bitset(&self.out_fields);
```

But I'm not so comfortable either. I prefer instead to fix problem at the root (i.e. similar to https://github.com/risingwavelabs/risingwave/pull/8267). For this PR, perhaps we can introduce an `debug_assert` injectivity check to the `out_col_change` here.

File: src/frontend/src/optimizer/mod.rs [hunk 2]
```diff
@@ -294,8 +295,35 @@ impl PlanRoot {
...
+                            if tar_exists[*i] {
+                                output_indices.push(*i);
```
Comment (jon-chuang) [inline src/frontend/src/optimizer/mod.rs:314]: basically, this won't work for the following query:

```sql
create table t(x int, y int);
explain create materialized view mv as  SELECT t.x x1, t.x x2, y FROM t join t tt ON t.x=tt.x;
````
As it will assign the name x2 to the y column and the name y to the secondary t.x column

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: It's probably possible to work around so that the ordering is respected.

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: > What bothers me a bit is that in our original problem, the element already exists somewhere in the output, we just have no idea where it is anymore, so we end up duplicating elements, and we no longer prune away the useless columns.

I am still much confused and do not know what's wrong... I think the root cause might be the `logical_rewrite_for_stream` of `LogicalJoin` adding the join key into the output_indices brutally to solve the "stream key issue" https://singularity-data.quip.com/3lUJAQMthect/RFC-Streamkey-instead-pk

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: If the mapping is not injective, it will mistakenly believe that one of the keys is missing.

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: Hmm indeed, the stream plan in https://github.com/risingwavelabs/risingwave/pull/8267 does indeed seem to contain the join key a second time erroneously, seems it does not completely get rid of repeated output indices (but in this case it does not cause non-injectivity) https://github.com/risingwavelabs/risingwave/blob/399ec7ca575f60c0034efcaeab89ed35fbdd5328/src/frontend/planner_test/tests/testdata/join.yaml#L612

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: The logical_rewrite_for_stream's interface definition allows returning a non-injectivity change. And in fact the behavior gives the upper operator a chance to merge two columns into one. The issue might be we do not handle the non-injectivity here but not the join gives us a non-injectivity change?

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: In other words, maybe making sure everyone calling the `logical_rewrite_for_stream` can handle the non-injectivity is easier than making sure every plannode's `logical_rewrite_for_stream` not returning a non-injectivity

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: I still believe non injective is wrong. We end up becoming confused and forgetting certain columns and relying on their supposed aliases. I am afraid that something subtle will break due to this if we simply fix superficially. 

To be clear, duplicate output indices are not the problem. If we can rewrite `logical_rewrite_for_stream` so that it returns an injective mapping, there is nothing with having duplicate output indices

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: > gives the upper operator a chance to merge two columns into one 

Perhaps, but we do not then prune away the aliased columns...

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: > Perhaps, but we do not then prune away the aliased columns...

Yes. I mean that we cannot do the prune on the top of the stream plan or a Materialize. But how about other operators? considering if there is a Aggregation with max(input_ref(0)), max(input_ref(1))...

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: > We end up becoming confused and forgetting certain columns and relying on their supposed aliases. 

In fact, this PR's fix gives the same plan with #8267. And actually, the query's output has two same columns, the only way is to copy it with a project operator.

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: > the only way is to copy it with a project operator.

Well, what I'm saying is that the output actually has 3 of the same columns...

Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: Btw, why doesn't this work for stream?
```rust
LogicalProject::with_out_fields(plan, &self.out_fields)
```
I guess for stream, we still care about hidden columns?

File: src/frontend/src/optimizer/mod.rs (hunk 1 above)
Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:312]: For that reason alone, I think it's safer for us to avoid non-injectivity, unless we can demonstrate that mapping to an alias will never result in a broken chain of assumptions.

(but this entire issue originates from the fact that it does).

File: src/frontend/src/optimizer/mod.rs (hunk 2 above)
Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: Yes, the required column is the columns declared in the user's query and the others is derived by `logical_rewrite_for_stream` and as the stream key.

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: your fix also give 3 same columns...
```
- name: Repeated columns in project should not interfere with join result (https://github.com/risingwavelabs/risingwave/issues/8216)
  sql: |
    create table t(x int);
    SELECT t.x x1, t.x x2 FROM t join t tt ON t.x=tt.x;
  stream_plan: |
    StreamMaterialize { columns: [x1, x2, t._row_id(hidden), t._row_id#1(hidden), t.x(hidden)], pk_columns: [t._row_id, t._row_id#1, x2, t.x], pk_conflict: "no check" }
    └─StreamProject { exprs: [t.x, t.x, t._row_id, t._row_id, t.x] }
      └─StreamHashJoin { type: Inner, predicate: t.x = t.x, output: [t.x, t._row_id, t._row_id, t.x] }
        ├─StreamExchange { dist: HashShard(t.x) }
        | └─StreamTableScan { table: t, columns: [t.x, t._row_id], pk: [t._row_id], dist: UpstreamHashShard(t._row_id) }
        └─StreamExchange { dist: HashShard(t.x) }
          └─StreamTableScan { table: t, columns: [t.x, t._row_id], pk: [t._row_id], dist: UpstreamHashShard(t._row_id) }

```

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: the two non-hidden column is produced by the non-injectivity returning which is unavoidable. And the hidden column is produced by the `LogicalJoin::logical_rewrite_for_stream`. The only thing we can optimize is to check if the join key has been in the original output indices in the rewriting. But we should do nothing for the non-injectivity. They are totally two different things and we can not mix them up.

File: src/frontend/src/optimizer/mod.rs (hunk 1 above)
Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:312]: Somehow, I get the feeling that this optimization should not happen in the `logical_rewrite_for_stream` step, but rather, as an optimization pass.

File: src/frontend/src/optimizer/mod.rs (hunk 2 above)
Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:314]: This is inaccurate. This PR produces 4 of the same column:
```
[t.x(hidden), x1, t._row_id(hidden), t._row_id#1(hidden), t.x#1(hidden), x2]
```
at pos 0, 1, and -1, -2

Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:314]: So the join's implementation has some wrong and should reduce the column he adds. But the issue is not related to the non-injectivity.

File: src/frontend/src/optimizer/mod.rs (hunk 1 above)
Comment (st1page) [reply src/frontend/src/optimizer/mod.rs:312]: I know your concern here. But the non-injection mapping here can not bring a question. The issue can only be with the non-surjection. Let's think about the changes_column here.
non-injection mapping: `[0->1, 1->1]` your original cloumn[0] and column[1] are at position 1 now, :heavy_check_mark: 
non-surjection mapping: `[0->0, 0->1]` your original cloumn[0] could be position 0 or 1, you can choose one. :x:

**Comment by st1page** [comment]
Ok, after some debugging I think you are right. But things are not because logical_rewrite_for_stream should not return non-injectivity changes mapping. It is because output_indices: [0, 0] generates a non-surjection o2i_mapping...

File: src/frontend/src/optimizer/mod.rs (hunk 1 above)
Comment (jon-chuang) [reply src/frontend/src/optimizer/mod.rs:312]: Created a proposal here: https://github.com/risingwavelabs/risingwave/issues/8277

**Comment by jon-chuang** [comment]
> should not return non-injectivity changes mapping.

Agreed this is not the true root cause. It can be fixed as long as the parent operator understands how to handle non-injective mapping. See materialized view section of https://github.com/risingwavelabs/risingwave/issues/8277 for example of this.

**Comment by st1page** [comment]
Can you approve this PR now? At least we are not sure if there are other plan nodes can return a non-injective mapping @jon-chuang

**Review by jon-chuang — APPROVED** [review]
Yes, this and https://github.com/risingwavelabs/risingwave/pull/8267 should be viewed as hot fixes. Let's find a proper solution long term

**Review by chenzl25 — APPROVED** [review]
LGTM. Could you please add the test case provided in the PR description to the planner test? It is not easy to understand this hotfix without a test case.

**Comment by st1page** [comment]
> LGTM. Could you please add the test case provided in the PR description to the planner test? It is not easy to understand this hotfix without a test case.

Not very easy. :lark_cry: After the fix in #8267 I can not find a way to cover this branch. It is just prevention of the unexpected non-injective returning
