### PR TITLE
fix(udf): allow `aggregate:` prefixed sql udf

### LINKED ISSUE #18202: cannot prefix a SQL UDF to make it an aggregate function
### Describe the bug

```sql
create function as2 ( int[] ) returns bigint language sql as 'select array_sum($1)';
select aggregate:as2(a) from (values (1), (2)) t(a);
```

output:

```
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: failed to build executor
  2: Expr error
  3: Failed to decode prost: field not found `identifier`
```

expected:

```
3
```

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes #18202.

## Checklist

- [ ] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

File: src/frontend/src/binder/expr/function/mod.rs [hunk 1]
```diff
@@ -483,30 +488,15 @@ impl Binder {
...
-            };
-            udf_context.insert(c, e);
+        for (i, arg) in args.into_iter().enumerate() {
+            if func.arg_names[i].is_empty() {
+                udf_context.insert(format!("${}", i + 1), arg);
+            } else {
+                // The index mapping here is accurate
+                // So that we could directly use the index
+                udf_context.insert(func.arg_names[i].clone(), arg);
+            }
```
Comment (chenzl25) [inline src/frontend/src/binder/expr/function/mod.rs:499]: Actually, I don't quite get how this context works. Could you please elaborate it more?

**Review by chenzl25 — APPROVED** [review]
Generally LGTM

File: src/frontend/src/binder/expr/function/mod.rs (hunk 1 above)
Comment (stdrc) [reply src/frontend/src/binder/expr/function/mod.rs:499]: The context contains a mapping of `argument name -> argument expression`. If an argument has no name, `$n` will be used as its name. I just updated the comment to make it more clear.
