### PR TITLE
fix(parser): disallow empty object names 

### LINKED ISSUE #6022: bug: empty object names are allowed
### Describe the bug

_No response_

### To Reproduce

```sql
dev=> create table ""(x int);
CREATE_TABLE
dev=> select * from "";
 x 
---
(0 rows)

dev=> create schema "";
CREATE_SCHEMA
dev=> create table "".t(x int);
CREATE_TABLE
dev=> select * from "".t;
 x 
---
(0 rows)
```

### Expected behavior

postgres:
```
postgres=# create table ""(x int);
ERROR:  zero-length delimited identifier at or near """"
LINE 1: create table ""(x int);
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by broccoliSpicy**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #6022

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- ~~I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features)~~.
- ~~I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- ~~[ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.~~

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

File: src/sqlparser/src/ast/mod.rs [hunk 1]
```diff
@@ -96,7 +97,10 @@ pub struct Ident {
 
 impl Ident {
     /// Create a new identifier with the given value and no quotes.
-    pub fn new<S>(value: S) -> Self
+    /// In situations like construct a identifier from existing object
+    /// names, we may prefer to use this 'cause the input string is
+    /// guanteed to be not empty.
+    pub fn new_safe<S>(value: S) -> Self
```
Comment (xxchan) [inline src/sqlparser/src/ast/mod.rs:103]: I don't think it's necessary to add `_safe` to this function, which makes this PR harder to review. Adding some doc comments should be enought.

BTW, `_unchecked` might be better than `_safe` (it's actually unsafe..? 😄)

File: src/sqlparser/src/ast/mod.rs [hunk 2]
```diff
@@ -106,19 +110,57 @@ impl Ident {
...
+            Err(ParserError::ParserError(format!(
+                "zero-length delimited identifier at or near \"{w}\""
+            )))
+        } else {
+            Ok(Ident {
+                value: w.value.clone(),
+                quote_style: w.quote_style,
+            })
+        }
+    }
```
Comment (xxchan) [inline src/sqlparser/src/ast/mod.rs:125]: Since `new_from_word` is only used in `Word::to_ident`, I think we can simply put the implementation there.

File: src/sqlparser/src/ast/mod.rs [hunk 3]
```diff
@@ -106,19 +110,57 @@ impl Ident {
...
+
+    /// Create a new quoted identifier with the given quote and value.
+    /// the inputs are guanteed to be legal.
+    pub fn new_with_quote_safe<S>(quote: char, value: S) -> Self
```
Comment (xxchan) [inline src/sqlparser/src/ast/mod.rs:129]:
```suggestion
    pub fn with_quote_unchecked<S>(quote: char, value: S) -> Self
```

According to rust naming convention. https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case:~:text=new%20or-,with_more_details,-Conversion%20constructors

File: src/sqlparser/src/ast/mod.rs [hunk 4]
```diff
@@ -106,19 +110,57 @@ impl Ident {
...
     where
         S: Into<String>,
     {
-        assert!(quote == '\'' || quote == '"' || quote == '`' || quote == '[');
```
Comment (xxchan) [inline src/sqlparser/src/ast/mod.rs:115]: I think we can keep the assertion?

File: src/sqlparser/src/ast/mod.rs [hunk 5]
```diff
@@ -106,19 +110,57 @@ impl Ident {
...
         Ident {
             value: value.into(),
             quote_style: Some(quote),
         }
     }
 
+    /// Create a new quoted identifier with the given quote and value.
+    /// returns ParserError when the given string is empty or the given quote is illegal.
+    pub fn new_with_quote_check<S>(quote: char, value: S) -> Result<Ident, ParserError>
```
Comment (xxchan) [inline src/sqlparser/src/ast/mod.rs:141]: Where is this function used? I didn't find that

**Review by xxchan — COMMENTED** [review]
Generally LGTM. Thanks for your contribution!

File: src/sqlparser/src/ast/mod.rs (hunk 1 above)
Comment (broccoliSpicy) [reply src/sqlparser/src/ast/mod.rs]: I was dumb...

File: src/sqlparser/src/ast/mod.rs (hunk 2 above)
Comment (broccoliSpicy) [reply src/sqlparser/src/ast/mod.rs]: removed implementation to Word::to_ident

File: src/sqlparser/src/ast/mod.rs (hunk 4 above)
Comment (broccoliSpicy) [reply src/sqlparser/src/ast/mod.rs:115]: Well, if the function name is _unchecked, doesn't seem coherent to add assertions.

File: src/sqlparser/src/ast/mod.rs (hunk 5 above)
Comment (broccoliSpicy) [reply src/sqlparser/src/ast/mod.rs]: shoud I remove this function? it might be useful, and I just found this asymmetry jarring defining only a unchecked function

**Review by xxchan — APPROVED** [review]
